### ISSUE TITLE
Russian text issuses

### ISSUE THREAD

**Issue by igor523** [swiftyspiffy/TwitchLib#10]
Hello!

Library (version 1.0.5 from NuGet) doesn't seems to work with Russian text - all of the Russian characters in received messages becomes unreadable, and in sent messages they became not visible. For example, this code:

`chatWrapper.SendMessage("Тестовое сообщение! Test message!");`

sends "! Test message" in chat instead of given string.

And any received Russian character becomes something like this: 

`"РўРµСЃС‚РѕРІРѕРµ СЃРѕРѕР±С‰РµРЅРёРµ! Test message!"`

Maybe, it's something related to IRC part of your lib? Twitch server expects UTF8 without BOM, but perhaps gets something else.
I think, that some other languages could be affected too.

Thank you!

**Comment by swiftyspiffy** [comment]
I'll look into this now, thanks for pointing it out!

**Comment by igor523** [comment]
@swiftyspiffy, thanks! I've found a workaround for this, but fixing the lib itself would be useful
```
public void SendMessage(string message)
        {
            string content = message;
            

            content = String.Format(":{0}!{0}@{0}.tmi.twitch.tv PRIVMSG #{1} :", parameters.TwitchUsername, targetChannel.ToLower());
            content += message;
            var enc = Encoding.UTF8;
            byte[] orig = enc.GetBytes(content);
            content = Encoding.GetEncoding(1251).GetString(orig);
            chat.SendRaw(content);
        }
```

**Comment by swiftyspiffy** [comment]
I'm getting ???????? as replacements for Russian characters using the existing solution, your solution, and a new solution I just came up with, for reasons I'm not quite sure of.  Would you mind trying this solution in your custom SendMessage function (I have substituted my values with yours to make it easier)?

`
public void SendMessage(string message)
{
    string twitchMessage = $":{parameters.TwitchUsername}!{parameters.TwitchUsername}@{parameters.TwitchUsername}.tmi.twitch.tv PRIVMSG #{targetChannel.ToLower()} :{message}";
    Encoding enc = new UTF8Encoding(false);
    chat.SendRaw(twitchMessage);
}
`
I'd like to stick to a avoid using a specific code page if possible (windows-1251). Anyways, if you can test that and get back to me, that'd be awesome.

Thanks!

**Comment by igor523** [comment]
Ready to try it now. Waiting for your edit...

**Comment by swiftyspiffy** [comment]
So if I understand your solution above, it essentially encodes the twitch message via UTF8 encoding, and then "windows-1251" is a subset of UTF8, and uses that to decode it? I'm having issues thinking of a solution that would not cater to a single region, but would be general instead.  Perhaps an optional param to decode based on a passed in decode object?

**Comment by igor523** [comment]
> Perhaps an optional param to decode based on a passed in decode object?

Maybe... Or you can try to mess around with default codepage. I think, that 1251 is the default for Russian language. Perhaps, there is some way to get the default encoding of the system, that lib runs on? (sorry, I'm a new in .net)

**Comment by swiftyspiffy** [comment]
That's a good idea, .net has Encoding.Default which fetches the default system ANSII code page.  Let me get a solution for that real quick. I'm thinking by default it uses the default, but it can be reassigned as an optional param.

**Comment by igor523** [comment]
Found it! Works for me

```C#
public void SendMessage(string message)
        {
            string content = message;
            content = content.Replace("\n", " ");
            content = String.Format(":{0}!{0}@{0}.tmi.twitch.tv PRIVMSG #{1} :", parameters.TwitchUsername, targetChannel.ToLower());
            content += message;
            var enc = Encoding.UTF8;
            byte[] orig = enc.GetBytes(content);
            content = Encoding.Default.GetString(orig);
            chat.SendRaw(content);
        }
```

**Comment by swiftyspiffy** [comment]
Awesome, will implement that and run it through a few tests, and then deploy a package to NuGet tomorrow day/night (EST).

**Comment by igor523** [comment]
Thank you! That was really quick! :)

**Comment by swiftyspiffy** [comment]
I'll also apply a fix similar to your solution to fix reading Russian characters, I tested it seems to work on my end, if you want to give it a go:

```
Encoding.UTF8.GetString(Encoding.Default.GetBytes(e.Line))
```

**Comment by swiftyspiffy** [comment]
NuGet package updated!
