### ISSUE TITLE
PubSub: Failed to listen! Error: ERR_BADAUTH

### ISSUE THREAD

**Issue by JustMeDaFaq** [swiftyspiffy/TwitchLib#101]
Hi,
getting this error when trying to use pubsub, using this site to generate my oauth token:

https://burkeblack.tv/testapp/twitchauth.php

do i need any other scopes for pubsub to work?

Just giving my name, channel (my channel) oauth token and connecting. Can Send messages.... but pressing the pubsub button on your example projects results in this error message

**Comment by swiftyspiffy** [comment]
Looking into this now. Last time I tested this, you just needed a single scope (maybe not even a single scope). Twitch just wants to verify you are who you say you are.

**Comment by JustMeDaFaq** [comment]
Yeah, it didnt worked in the example application. Tho, no idea why, but just tried it today again and it works now.

Could it be some network issues yesterday on my side? 
No idea, tho, thank you!

**Comment by swiftyspiffy** [comment]
There was another issue similar to this earlier, and it seemed like they had a similar outcome to you. It initially wasn't working and then giving it a go another day and it randomly started working.

Anyways, I'll go ahead and close this :)
