### ISSUE TITLE
Unfollow of an user will trigger service.OnNewFollowersDetected with all current follower

### ISSUE THREAD

**Issue by JustMeDaFaq** [swiftyspiffy/TwitchLib#103]
Hi,

tested it also with your example application by doing following steps:

-Set client id
-Starting follower service on my channel
-used an test account to follow my channel 
    =>Triggers as expected with just the new follow(s) / Messagebox pops up in your excample application
-Then just unfollow with that test account
    => give it some time and it triggers the OnNewFollowersDetected Event with all current follower (Messagebox will pop up listing them in your example application)

**Comment by swiftyspiffy** [comment]
This indeed is what happens. Looking into it now, not a use case I considered.

**Comment by swiftyspiffy** [comment]
I believe this has been fixed. I'm going to go ahead and close it. If for some reason you find that it hasn't, feel free to reopen it.
