### ISSUE TITLE
Is it possible to save the login tokens generated from the login, to use them next time?

### ISSUE THREAD

**Issue by PFCKrutonium** [swiftyspiffy/TwitchLib#105]
For example, lets say I have a logged in TwitchClient, how can I save the credentials, so I don't have to get the user to re-auth next time? I could save the user/pass, but is there an oauth token in there or somthing I can save?

**Comment by swiftyspiffy** [comment]
The credentails are not converted or used to generate auth keys. Much like actual IRC, Twitch's IRC-esque chat interface is authorized using raw text of the username and oauth token. So, beyond the user/oauth token used to authenticate, there's nothing else to use/manipulate unfortunately.

**Comment by PFCKrutonium** [comment]
How can I grab that oauth/use it to auth later? Or can I?

**Comment by PFCKrutonium** [comment]
Never Mind, I'm an idiot.

**Comment by swiftyspiffy** [comment]
:)

**Comment by PFCKrutonium** [comment]
BTW, I like how you have spruced up the lib, I should go back and fix my VB Example at some point, though at this point I've switched to mostly C#.

My VB example current dies at an error 400. _Shrug_

**Comment by swiftyspiffy** [comment]
What do you mean spruced up? you mean in the branch I have going for reorganization of it? Ya, that's been a long time coming, should have been done much earlier! If you're using an old version of the library in your VB project, there's a good chance you get that 400 because a client_id is not being set.

**Comment by PFCKrutonium** [comment]
Most likely, yah. Right now I am just playing with making a far more in-depth bot in C#.

I just spent 3 hours trying to solve a bug, that was literally I forgot to type `account.Connect();`
