### ISSUE TITLE
Is there a way to get the current title and game of a stream?

### ISSUE THREAD

**Issue by PFCKrutonium** [swiftyspiffy/TwitchLib#106]

**Comment by swiftyspiffy** [comment]
Get the stream object (they must be online):
```
TwitchLib.Models.API.Stream stream = TwitchLib.TwitchApi.Streams.GetStream("burkeblack");
Console.WriteLine($"Current title: {stream.Channel.Status}");
Console.WriteLine($"Current game: {stream.Game}");
```
or
Get the channel object (they can be on or offline):
```
TwitchLib.Models.API.Channel channel = TwitchLib.TwitchApi.Channels.GetChannel("burkeblack");
Console.WriteLine($"Current title: {channel.Status}");
Console.WriteLine($"Current game: {channel.Game}");
```

**Comment by PFCKrutonium** [comment]
Thanks! I couldn't figure it out, though this makes it stupid simple!

**Comment by PFCKrutonium** [comment]
I'm using the library on NuGet, and `TwitchLib.TwitchApi.Channels.GetChannel` does not exist, starting at Channels - and my use case needs to work when the streamer is offline.

**Comment by swiftyspiffy** [comment]
Oops, sorry, was thinking about the latest GitHub code, not NuGet.

To do it with the NuGet package, it'd be something like:
```
TwitchLib.Models.API.Channel channel = TwitchLib.TwitchApi.GetChannel("burkeblack");
Console.WriteLine($"Current title: {channel.Status}");
Console.WriteLine($"Current game: {channel.Game}");
```

**Comment by PFCKrutonium** [comment]
And how can I get a list of current viewers?

**Comment by PFCKrutonium** [comment]
So I did this `var channel = TwitchApi.GetChannel(Properties.Settings.Default.StreamerAccountName).Result;` but it's telling me I need to set a client-id - Can I do this using the logged in account? If so, how?

**Comment by swiftyspiffy** [comment]
Yes, Twitch requires a valid client Id be set before using the API (it's their way of identifying who you are). To do this, you'd do something like (this needs to be done before any API calls):
```
TwitchLib.TwitchApi.SetClientId("client_id_here");
```

To get chatters, something like:
```
TwitchLib.TwitchApi.GetChatters("burkeblack");
```

**Comment by PFCKrutonium** [comment]
Where do I get the client id?

**Comment by swiftyspiffy** [comment]
This is the run down on the requirement and how to get it:
https://blog.twitch.tv/client-id-required-for-kraken-api-calls-afbb8e95f843#.atec0s7dp

**Comment by PFCKrutonium** [comment]
Okay, so I did
```
            TwitchLib.TwitchApi.SetClientId("removed");
            var channel = TwitchApi.GetChannel("itslewdicolo").Result;
            MessageBox.Show(channel.Status + channel.Game);
```

but it just sits there and never returns.

**Comment by swiftyspiffy** [comment]
Generally it's not a good idea to force the result of an async call via `.Result` unless you are 100% sure race conditions cannot occur.

I would recommend making whatever function/method that uses your code above asynchronous by adding `async` keyword to it.
Demonstrated here: https://github.com/swiftyspiffy/TwitchLib/blob/master/TwitchLibExample/TwitchLibExample/Form1.cs#L289

**Comment by swiftyspiffy** [comment]
I'm going to go ahead and close this, as it seems answered :)
