### ISSUE TITLE
The remote server returned an error: (400) Bad Request.

### ISSUE THREAD

**Issue by term1nal** [swiftyspiffy/TwitchLib#107]
Testing out the Example application, this error continues to occur. "Twitch API" tab errors on setting required client ID. The "Twitch API 5" tab allows the set of required client ID then errors on the fetch of Get Users.

**Comment by swiftyspiffy** [comment]
Will look into this now.

**Comment by swiftyspiffy** [comment]
I tested it just now. Results below:

![image](http://swfty.xyz/?id=618HoD640)

Are you certain you're using a valid client id and channel?

**Comment by term1nal** [comment]
I am uncertain if I am using a "valid" client id. I wasn't aware there was a required formatting.
