### ISSUE TITLE
OnStreamUp/Down doesnt fire

### ISSUE THREAD

**Issue by JustMeDaFaq** [swiftyspiffy/TwitchLib#109]
Hi,
tried listening to:
ListenToChatModeratorActions
ListenToBitsEvents
ListenToVideoPlayback
ListenToWhispers

[pubsub].OnStreamUp and [pubsub].OnStreamDown events dont fire. Do i need to start something different than pubsub before using it?

**Comment by swiftyspiffy** [comment]
ListenToVideoPlayback I believe is supposed to trigger OnStreamDown and OnStreamUp.

That being said, this topic is not officially supported by Twitch, so it's possible they broke it (I haven't tested it in some time). Their GitHub API repo has the supported topics (currently bits and whispers). The other topics in the library were taken from various online sources that had listed them, but not from official Twitch. Twitch PubSub: https://github.com/justintv/Twitch-API/tree/master/PubSub

**Comment by JustMeDaFaq** [comment]
Seems that it doesnt work anymore. Just pulling now instead of using the pubsub.

Just a side question, is it possible to detect anyhow if chat is in slowmode?

**Comment by swiftyspiffy** [comment]
Ya, I would recommend pulling for the time being.

Slowmode is announced in the OnChannelStateChanged event. You can listen to this event and utilize the ChannelState object which contains, among other things, a boolean for SlowMode.

**Comment by JustMeDaFaq** [comment]
Thanks! :)
