### ISSUE TITLE
OnHostingStarted is mislabeled in docs

### ISSUE THREAD

**Issue by dastrn** [swiftyspiffy/TwitchLib#113]
The OnHostingStarted event is firing when the user's channel hosts someone else, but is documented to suggest it fires when someone else hosts the user's channel.

1. Documentation needs updated.
2. We need an event to fire for the intended scenario.

**Comment by swiftyspiffy** [comment]
You're right, the docs are significantly out of date. Will work on shortly. Currently working on Twitch Video Upload and then working on GetAllStreams from v5, and then I'll do this.

Been quite busy lately, sorry :(

**Comment by MagiusRerecros** [comment]
I'm glad someone mentioned this; I've been playing around with this event for a while, trying to figure out if I was just doing something wrong, or if documentation on the event was just mislabeled.

**Comment by swiftyspiffy** [comment]
This is certainly not the first time it's been mentioned either. I'll fix it after I figure out this chunked twitch video upload flow.

**Comment by swiftyspiffy** [comment]
Upon further review, this is way the library should be laid out as far as hosting goes:

- OnHostingStarted: This is when the library receives a HOSTTARGET message from Twitch. This event/data does contain the number of viewers.
- OnHostingStopped: This is fired when a HOSTTARGET message from Twitch received with no channel specified (hence stopped hosting).
- OnNowHosting: This fires when the library receives a NOTICE message from Twitch describing the host action. This event/data does not contain the number of viewers.

The OnHostingStarted and OnNowHosting are basically the same, just fire as a result of different messages received.

You might be wondering about the notification that is sent to the broadcaster about who hosts them and the number of viewers. As far as I can gather, there's no way to get the actual notification broadcasters see in their chat. The on stream host notifications you see various streamers have I think is a result of pulling a TMI endpoint. If that's the case, I can build a simple service to do that, but I'd like to verify that there is no way via irc (or even pubsub) to gather this kind of info.

What do you guys think?

Also, will update XML comments and github docs to reflect proper causes for event firing.

**Comment by dastrn** [comment]
Makes good sense to me, sir.

Thanks for your work!

**Comment by swiftyspiffy** [comment]
That being said of course, I can add an event that, if the bot is connected as the broadcaster, would fire when the host notification occurs. It would only work when the library is connected as the broadcaster, but as I understand it, this is the case many times, so some people may find this useful. Will implement in a few hours.

**Comment by dastrn** [comment]
I actually use 2 concurrent connections with my bot: 1 as the bot account, 1 as the caster account. This lets me post to chat with bot account, but still use caster-only features like promoting someone to moderator.

**Comment by dastrn** [comment]
I will for sure make great use of the host notification if it's added.
Thanks for your work!

**Comment by swiftyspiffy** [comment]
That's an interesting use case I hadn't thought of (running two clients concurrently with one being a bot and one being the broadcaster).

Anyways, I think I have something here that may work. It adds the event `OnBeingHosted`. The way this works is that, if you listen to the event, you MUST be joining the broadcaster's channel. If you aren't it will throw an exception (`BadListenException`). This can be overriden (if you plan on joining the broadcaster's channel in addition to other channels) by settings `OverrideBeingHostedCheck` to `False` in `TwitchClient`. 

The event OnBeingHosted has the following data (I hope this is enough for you, not sure exactly what you wanted):
 - BotUsername - The username of the bot that received the data from Twitch.
 - HostedByChannel - The channel that has started hosting you.
 - Viewers - Integer representing the number of viewers from the host.
 - Channel - Broadcaster's channel used for identification with multiple joined channels.

It should be noted that if no viewer count is provided for the host, the `viewers` integer will be -1.

Commit: 3eecb23d3c2cd790d8743cf1c1a8be163aaf6584

Cheers :)

**Comment by swiftyspiffy** [comment]
I'm going to go ahead and close this as the issue appears resolved :)

**Comment by MagiusRerecros** [comment]
The OnBeingHosted event is a good idea, and is basically what I was looking for, although I was hoping there'd be something available to do the same thing when the account the bot is using is NOT the broadcaster's account.

However, since Twitch itself doesn't really have anything officially supported for that, I'll just have to stick with the unsupported API calls via GetChannelHostsAsync.
