### ISSUE TITLE
onChatCommandReceived never gets called.

### ISSUE THREAD

**Issue by RamonRobben** [swiftyspiffy/TwitchLib#114]
So whenever I try to execute a command in my channel like !points or !hello the event never gets called. Even if another user tries it it just never executes.

**Comment by MagiusRerecros** [comment]
1. You made sure that the bot is connected to the same channel where the commands are being executed, right? (yes, this is a stupid question, but I accidentally made this mistake before when working with a Python bot)
2. Did you make sure to add '!' as a Chat Command Identifier via the AddChatCommandIdentifier method on your TwitchClient instance?

**Comment by RamonRobben** [comment]
Yea I forgot to add the Identifier. thanks @MagiusRerecros

**Comment by swiftyspiffy** [comment]
You can also add the identifier in the constructor of the TwitchClient object :)

I could do a check that if the programmer is listening to onChatCommandReceived and hasn't set an identifier it throws an exception. Thoughts?

I've done this kind of enforcing elsewhere.

**Comment by RamonRobben** [comment]
It would be nice if the default is ! since its almost always the default for any bot out there.
If people are looking for a custom identifier they will probably look in documentation and find the custom identifier thing.

**Comment by MagiusRerecros** [comment]
I could see either approach being useful, but I think I'd personally favor @RamonRobben's suggestion, since as he said, it's already a pretty widespread convention.

**Comment by swiftyspiffy** [comment]
I can add that now, sure. With the enforcing, there'd be a boolean you could set to override the enforcement.

For example, if the programmer is listening to `OnBeingHosted` but the library detects the programmer isn't connecting as the broadcaster account (it's only possible for `OnBeingHosted` to be fired when connected as the broadcaster), it will thrown an exception. There's a major use case exception here where the programmer wishes to connect to the broadcaster's account in addition to other accounts. If this is the case, the programmer can set `OverrideBeingHostedCheck = true`, which kills the check.
