### ISSUE TITLE
IrcConnection

### ISSUE THREAD

**Issue by prom3theu5** [swiftyspiffy/TwitchLib#116]
Mentioned to you that I may have a stab at porting Meebey's IrcConnection into .NetStandard1.6.
This so far. I ditched the DCC functionality, as we don't need it.

https://github.com/prom3theu5/TwitchIRC

I still need to redo thread termination in IrcConnection by adding in Cancellation Tokens for each thread started.
Currently, it should run under .net core on Windows, Linux and OSX.

There is a test console app, shows it's a drop in replacement - or at least will be once the threading is sorted :)

Edit:
Alternatively - could move the entire Chat system over to a websocket implementation.

**Comment by swiftyspiffy** [comment]
Haven't had a lot of time, but saw your pull request and left a comment there.

**Comment by swiftyspiffy** [comment]
I believe this has been dealt with :)
