### ISSUE TITLE
WebRequests read as Encoding.ASCII instead of Encoding.UTF8

### ISSUE THREAD

**Issue by jxlarrea** [swiftyspiffy/TwitchLib#12]
MakeGetRequest in TwitchApi class returns response streams as Encoding.ASCII when it should be Encoding.UTF8

Pull request https://github.com/swiftyspiffy/TwitchLib/pull/13

**Comment by swiftyspiffy** [comment]
Merged (see pull request for details). Thanks :)

**Comment by swiftyspiffy** [comment]
NuGet version 1.0.7 should be available with this issue fixed.

**Comment by jxlarrea** [comment]
Downloaded NuGet package 1.0.7. Unicode characters are still shows as "????", specifically in the channel status.

**Comment by swiftyspiffy** [comment]
We (I and Igor from #10 ) had an issue with this earlier with chat messages and Russian cyrillic characters.  The solution we found was essentially encoding with UTF8, then decoding with Encoding.Default .

Would you be able to build the library using a similar solution and see if that solves your problem? If it does, I can apply it and send it out in the next version.  Here's the solution for chat currently implemented, modification should be pretty straight forward.

```
string decodedMessage = Encoding.UTF8.GetString(Encoding.Default.GetBytes(e.Line));
```

**Comment by swiftyspiffy** [comment]
You can also comment on your use case here and I can test it and try to recreate it.

**Comment by swiftyspiffy** [comment]
Just updated NuGet packag eto 1.0.8, which includes resub stability fixes and Encoding.Default, which should solve your problem.  Give it a go with your use case and let me know if it fixes it. :)

**Comment by swiftyspiffy** [comment]
As far as I know, this has been fixed.
