### ISSUE TITLE
Get live stream in a C# Form

### ISSUE THREAD

**Issue by jscoys** [swiftyspiffy/TwitchLib#120]
Hi,

I wonder if the current API could help to retrieve the complete link to be able to incorporate it in a C# Form, or at least to open it in a browser?

Thx for you help!

**Comment by MagiusRerecros** [comment]
Well, if youre joining a channel using the TwitchClient, you already know
the name of the channel and can build the url to open in a browser (
http://www.twitch.tv/channelname).

I'm not entirely positive on how you could embed the stream directly into a
form, although I'm sure it's possible somehow.

**Comment by jscoys** [comment]
Ok thx but little question : If I connect my account to one chat channel, is my connection considered as a "viewer" or only as a "chatter"?

**Comment by swiftyspiffy** [comment]
Assuming you're speaking of the TwitchClient, this is is an interesting question. I am pretty sure the connected channel (via IRC) does not count as a viewer, only a chatter.

**Comment by jscoys** [comment]
Ok thx a lot!
