### ISSUE TITLE
Videos.GetChannelVideos is only returning highlights.

### ISSUE THREAD

**Issue by Examed** [swiftyspiffy/TwitchLib#121]
Videos.GetChannelVideos is only returning highlights even though broadcasts=true should return more than highlights.

I'm trying to get a list of PastBroadcasts of the channel.

![twitch02-02-_2017_06-34-08](https://cloud.githubusercontent.com/assets/21694673/22538325/d5332616-e911-11e6-9bea-e3e81053e103.png)

**Comment by swiftyspiffy** [comment]
Will look into this now.

**Comment by swiftyspiffy** [comment]
That commit ^ might fix it. I got full recordings when passing `true` as `broadcastsOnly`. Give it a go and let me know what you think.

**Comment by Examed** [comment]
I will try it later :) I'm sure it will work 👍

**Comment by swiftyspiffy** [comment]
I'm going to go ahead and close this, feel free to reopen if the issue is not resolved.
