### ISSUE TITLE
oAuth key / Scope for Follow/Unfollow

### ISSUE THREAD

**Issue by jscoys** [swiftyspiffy/TwitchLib#122]
Hi i'm sorry for the question if it looks easy, but I can't figure out how to obtain the oAuth from my Twitch account with a scope of "Follow/Unfollow" people.

Is there an app online that could give me this information? Please help because I really need it.

**Comment by swiftyspiffy** [comment]
I'll create a site that allows for custom token generation. Will take a few hours though.

**Comment by swiftyspiffy** [comment]
Almost done.

**Comment by jscoys** [comment]
Ok thx its really appreciated!!! You rock!

**Comment by swiftyspiffy** [comment]
Done! Server is a bit slow, but you should be able to generate the token you want.

https://twitchtokengenerator.com/

Cheers.

**Comment by jscoys** [comment]
Tanks a lot! It's just wonderful what a great tool! You have to share it all over the web!

**Comment by swiftyspiffy** [comment]
Thanks for the kind words man! Feel free to share it :) Shall I close this?

**Comment by jscoys** [comment]
Yes you can, I saved the URL ;-)

**Comment by swiftyspiffy** [comment]
Also made a repo for it here :) https://github.com/swiftyspiffy/twitch-token-generator
