### ISSUE TITLE
username color

### ISSUE THREAD

**Issue by Toktha** [swiftyspiffy/TwitchLib#123]
I am sure this has been asked before but i am having trouble figuring it out.  I am new to coding and just playing around trying to figure things out but i got everything connected got the user name and message.  But i wanna get the username color that is applied from twitch and apply it to the chat box to help sort out whose messages are who instead of seeing all one color.  I know i could set it to random a color per user but  was not sure if i could pull the one they had set through twitch itself.  

Any examples or leads on this i would extremely appreciate!

**Comment by swiftyspiffy** [comment]
I think the ChatMessage object actually has a System.Drawing.Color object associated with it.

~~So to set the background color of the textbox, it'd be something like~~
Actually there's an example of it being done in the Example project:
https://github.com/swiftyspiffy/TwitchLib/blob/master/TwitchLibExample/TwitchLibExample/Form1.cs#L272

**Comment by Toktha** [comment]
I actually just figured this out... I got it to connect to each chat line and update.  

            chat.SelectionColor = e.ChatMessage.Color;
            chat.AppendText(e.ChatMessage.Message);
            chat.AppendText(Environment.NewLine);

not sure if this is proper code but it works to what i am looking for. 

Thanks for the help @swiftyspiffy

**Comment by swiftyspiffy** [comment]
Looks fine to me! I haven't worked a lot with the SelectionColor property, but it seems correct!

No problem. Shall I close this?

**Comment by Toktha** [comment]
I am noticing some colors are not showing up but i am gonna find a workaround..

**Comment by swiftyspiffy** [comment]
Yup, because some users don't have an assigned color for one reason or another, the `e.ChatMessage.Color` property can be null, representing a lack of color specified.

What I would do is something like this:
```
if(e.ChatMessage.Color != null) {
    // Assign the color that Twitch says is their chat color
    chat.SelectionColor = e.ChatMessage.Color;
} else  {
    // Assign a random color since Twitch didn't specify a color.
    Random ran = new Random();
    chat.SelectionColor = Color.FromArgb(ran.Next(256), ran.Next(256), ran.Next(256));
}
chat.AppendText($"{e.ChatMessage.Message}\n");
```

**Comment by Toktha** [comment]
I actually just did something similar to this. But since i don't know code i am just doing little statements to find out what does what lol.  I am trying to figure out now how to strip it out of the whole code and just do the names and not the message.  

Other bug i see i have is if i highlight a message the next message i receive while highlighting another message will update all messages to that color. -_-  

This is fun though learning as i play around with what does what.

**Comment by swiftyspiffy** [comment]
Gotcha, ya I don't know a ton about the (I assume you're using) RichTextBox, you may actually need to create your own UI component to accomplish what you're trying to do, maybe not.

Anyways, good luck and of course have fun! (I'll close this issue, but feel free to keep commenting on it)

**Comment by Toktha** [comment]
So been playing around with the code a bit and i put it in run by line mode cause it didn't feel like it was working and for some reason even if the color is not null it still only ran the first if and not else..

**Comment by swiftyspiffy** [comment]
I'm not quite sure I understand what you mean by "run by line mode".

**Comment by Toktha** [comment]
oh they are called "breakpoints" lol my bad -_-
