### ISSUE TITLE
Weird letters in Twitch Message

### ISSUE THREAD

**Issue by Syzuna** [swiftyspiffy/TwitchLib#125]
Hey Ho!

Since I upgraded your Twitch Lib to 1.3.9 this morning my Twitch Messages that contain letters like ä,ö.ü dont get encoded right although there never was a problem before.
Could that be a problem with the new way you hanlde IRC Connections and Messages?

Regards Syzuna

**Comment by swiftyspiffy** [comment]
Hi, yes there is a very good chance the move we made last night caused this. We are no longer using SmartIrc4Net to handle IRC, and instead using a built in websockets class.

I will look into this issue in a few hours and get back to you. I suspect it will be a fairly easy fix.

**Comment by Syzuna** [comment]
Thanks for your fast answer :) looking forward to hear from you

**Comment by swiftyspiffy** [comment]
Hey, so I have a solution, but I'm afraid it could possibility affect other aspects. I'll go ahead and push it now and we'll go from there.

Are you able to clone the repo and build the library and give it a go?

**Comment by Syzuna** [comment]
Will give it a go in a 1-2 hours and will give you feedback

**Comment by Syzuna** [comment]
Ok tested it already.. earlier than expected but I still get that encoding problem with ä ö ü e.g.

![github](https://cloud.githubusercontent.com/assets/22714301/22645582/03ba4ac4-ec68-11e6-9aa6-928a1dd2fd0c.PNG)

I builded the libary from scratch, unistalled the nuget version and linked the github one so I think the Project should use the right version

**Comment by swiftyspiffy** [comment]
So I connected a console app to a channel and pasted in those characters above, and this is what I get:

![http://swfty.xyz/?id=1306sc595](http://swfty.xyz/?id=1306sc595)

It appears to render in the console app. Are you using a UI app?

**Comment by Syzuna** [comment]
Yeah Im making a Bot for a friend with a UI. It reads the messages from a .txt file and he just has to check it and press a button to send it his social media links e.g. . (He didnt want a automatic repeat)

**Comment by Syzuna** [comment]
I just wanted to verify for myself that my program passes the right message and dont maleform it itself

![github_codesnip](https://cloud.githubusercontent.com/assets/22714301/22649251/72e34fa6-ec7a-11e6-9a3f-2b6137e481cd.PNG)

It defnitely passes the right message but it appears wrong in the Twitch Chat

**Comment by swiftyspiffy** [comment]
So using the latest code in the repo, when in Twitch chat, and I send `ä ö ü` in twitch chat, looking at the example application, it seems to work:
![http://swfty.xyz/?id=6149iW600](http://swfty.xyz/?id=6149iW600)

**Comment by swiftyspiffy** [comment]
Found the problem, I think. We've been encoding messages twice, which destroys Cyrillic characters.
Commit: 8d1d45fd73d3abfff26be5303b6d813e06665b22

Go ahead and pull, rebuild, and give it a go.

**Comment by Syzuna** [comment]
Yeah Im talking about Sending twitch messages. Will trotzdem the new build in a sec

**Comment by Syzuna** [comment]
Ok looks good for me now. Encoding seems to work properly once again

**Comment by swiftyspiffy** [comment]
Awesome, glad I could help :)
