### ISSUE TITLE
Proper event methods?

### ISSUE THREAD

**Issue by vaindil** [swiftyspiffy/TwitchLib#127]
Hello! I'm writing a new bot and have a quick question. The [docs](http://swiftyspiffy.com/TwitchLib/client.html#Connect) show that this format can be used for adding methods to an event:

```csharp
client.OnConnected += clientConnected;
```

That doesn't seem to work any way I can figure out. The example code shows this:

```csharp
newClient.OnConnected += new EventHandler<OnConnectedArgs>(onConnected);
```

That does work. Is there a way I'm missing that will allow me to use the first shortened syntax instead of the longer one?

**Comment by vaindil** [comment]
Welp, I'm dumb. As long as I have the proper parameters specified for the `clientConnected` function then the rest of the call can be omitted. Sorry, thanks!

**Comment by swiftyspiffy** [comment]
Glad you figured it out :)
