### ISSUE TITLE
1.3.9 WebServer already started.

### ISSUE THREAD

**Issue by thetrust3343** [swiftyspiffy/TwitchLib#131]
Since the 1.3.9 Version i sometimes get the error that the webserver already started. Don't know what the Problem is since the new version

**Comment by Syzuna** [comment]
Are you using the Disconnect function of the client at any point?

**Comment by swiftyspiffy** [comment]
For the time being, I would recommend reverting back to 1.3.7 . There were some issues with the built in websocket class we were using. Moving over to websocket-sharp in 1.4.0 and it should resolve a lot of these issues.

Sorry :(

**Comment by swiftyspiffy** [comment]
Alright guys, 1.4.1 NuGet package was just pushed. Should rectify parsing issues. Still not totally sure about the WebServer already started. Will look into that.

**Comment by thetrust3343** [comment]
Yeah I already went back to 1.3.7 but  I will try the newest version. Thanks for the information! 
Keep up the good work!

**Comment by swiftyspiffy** [comment]
I'll go ahead and close this, feel free to reopen if you think the issue hasn't been resolved :)
