### ISSUE TITLE
OnExistingUsersDetectedArgs returns false Users list

### ISSUE THREAD

**Issue by it0** [swiftyspiffy/TwitchLib#132]
Hey,

dont know if this is a bug, but when the event "OnExistingUsersDetected" triggers,
i get the following list from e.Users:
(Replaced my username with "username")

Users - Count = 8
0 = "username\r\n:username.tmi.twitch.tv"
1 = "366"
2 = "username"
3 = "#username"
4 = ":End"
5 = "of"
6 = "/NAMES"
7 = "list"

Version: 1.4.0

**Comment by swiftyspiffy** [comment]
Assuming you are using the latest code in the GitHub repo, this should be fixed. Let me give it a go real quick.

**Comment by swiftyspiffy** [comment]
Yup, looks like it is broke. A lot of broken things since we moved over to websockets :( Will fix now.

**Comment by swiftyspiffy** [comment]
Should be fixed with this commit, if you want to give it a go:
7803ab2d9322fc92321da64e4a60ff8ac94d5180

**Comment by it0** [comment]
Seems to work, good job!
Thanks!
