### ISSUE TITLE
Most of the events are not firing anymore

### ISSUE THREAD

**Issue by Cr1TiKa7** [swiftyspiffy/TwitchLib#133]
Some events are not firing anymore since the 1.3.9 update:
OnMessageReceived
OnMessageSent
OnUserJoined
OnUserLeft
OnWhisperReceived

Greetz

**Comment by Syzuna** [comment]
OnMessageReceived fires fine for me. Dont using the others atm

**Comment by swiftyspiffy** [comment]
Hey, are you using the latest GitHub repo code? Most of those seem to be working at the moment. There are a few messed up though (ExistingUsers is one I know for sure is broke). We moved over to websockets from the IRC, and this has broken a few things.

Sorry about the issues :( Feel free to revert to back to 1.3.7 for the time being.

**Comment by swiftyspiffy** [comment]
Testing each of those events with current repo code using example app:
OnMessageReceived: `working`
OnMessageSent: `working`
OnUserJoined: `not working` - works for a single join message, but websocket implementation can receive several join messages in a single transmission, which doesn't work. Will work on this now. 
OnUserJoined: `now working` - See commit: 3b1cb2e40f526463365b42e5108ec7e5d4eeae53
OnUserLeft: `working`
OnWhisperReceived: `working`

The commit referenced above essentially breaks the websocket transmission into individual messages similar to what you'd see in IRC, and then uses the existing parsing infrastructure. This should pretty much resolve all parsing issues.

**Comment by swiftyspiffy** [comment]
And with that, NuGet package 1.4.1 was just pushed. Try updating and giving that a go. I think it should fix your issues. Sorry again.

**Comment by swiftyspiffy** [comment]
I think this has been resolved, I'm going to go ahead and close it. Feel free to reopen it though if you think otherwise.
