### ISSUE TITLE
Changes to the OnMessageReceivedArgs EventArgs

### ISSUE THREAD

**Issue by Cr1TiKa7** [swiftyspiffy/TwitchLib#136]
Hi,
could you please add an IsFollower property to the EventArgs?
And maybe rename the Subscriber property to IsSubscriber? (It's better to read).

Would be cool if you could change that.
Keep on the good work!

**Comment by toffaste1337** [comment]
Followers arent sent with the message I believe. That means you need to send a query to the twitch api every time, and there are limits.
You could either do:
`TwitchApi.Follows.UserFollowsChannel(e.ChatMessage.Username, e.ChatMessage.Channel);`
Or make a function that loads the followers in a channel to a list ever so often so you dont have to make api calls for every message.

**Comment by swiftyspiffy** [comment]
Hi. Yes, toffaste is correct, follower relationship is not provided with message properties. If this were to be implemented, either we'd need to fetch follower data on the fly when we receive messages and cache that data (not efficient at all), or fetch follower data up front and maintain this collection of data as new users join chat (also not very efficient).

I don't think we want to implement this at the library level as most users of the library wouldn't want the trade off of efficiency for follower relationship. You, of course, are more than welcome to either modify the library for your own needs, or use the ChatMessage username property to fetch the follow relationship of the user.

**Comment by swiftyspiffy** [comment]
I'm going to go ahead and close this. The route for fetching this kind of data has been outlined in the two comments above. Feel free to reopen this if need be.
