### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by helix757** [swiftyspiffy/TwitchLib#139]
No matter what, when I try to connect I get

2/28/2017 4:06:25 PM|Fatal|WebSocket.<startReceiving>b__175_2:0|System.ObjectDisposedException: Cannot access a disposed object.
                           Object name: 'System.Net.Sockets.NetworkStream'.
                              at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
                              at WebSocketSharp.Ext.<>c__DisplayClass55_0.<ReadBytesAsync>b__0(IAsyncResult ar)

I am even using the default web socket example from the git

Thanks in advanced!

**Comment by swiftyspiffy** [comment]
Hey, it looks like you resolved whatever the problem was, but would you mind sharing what you did? Just for future reference.

**Comment by helix757** [comment]
Yeah, that error was just being thrown because of invalid credentials.
