### ISSUE TITLE
User ID types are inconsistent

### ISSUE THREAD

**Issue by vaindil** [swiftyspiffy/TwitchLib#141]
`ChatMessage.UserId` is a string, but `TwitchLib.API.Models.v5.User.Id` is long. Is there a reason for this? A string is returned by the v5 API, so it's being cast to long by the library.

**Comment by swiftyspiffy** [comment]
It needs to be a string. I'll fix it when I get home. I meant to do this earlier but forgot.

**Comment by swiftyspiffy** [comment]
Didn't actually mean to close this until I could get home and verify everything, but it looks good.
