### ISSUE TITLE
How can I send a message to a chat with a higher priority?

### ISSUE THREAD

**Issue by DarkoreXOR** [swiftyspiffy/TwitchLib#143]
It happens that messages are not sent if they try to send often. I need a way of guaranteed, but not urgent, delivery of important messages to the chat. Is there any way to do this?

**Comment by elu00** [comment]
I'm pretty sure there's no native function to do this within the library (could be wrong), so I'm fairly sure your only options are

- Be modded in whatever chat you're in to increase the rate limit
or 
- Manually ensure you don't exceed your rate limit inside your program.

[https://discuss.dev.twitch.tv/t/twitch-chat-from-a-twitch-dev/1108/3] From this thread, the maximum amount of messages you can send as a regular user is 20/30sec, but this increases to 100/30sec when you're modded.

**Comment by swiftyspiffy** [comment]
elu is correct. At one point (and maybe still give it a try) you could contact Twitch support with the name of your bot and ask to be whitelisted and they will increase the limits for your bot (though they won't tell you to what).

**Comment by DarkoreXOR** [comment]
Can MessageThrottler cancel sending of the second message, if in the code I call immediately 2 times SendMessage (...)?

**Comment by swiftyspiffy** [comment]
The message throttler _could_ do this, but it would need a bit of a rewrite I think. You're welcome to write your own message throttler implemention too, of course. I can put it on my list of things to do, but I have a lot of other things that need to get done first.

**Comment by swiftyspiffy** [comment]
I'm going to go ahead and close this. There isn't a message priority system on Twitch's side, nor in this library. I would recommend either utilizing the message throttler/building out your own throttler, or sending less messages.
