### ISSUE TITLE
Dependency injection

### ISSUE THREAD

**Issue by vaindil** [swiftyspiffy/TwitchLib#145]
Would it be helpful to add DI functionality? I have all of my commands crammed into Program.cs right now, it would be great to break them into separate classes but then I have to instantiate some objects multiple times.

**Comment by Syzuna** [comment]
do you talk about chat commands?

If yes I just wrote them into a database file and work with that

**Comment by vaindil** [comment]
Yes, but I have commands that do more than fire an autoreply, they rely on other services. One simple example is a `Random` class. That could be instantiated individually in each class I use it in, but that's wasteful. It's not necessary to have 3 or 4 `Random` objects floating around.

**Comment by Syzuna** [comment]
ah ok ye thats right then a simple database solution wont work

**Comment by swiftyspiffy** [comment]
This is interesting. The way my bot is setup is that have a directory that houses a .cs file for each command the bot does, and that .cs file contains all logic applicable to that command. then I have a simple commands.cs file that handles OnChatCommandReceived, and fires a "handleCommand" that exists in each of the .cs command files, for whichever command .cs file is applicable.

**Comment by vaindil** [comment]
I'm starting to move to that, but I was hitting the problem of having multiple dependencies across the project. It's not a huge deal, the extra overhead is virtually zero for my bot specifically, but in the future adding DI would be very helpful IMO.

**Comment by swiftyspiffy** [comment]
I understand the concept of DI, but not super sure how it'd be implemented. I'll do some research and see what is possible.

**Comment by Syzuna** [comment]
Did you maybe thought about an Interface and Reflection to achieve what you want?

**Comment by horato** [comment]
What does internal implementation of this library has to do with DI containers of your bots? I am currently refactoring my old bot and I am transfering over to this library (looks cool btw ;)). If you are interested check my RoxorBot repo in a few days, it should have some command handler with DI by then.

**Comment by prom3theu5** [comment]
It doesn't.
The library is fairly DI ready (apart from the static API class).
Basic rule is that You set up your DI Container inside the Composition Root and only start-up projects should contain a Composition Root. Certainly not in a class library.

**Comment by vaindil** [comment]
Yeah, this doesn't belong here. The Discord.Net library had built-in DI, but they switched to using the built-in provider. Discord.Net was confusing me, this isn't relevant.

**Comment by swiftyspiffy** [comment]
Sorry about not discussing this very actively. prom3theu5 sums up what I had in mind more elegantly.
