### ISSUE TITLE
Disconnects after a while

### ISSUE THREAD

**Issue by vaindil** [swiftyspiffy/TwitchLib#148]
I can't figure out what's going on. I'm running the bot with 4.6.2, nothing fancy with it. I had it on an Azure WebJob, and after a while the bot just disconnected with no log message. Moved it to a dedicated VM with nothing else running on it, still getting the disconnect. I'm getting no log messages, no errors, nothing. I have no idea what to even check.

**Comment by swiftyspiffy** [comment]
Couple things to check.
- Your app is persisting and actually running.
- Listen to the OnConnectionError, as seen here: https://github.com/swiftyspiffy/TwitchLib/blob/master/TwitchLib/TwitchClient.cs#L527
- Make sure to initialize TwitchClient with the logging boolean set to true, as seen here: https://github.com/swiftyspiffy/TwitchLib/blob/master/TwitchLib/TwitchClient.cs#L247

Currently I have three applications using the library and running on AWS (through mono).

**Comment by Syzuna** [comment]
Did you reference the websocket-sharp.dll correctly?
Had that problem too and it was all down too a corrupted reference too the websocket-sharp.dll
Just give it a try maybe ;)

**Comment by Syzuna** [comment]
oh and swifty I tried to get around that win7 problem with the websockets but wasnt able to make it. I also build the lib with the latest version of the websocket-sharp lib and still get that platform not supported error from the websocket... its kinda annoying that I can only work at home on my desktop pc and not on my work laptop when i am not home :/

**Comment by vaindil** [comment]
I was listening to all of the events and sticking them in my DB, but I had only ever received the OnConnected event. I didn't know of the logging bool, I just enabled that. I'll watch what happens and report back.

**Comment by vaindil** [comment]
Bot stopped working, nothing valuable was logged. Last two lines are below.

```
[TwitchLib] Received: PING :tmi.twitch.tv
[TwitchLib] Writing: PONG
```

**Comment by vaindil** [comment]
(sorry for the double comment)

@Syzuna What specifically was your problem? I'm not seeing any issues. It's been a while since I've used 4.6.2 (I've been working exclusively with Core for the past year or so), so I'm not sure exactly what to check.

**Comment by Syzuna** [comment]
for me the websocket-sharp dll that was copied to the output directory (due to the reference to it in VS) was smaller than the original one. Looked like an issue from VS17 dunno. I just deleteted the file and the new copy was ok

**Comment by vaindil** [comment]
I have `websocket-sharp.dll`, 244KB. The same file is in my output directory. Path in the project is `packages\WebSocketSharp-NonPreRelease.1.0.0\lib\net35\websocket-sharp.dll`.

**Comment by Syzuna** [comment]
Well it was worth a shot to look at that. hmm then I dont rly know what causes your disconnects.. maybe try to log the traffic with a program like wireshark and watch if there is something suspicous in the websocket traffic

**Comment by vaindil** [comment]
Traced it with Wireshark, nothing of interest there either in the websocket connection. My bot sends a PONG and that's that, nothing happens after that. This isn't the first PONG, it just fails at this point for whatever reason. That last pong happened 35 mins 3 secs after the connection started.

**Comment by swiftyspiffy** [comment]
So the two environments you've tested with are Azure WebJobs and a dedicated VM. Are you able to run the bot beyond the 30 or so minutes locally on your own machine in Visual Studio debugger? For reference I run all three of my bots on AWS using mono and they have uptimes in the weeks. Running locally using VS debugger also runs fine.

**Comment by vaindil** [comment]
Ran it for a couple hours in debug on my PC, no disconnects. I tried using Mono on my Ubuntu server, but I get an NRE that I don't get with Xamarin Studio on my PC. I'll open a separate issue for that though. Not sure what I'll do now.

**Comment by swiftyspiffy** [comment]
For what it's worth, I plan on deploying an ASP app to Azure here shortly (today or tomorrow). I can have feedback for you on how that goes.

**Comment by vaindil** [comment]
Alright, I figured out why it's failing on Mono, it was an issue with the SSL cert. I thought I had installed `mono-complete`, apparently not. Got those packages sorted out (see #154). Bot actually runs on the server now, so I'll start it up and leave it overnight to see if it works.

**Comment by vaindil** [comment]
Bot is working properly with Mono now. Might be a problem with the websocket library on Server 2016; I assume that's what Azure App Service runs on. Not sure though. Can probably close this issue, I'll leave it up to you.

**Comment by swiftyspiffy** [comment]
Damn, I should have mentioned the cert issues I've had with mono. It's good that progress seems be being made though.

**Comment by swiftyspiffy** [comment]
I guess I'll go ahead and close this one as the other issue seems to overlap. As a side not, I'm not sure there's a fix to the other issue. I pushed a commit that should throw the proper exception if casting fails.
