### ISSUE TITLE
Pubsub causes platform not supported execption on win7

### ISSUE THREAD

**Issue by Syzuna** [swiftyspiffy/TwitchLib#149]
Hey swifty,

I think I finally found that error causing the trouble with the PlatformNotSupported Exepction on Win7.
It looks like you forgot to rewrite the code from the pubsub to the websocket-sharp way of handling websockets.

![pubsub_error](https://cloud.githubusercontent.com/assets/22714301/23947254/396b23cc-097e-11e7-9e00-7271ff7e4f73.PNG)

(sorry for the german error screenshot but I think the essential parts are still understable)

Hope that helps you :)

**Comment by Syzuna** [comment]
#150

**Comment by swiftyspiffy** [comment]
merged :) thanks again
