### ISSUE TITLE
ChatMessage has no awareness of /me actions

### ISSUE THREAD

**Issue by GlitchHound** [swiftyspiffy/TwitchLib#15]
Currently a user of the Library will have to manually add a logic check and do some string manipulations to properly handle any /me action that a chatter enters.

I've put in just a couple of lines to address this in a pull request which I'll link to this issue.

Based on observation, /me actions are received identically to normal messages (via PRIVMSG) but are denoted by Twitch by wrapping the text in 0x01 bytes, and prepending the message text with "ACTION ".

Associated PR: https://github.com/swiftyspiffy/TwitchLib/pull/16

**Comment by GlitchHound** [comment]
As a mostly unrelated aside, is it intentional that there's no TwitchLib/TwitchLib.csproj file in the repo? Would be nice to be sure I'm not doing anything wrong when I try to work on the solution in VS

**Comment by swiftyspiffy** [comment]
I did it at the very start of the project when i was testing some things with it locally, and have been meaning to put it back ever since.  Thanks for reminding me, will do it now.

**Comment by GlitchHound** [comment]
Confirmed working, and thanks for getting the .csproj in.
