### ISSUE TITLE
Auth Calls doesnt work in the example

### ISSUE THREAD

**Issue by LuxhDEV** [swiftyspiffy/TwitchLib#153]
Hello, I have tried to use the Auth calls from the example. I've generated an AccessToken with the necessary scope. However, I still get the error message: "do you have the right scope for your access token?"

**Comment by swiftyspiffy** [comment]
What scopes are you using and what calls are you attempting to make? I'll give it a try now.

**Comment by LuxhDEV** [comment]
I used the scope channel_editor for changing the Channel Status and the Game.

**Comment by swiftyspiffy** [comment]
Sorry I've been quite busy and haven't been able to look at this. If you don't mind me asking, what was the issue?

**Comment by LuxhDEV** [comment]
There's no error in the API. I had mistakenly changed something at the imports, which is why it hadn't worked anymore.
Sorry for the inconvenience c:
