### ISSUE TITLE
WebSocketSharp.WebSocketException

### ISSUE THREAD

**Issue by ghost** [swiftyspiffy/TwitchLib#156]
Hey,

maybe i do something wrong, but i get the following exception:

![image](https://cloud.githubusercontent.com/assets/4417107/24458283/c600d1ea-1498-11e7-9142-b9c937e89ab2.png)

My Code:

    public class BBB {

        public static void test() {
            TwitchLib.TwitchClient Client;

            var username = "username";
            var oauthKey = "oauthKey";
            var channel = "channelName";

            // Set TwitchAPI Config
            TwitchApi.SetClientId("clientID");
            TwitchApi.SetAccessToken(oauthKey);

            // Credentials
            var credentials = new ConnectionCredentials(username, oauthKey);

            Client = new TwitchClient(credentials, channel, '!', '@', true, true);

            Client.Connect();

            Client.OnMessageReceived += Client_OnMessageReceived;

        }

        private static void Client_OnMessageReceived(object sender, TwitchLib.Events.Client.OnMessageReceivedArgs e) => Console.WriteLine(e.ChatMessage.Message);
    }

Do you know why?

**Comment by swiftyspiffy** [comment]
What is the full web exception? Are you able to set a breakpoint on where it's thrown to get more details?

Also, as a side note you should subscribed to the OnMessage event before connecting to the channel.

**Comment by toffaste1337** [comment]
I was just about to post this myself. My bot ran ok for around 30 hours, then the error below came up as it crashed, later when I tried to start it again, I got the same error as @it0. Waited around 2-3 minutes, tried again then it worked again.

![image](https://cloud.githubusercontent.com/assets/6287600/24473737/8ffe5694-14ca-11e7-91fb-05f5ca9f5bdf.png)

**Comment by swiftyspiffy** [comment]
The issue @it0 got seems to be related to the TwitchApi class, while the image you ( @toffaste1337 ) posted seems to be related to the TwitchClient, is that correct?

**Comment by toffaste1337** [comment]
TBH, the error I posted might be another thing. Do you know if `Quobject.SocketIoClientDotNet.Client;` would interfere with your code?

**Comment by swiftyspiffy** [comment]
So I'm actively researching @it0 's issue, so hopefully I can come up with something regarding that. Regarding your issue @toffaste1337 I actually have seen this issue before, but figured it was something wrong with my bot logic, and not the library itself. Do you know exactly where that error occurred, because as far as I can tell, the stacktrace doesn't pinpoint it.

**Comment by swiftyspiffy** [comment]
It looks like the issue has already made the rounds, and that the simplest route might be to simply disable extensions in websocketsharp. We can also go the route that this fellow found: 
https://github.com/sta/websocket-sharp/issues/202#issuecomment-220267454

**Comment by toffaste1337** [comment]
@swiftyspiffy I have no idea where the error occured, as this ran on linux with mono, what you see in that image is what I saw. I can try to run it locally for a while then come back with results if it crashes.

**Comment by swiftyspiffy** [comment]
@it0 it looks like that issue can happen as a result of a PING being sent/received right after connecting. Perhaps give it another go and see if it works. Additionally, I just uploaded a release candidate of websocketsharp that includes OQO's possible fix. If it seems to work, then I'll just make it non-pre-release and update the library to use the new websocketsharp.

@toffaste1337 That's where I've noticed the error as well (on Mono). I don't want to say the error is specific to mono, but it could be. I've never encountered it on Windows.

**Comment by toffaste1337** [comment]
@swiftyspiffy, right, I have noticed that my bot pretty much run seamlessly on windows, but then I get weird errors on linux...

I have updated your library now though, as it was a few versions behind. Might be more stable. :)

**Comment by Moerty** [comment]
I am it0. I have created a new account. 
The mistake seems to appear only on my working computer. At home and on my virtual machine my test program works. 
It seems to be a specific problem and I will try to find the error.
From my side, the mistake can be closed.

**Comment by swiftyspiffy** [comment]
Hey Moerty, no problem.

If you'd like to try something that may fix it, what you should do is go to your NuGet package manager (assuming you're using NuGet), go to Updates tab, check Include Prereleases, and then update WebSocketSharp-NonPreRelease with the latest rc1 version.  This version has a slight modification that might fix your issue.

**Comment by Moerty** [comment]
Hey swiftyspiffy,

i have update the dll and i'm a bit confused.

I get a "System.IO.FileLoadException"-Exception on line:
`Client = new TwitchClient(credentials, channel, '!', '@', true, true);`

Errortext:
System.IO.FileLoadException: "Could not load file or assembly "websocket-sharp, Version=1.0.2.32519, Culture=neutral, PublicKeyToken=5660b08a1845a91e" or one of its dependencies. 
The located assembly's manifest definition does not match the assembly reference.


And that's right. The "normal" dll has the Version "1.0.2.32519". 
The PreRelase dll has the Version "1.0.2.26229".


Can you give me a hint, how i get this working?

**Comment by swiftyspiffy** [comment]
Ohhh, I didn't think about that. Nevermind, I don't think what I suggested will work. What you need to do I think is rebuild the project using the suggested websocketsharp library, and then reference the built dll, instead of using NuGet. But, that's a bit of a pain in the ass though. 

Your best bet I think would be to  rebuild the project. Alternatively, tomorrow I can upload an rc1 of TwitchLib so that you can just pull that from NuGet and not get the issue you're having.

**Comment by swiftyspiffy** [comment]
Ohhh, I didn't think about that. Nevermind, I don't think what I suggested will work. What you need to do I think is rebuild the project using the suggested websocketsharp library, and then reference the built dll, instead of using NuGet. But, that's a bit of a pain in the ass though. 

Your best bet I think would be to  rebuild the project. Alternatively, tomorrow I can upload an rc1 of TwitchLib so that you can just pull that from NuGet and not get the issue you're having.

**Comment by Moerty** [comment]
I build the lib with the new dll and yeah, no Exception.

But:
I cant receive any messages from the chat.

My Code:


    class Program
    {
        static void Main(string[] args)
        {
            TwitchClient Client;
            var username = "";
            var oauthKey = "";
            var channel = "";

            // Set TwitchAPI Config
            TwitchApi.SetClientId("");
            TwitchApi.SetAccessToken(oauthKey);

            // Credentials
            var credentials = new ConnectionCredentials(username, oauthKey);

            Client = new TwitchClient(credentials, channel, '!', '@', true, true);

            Client.OnMessageReceived += Client_OnMessageReceived;

            Client.Connect();

            Console.ReadKey();
        }

        private static void Client_OnMessageReceived(object sender, TwitchLib.Events.Client.OnMessageReceivedArgs e) {
            Console.WriteLine(e.ChatMessage.Message);
        }
    }


![image](https://cloud.githubusercontent.com/assets/26777372/24502241/407bd4e2-154d-11e7-9324-0c3093fb88e1.png)

**Comment by swiftyspiffy** [comment]
Gotcha, glad we got it figured out. Will go ahead and hide the faulty websocketsharp version.

I'll go ahead and close this.
