### ISSUE TITLE
TwitchClient.Logging

### ISSUE THREAD

**Issue by zerocarbthirty** [swiftyspiffy/TwitchLib#157]
Any idea where twitchclient.logging ended up going?

This used to work:

            client.SetLoggingStatus(true);

**Comment by swiftyspiffy** [comment]
Looking into this.

**Comment by swiftyspiffy** [comment]
Right, since a lot of the settings set in the constructor of TwitchClient are now properties that can be modified at any time, I removed the setter methods for them (since they were now duplicates). To set the logging status at anytime, it's just: 
`client.Logging = true;`

**Comment by Syzuna** [comment]
It is only logging to console right? 
So in a GUI Application it wont help me right?

**Comment by swiftyspiffy** [comment]
Correct. If you have an idea for logging for GUI applications, I'm all ears.

**Comment by Syzuna** [comment]
Well.. there would be the possibility to log to the Debug Window.. at least for Visual Studio but ye dunno how to decide if it shall log to the Console or the Debug window depending on the type of the running application.. or you could log to a file..

**Comment by toffaste1337** [comment]
@Syzuna You can just change the application to a console application. You will get the GUI and the console :)

**Comment by swiftyspiffy** [comment]
I don't see a reason why logging can't be sent to output as well. Maybe when setting logging status, you can specify where to send it to or something. I'll look into it after I finish this API rewrite.

**Comment by toffaste1337** [comment]
@swiftyspiffy Can the logging be an event? This way you could do whatever you would like with the message.

**Comment by swiftyspiffy** [comment]
I can do that, sure.

**Comment by swiftyspiffy** [comment]
@toffaste1337 OnLog event should be available in 1.4.5 NuGet package. As for the original issue, it should be described pretty clearly above. I'll go ahead and close this.
