### ISSUE TITLE
UserType always equals "Viewer" in OnChatCommandReceivedArgs

### ISSUE THREAD

**Issue by zerocarbthirty** [swiftyspiffy/TwitchLib#159]
Hi, I've had this issue for awhile but haven't been able to resolve it.

I notice that in OnChatCommandReceivedArgs

Command.ChatMessage.UserType seems to always equals "Viewer" or "Broadcaster" even though the output from twitch looks like this:

[TwitchLib] Received: @badges=moderator/1;color=;display-name=testuser;emotes=;id=bcae9fc9-7c93-4641-9496-67e333b0d01b;mod=1;room-id=111927550;sent-ts=1491314238284;subscriber=0;tmi-sent-ts=1491314205113;turbo=0;user-id=115499748;user-type=mod :testuser!testuser@testuser.tmi.twitch.tv PRIVMSG #testroom :!supershout

it never seems to evaluate to moderator.

**Comment by elu00** [comment]
Hiya,

Do you know if the same issue is true of OnChatMessageRecievedArgs?
Both use the same constructor for the instance of ChatMessage, so if it's an issue with the parsing in ChatMessage, then it should occur with both events.

**Comment by swiftyspiffy** [comment]
Looking into this now, I think I know what's up.

**Comment by swiftyspiffy** [comment]
Didn't mean to close this.

**Comment by swiftyspiffy** [comment]
I'm going to go ahead and close this, as it should be resolved :)
