### ISSUE TITLE
Unaccounted

### ISSUE THREAD

**Issue by toffaste1337** [swiftyspiffy/TwitchLib#163]
Got this error when restarting my bot today
` [TwitchLib][ChannelState] Unaccounted for: room-id=46215118 `
Might be fixed in a new release though.

**Comment by swiftyspiffy** [comment]
This means that in the ChannelState model, room-id property is not being parsed. I can fix this now.

**Comment by swiftyspiffy** [comment]
should be fixed, if you want to give it a go with the latest code.
