### ISSUE TITLE
TwitchApi.Streams.BroadcasterOnlineAsync(channelName);

### ISSUE THREAD

**Issue by zerocarbthirty** [swiftyspiffy/TwitchLib#167]
I am guessing that I am using this incorrectly but when I use this:

where channelName is the name of a twitch channel.

bool online = await TwitchApi.Streams.BroadcasterOnlineAsync(channelName);

it causes a System.ArgumentOutOfRangeException

**Comment by swiftyspiffy** [comment]
Will look into this now, it looks like you're using it correctly.
