### ISSUE TITLE
SendMessage doesn't trigger onMessageReceived?

### ISSUE THREAD

**Issue by lexyoussef** [swiftyspiffy/TwitchLib#173]
May be related to https://github.com/swiftyspiffy/TwitchLib/issues/108

I've added functionality to send messages, and I can see on twitch.tv that the messages are indeed being sent. However, I've noticed that the messages sent from my app do not trigger onMessageReceived, however if I write anything directly into chat on twitch.tv, onMessageReceived will be triggered.

Am I missing something, or is there an elegant solution to this so that I can trigger onMessageReceived when my app sends messages? Otherwise I think I'll have to manually create a ChatMessage object, and again, not sure of an elegant/appropriate way to do that.

Thanks in advance for you help!

**Comment by swiftyspiffy** [comment]
Ya, so when you send a message via IRC/websockets, the message is not sent back to the connection that sent it, so the library doesn't know that you sent it in that sense. However, there is an event `OnMessageSent`. Basically, this event fires at the same time the library sends a message, and it attempts to construct a ChatMessage based on the limited information the library sees. It's not perfect, but it has basic information.

**Comment by lexyoussef** [comment]
Ah perfect! Thanks, I'll work on that tomorrow.

As always, much appreciated and keep up the great work!

**Comment by swiftyspiffy** [comment]
Yup! Happy programming!
