### ISSUE TITLE
Compatibility with MONO

### ISSUE THREAD

**Issue by bruxo00** [swiftyspiffy/TwitchLib#174]
Hey. I'm trying to use your lib on my project that is a automatic twitch highlight submitter to youtube, but I need to run the program on my VPS, witch runs linux.

I'm using Mono to run my program. The only issue is that when I start the program, it requires me to authenticate on the browser, wich I can't do because I'm running only on a terminal. Is there any way for me to do the authentication without using a browser?

The "error" it gives:

> Error: Failed to launch browser with "https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&response_type=code&client_id=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" for authorization. See inner exception for details.

Thanks.

**Comment by Moerty** [comment]
Maybe i am wrong, but i think your problem is not related to TwitchLib.

**Comment by bruxo00** [comment]
Oh, fuck me. Sorry, wrong place...
