### ISSUE TITLE
Implementing async by using Task.Run is harmful and misleading.

### ISSUE THREAD

**Issue by johnduhart** [swiftyspiffy/TwitchLib#175]
I noticed that in your library you support async, however looking at your implementation it simply starts a new task that calls the synchronous implementation. When I call an Async version of a method, I expect that method will execute until it blocks at an I/O boundary, and then return execution to the calling method.

https://blog.stephencleary.com/2013/11/taskrun-etiquette-examples-dont-use.html

**Comment by swiftyspiffy** [comment]
I will look into this. The idea for await Task.Run() was introduced to me by a superior, and I didn't question it. It looks like it may not be the _correct_ solution, despite running technically asynchronously.

**Comment by swiftyspiffy** [comment]
Alright, so after reading it, this was the big take away:
```
The key here is that the solution does not belong in the service. It belongs in the UI layer itself. Let the UI layer solve its own problems and leave the service out of it.
```

This would imply that async calls don't belong in the library. Do you agree with that? 
The alternative being I/we create alternative internal methods that make the web calls asynchronous in nature, instead of simply invoking Task.Run() at the highest level.

Interesting in your input.

**Comment by johnduhart** [comment]
Having async versions of your methods is fine, the main issue currently is the implementation. Async versions of http client calls should be used instead of the current synchronous ones.

**Comment by swiftyspiffy** [comment]
@johnduhart if you want to give it a look now, I'm pretty sure it should be compliant with the link you shared.

TwitchAPI is 100% async which will go out in 1.4.7. For 1.4.8 I'd like to target HttpClient in an attempt to make the library netcore compliant.

**Comment by johnduhart** [comment]
Thanks, looks good.
