### ISSUE TITLE
Changes in the API-Rewrite

### ISSUE THREAD

**Issue by Syzuna** [swiftyspiffy/TwitchLib#176]
Hey :)

Do you have sth. like a compact list of all changes you did to names and namespaces in the rewrite?
So that I can calculate the amount of work I have to do to rewrite my bot to the new API stuff.

Regards

**Comment by swiftyspiffy** [comment]
Every API namespace path was changed. Currently trying to ensure that no endpoints were lost causing more work. It should just be a matter of mass-find-and-replace.

**Comment by Syzuna** [comment]
ok will wait with the next lib update then^^ thx for the information :)
Keep up your good work ;)

**Comment by swiftyspiffy** [comment]
Additionally, the library will only support async functions for TwitchAPI, so to that point it might require some work. You can kind of prepare for it by utilizing the Async versions currently supported :)
