### ISSUE TITLE
Can't catch StreamOfflineException from GetStream(string channel)

### ISSUE THREAD

**Issue by lexyoussef** [swiftyspiffy/TwitchLib#178]
I'm having an interesting issue here, where the following: 
```
            try
            {
                if (TwitchApi.Streams.BroadcasterOnline(username))
                {
                    return TwitchApi.Streams.GetStream(username).Viewers;
                }
                return 0;
            }
            catch (StreamOfflineException)
            {
                TwitchApi.SetClientId(AppSettings.TwitchAppID);

                return 0;
            }
```

is resulting in this:
```
[StreamOfflineException: Exception of type 'TwitchLib.Exceptions.API.StreamOfflineException' was thrown.]
   TwitchLib.Internal.<GetStream>d__19.MoveNext() +625

[AggregateException: One or more errors occurred.]
   System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) +4126993
   System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) +12252463
   System.Threading.Tasks.Task`1.get_Result() +33
   TwitchLib.Streams.GetStream(String channel) +139
   TwitchAPIManager.GetViewers(String username) +42
```

So, it's returning true for the online check (as the channel I'm testing with was online), but then once it tries to retrieve viewers it throws a StreamOfflineException error. Am I using it incorrectly?

Thanks in advance :)

**Comment by swiftyspiffy** [comment]
Hi. It looks like your code should theoretically work.

What you can try doing is simply doing:
```
TwitchApi.SetClientId(AppSettings.TwitchAppID);
 try
            {
                return TwitchApi.Streams.GetStream(username).Viewers;
            }
            catch (StreamOfflineException)
            {
                return 0;
            }
```

**Comment by lexyoussef** [comment]
That's actually what I had before, and it still wouldn't catch StreamOfflineException though. That's why I'm a little confused. I put the BroadcasterOnline check as I thought it would alleviate the problem, but I'm still getting those errors thrown and it crashes my app.

**Comment by swiftyspiffy** [comment]
This is really weird. Try changing:
`catch(StreamOfflineException)`
to
`catch(Exception)`

It's almost like the exception is being fired from a different piece of code or something.

**Comment by lexyoussef** [comment]
I'm guessing a new thread created in the lib is throwing the exception and perhaps that's why I can't catch it?

**Comment by lexyoussef** [comment]
K I'll try that now.

**Comment by lexyoussef** [comment]
Ok so catch(Exception) seems to be working fine. Just scares me a little because I'm assuming then the only exception that is being caught is a StreamOfflineException. I'm going to dig a little bit now and see if I can find something helpful to narrow this down some more.

Cheers :)

**Comment by swiftyspiffy** [comment]
Ya, I haven't see this issue before. Pretty weird.

**Comment by lexyoussef** [comment]
Issue hasn't happened again since updating to v5, I'll close this.
