### ISSUE TITLE
Chatter type gone?

### ISSUE THREAD

**Issue by Syzuna** [swiftyspiffy/TwitchLib#179]
Is there a reason why the chatter type is gone and was replaced by Chatters/ChattersResponse which are a pain to work With if you have to determine a users usergroup in Chat. Was much nicer before with the chatter type containing that data

**Comment by Syzuna** [comment]
Well I should write a description.. fail..
But yeah.. is there a reason why the chatter type is gone and was replaced by Chatters/ChattersResponse which are a pain to work With if you have to determine a users usergroup in Chat. Was much nicer before with the chatter type containing that data

**Comment by Syzuna** [comment]
And another thing.. why does the new version throws errors at me non stop`? it says badscope exeption all the time and noclientid expetion and both are correct.. I even made a new token using your generatpr with all scopes.. and besides that I am getting websocket and system.net Webexceptions at the same time. maybe you oversaw sth there?

**Comment by Moerty** [comment]
How do you set the clientid and oauthkey?

**Comment by Syzuna** [comment]
TwitchAPI.Settings.clientID = clientId and the same for the api token

**Comment by swiftyspiffy** [comment]
Ya, so chatter type is gone due to how the parsing is done in the library now. I am not happy with it, and am going to see if I can change how it works to make it similar to how it was earlier. If you are getting scope validation issues, you can turn that off via:
`TwitchAPI.Validators.SkipDynamicScopeValidation = true`

Sorry about the rocky roll out, it was a ton of code. I will work to get the examples up and working again.

**Comment by Syzuna** [comment]
Will test with your latest commit.  Looks like it could be the root of my exception problem

**Comment by swiftyspiffy** [comment]
Are all methods throwing badscope exceptions? There was a bug that caused block_read methods to cause the exception, but that has been fixed earlier (will go out tonight/tomorrow). As far as the TwitchClient is concerned, there was nothing changed as far as I can recall.

**Comment by swiftyspiffy** [comment]
This should be fixed now. Feel free to open again as needed.
