### ISSUE TITLE
MissingClientIDException

### ISSUE THREAD

**Issue by Syzuna** [swiftyspiffy/TwitchLib#182]
So I thought I would make a new issue for that now.

It crashes at GetChatter but not on other API requst as far as I tested now.

So I thought it was my fault so I tested with you Test App and still got the same error.

![clientidexc](https://cloud.githubusercontent.com/assets/22714301/25843110/9091bbae-34a6-11e7-8ecd-f8b05d5ef542.PNG)

![id](https://cloud.githubusercontent.com/assets/22714301/25843121/98a878e6-34a6-11e7-9d1a-420600fd61c6.PNG)

**Comment by swiftyspiffy** [comment]
Looking into this now.

**Comment by swiftyspiffy** [comment]
Looks like it auto closed the issue. Feel free to reopen it.

The problem looks like it was in the testing app and not the library. See the commit above.

**Comment by Syzuna** [comment]
For me it still crashes with no client-Id at the same part in the example app.
