### ISSUE TITLE
InvalidOperation Exception on Pubsub Ping

### ISSUE THREAD

**Issue by Syzuna** [swiftyspiffy/TwitchLib#183]
I am sorry to flood you with issues.
But there is anotherone I encountered now.
Everytime the pubsub is try to send a ping it crashes with an Invalid Operation Exception

![websocketexception](https://cloud.githubusercontent.com/assets/22714301/25843227/ff495d68-34a6-11e7-91c0-23c9f921021a.PNG)

**Comment by swiftyspiffy** [comment]
As long as there are problems with the library, feel free to open issues :)

I will test pubsub now and see if I can recreate the issue.

**Comment by swiftyspiffy** [comment]
So, testing ModeratorActions, I was able to get past several ping/pong patterns:

![https://swfty.xyz/787goM330](https://swfty.xyz/787goM330)

Try uninstalling the library completely and reinstalling it.

**Comment by swiftyspiffy** [comment]
Also for what it's worth, I just updated/renamed the example project to be more consistent with the purpose. One project for testing API, one for testing client/pubsub. Feel free to pull.

**Comment by Syzuna** [comment]
Will look into it thanks :) 

Is there any chance I could send you a copy of my bot code or parts of it for you to look into? bcs I rly dont know why it isnt working for me but for you

**Comment by swiftyspiffy** [comment]
sure swiftyspiffy@gmail.com

**Comment by Syzuna** [comment]
ok send you an email. I hope my mailserver is a good boy today and signs the mail right so it doesnt get filtered

**Comment by Syzuna** [comment]
Ok so I think I narrowed the problem down. 
I got a BadScopeException bcs I used the wrong endpoint for getting the channel Id and that prevented the bot from listening to a topic so the pubsub server closed the connection, but the libary didnt get that so the timer for the ping never stopped

**Comment by swiftyspiffy** [comment]
Do you have an update on this issue @Syzuna ?

**Comment by Syzuna** [comment]
Ye. Due to a wrong parameter it wasnt able to listen to a topic within 15 seconds and closed the connection. But the lib didnt stop the ping timer and with that tried to ping on a closed socket

**Comment by swiftyspiffy** [comment]
What topic were you trying to listen to, and what was the bad parameter?

**Comment by Syzuna** [comment]
Bad Parameter isnt The right word used wrong endpoint to get The channel id. So wasnt able to Listen to the ModeratorActions. So italienische closed the Connection. But the lib didnt Stop the Ping Timer. So italienische tried to Ping in a closed websocket

**Comment by swiftyspiffy** [comment]
Were you listening to OnListenResponse?

If you listen to that, you can figure out if your topic request succeeded or not.

**Comment by Syzuna** [comment]
It didnt succeed I know that. 
But the Problem was/is that your lib doesnt seem to stop the timer for the ping to the pubsub Server if the connection gets closed due to an error or sth. like that. At least it looks like that for me.

**Comment by Syzuna** [comment]
And that caused that initial invalidOperationException

**Comment by swiftyspiffy** [comment]
That should be a pretty straight forward fix, give me a sec.

**Comment by swiftyspiffy** [comment]
Just stops pingTimer on disconnect event.

**Comment by Syzuna** [comment]
Ye should be just pingTimer.Stop () by disconnect

**Comment by Syzuna** [comment]
I think that should be it  :)
Will close this one and will hunt other bugs while rewriting

**Comment by swiftyspiffy** [comment]
Sounds good, thanks :)
