### ISSUE TITLE
TwitchAPI.Streams.v5.BroadcasterOnline only returns true

### ISSUE THREAD

**Issue by hikyle** [swiftyspiffy/TwitchLib#185]
i've tested this on my channel both live and not live. in Postman i get the correct "stream: null" when not live, and the full json when it was detected as live.

BroadcasterOnline ran while not live returned true, as well as true for when i was live.

**Comment by Syzuna** [comment]
Well for me it just throws random MissingClientIdExpeptions at me although I know that the id has to be there bcs I can get the Viewers list on the initial connect to a channel without a problem

**Comment by swiftyspiffy** [comment]
looking into this now.

**Comment by swiftyspiffy** [comment]
git auto closed the issue, but it should be fixed with the above commit.
