### ISSUE TITLE
Cant get rid of MissingClientIDException

### ISSUE THREAD

**Issue by Syzuna** [swiftyspiffy/TwitchLib#186]
I still cant get rid of that MissinhClientIdException.
The first request seems to be ok but then its just failing over and over.
(I know that it has to work at least once bcs I can get the initial Chatter List from the API but for the Broadcaster Online check after a timer tick for viewtime I get that exception which is weird to me

![idexc](https://cloud.githubusercontent.com/assets/22714301/25870563/c713cf4c-3504-11e7-9a56-ebf8b8c2efd3.PNG)

Thats the Exception chain thrown at me all the time

**Comment by Syzuna** [comment]
Omg I am so dumb.. although I dont get why I get a MissingClientIdExpeption for that but I used the channel name instead the channel id bcs it was the channel name before and I didnt look at the parameter name.. omg... I am so sorry for that dumb mistake

**Comment by Syzuna** [comment]
Its working now. But the exception was misleading.
The Id was There But i used the channel name instead of the channel id. That somehow resulted into a missingClientIdException. Dunno why

**Comment by Syzuna** [comment]
I mean i used BroadcasterOnline (channel-name) instead of BroadcasterOnline (channel-id)

**Comment by swiftyspiffy** [comment]
Gotcha, let me look at that. That's a bad exception to throw for an invalid channel id.

**Comment by swiftyspiffy** [comment]
Should be fixed now :) You'll get a BadRequestException now if you try to use a username where userid expected.
