### ISSUE TITLE
TwitchAPI.Follows.GetFollows problem

### ISSUE THREAD

**Issue by DarkoreXOR** [swiftyspiffy/TwitchLib#188]
I want to get followed channels after the 25th, but if I send an offset = 25, I get users as if the offset is 0.

My example:
TwitchAPI.Follows.GetFollows(user, offset: 25);

**Comment by DarkoreXOR** [comment]
This is a problem with the forgotten parameter "paramsStr" in the URL.

**Comment by swiftyspiffy** [comment]
Yup, good catch. Just merged it.
