### ISSUE TITLE
IndexOutOfRangeException parse crash

### ISSUE THREAD

**Issue by TerrahKitsune** [swiftyspiffy/TwitchLib#190]
Row 49 in Models/Client/WhisperMessage.cs will split with tail on the raw irc which will result in an unhandled IndexOutOfRageException if the tail contains a semi-colon.

**Comment by swiftyspiffy** [comment]
Looking into this now.

**Comment by swiftyspiffy** [comment]
Git auto closed the issue, but feel free to reopen if the problem is not fixed with the above commit.
