### ISSUE TITLE
Clip always returning a null Id

### ISSUE THREAD

**Issue by bruxo00** [swiftyspiffy/TwitchLib#192]
Like the title says, the Clip Id is always returning null, no matter what clip I try.

[Example](https://i.gyazo.com/466d8ca354163700d3964047dfd46216.png)

(c is a Clip)

**Comment by Syzuna** [comment]
The Clip itself has no Id I think only a tracking Id.
Maybe thats sth. from the old v3 API that got copy pasted without notice?

See https://dev.twitch.tv/docs/v5/reference/clips/#get-clip for reference

**Comment by swiftyspiffy** [comment]
Looking into this.

**Comment by swiftyspiffy** [comment]
Feel free to reopen this as needed.
