### ISSUE TITLE
How to get a list of all viewers in a chatroom?

### ISSUE THREAD

**Issue by simonmannsfeld** [swiftyspiffy/TwitchLib#193]
I found no possibility to get a full list of viewers in a chatroom, is there any possibility as WebSocket or something else with TwitchLib?

**Comment by swiftyspiffy** [comment]
Because it's not officially supported/documented by Twitch, you can find the endpoint in the Undocumented static sub class of TwitchAPI:

```
var chatters = await TwitchLib.TwitchAPI.Undocumented.GetChatters("channel-name");
```

**Comment by swiftyspiffy** [comment]
Feel free to reopen this as needed.
