### ISSUE TITLE
TwitchClient OnUserJoined Event delay

### ISSUE THREAD

**Issue by simonmannsfeld** [swiftyspiffy/TwitchLib#194]
If a user joins the chatroom, i got a delay of 2-3 minutes between user join till the event fired.

**Comment by swiftyspiffy** [comment]
The event fires right when Twitch sends the data to the client. In other words, the timing is reliant on Twitch, and not the library :(

**Comment by swiftyspiffy** [comment]
Feel free to reopen this as needed.
