### ISSUE TITLE
Broadcaster is parsed as Mod and Broadcaster?

### ISSUE THREAD

**Issue by Syzuna** [swiftyspiffy/TwitchLib#195]
Is the Broadcaster parsed as Mod and Broadcaster in the GetChatter-Method?
I get the Broadcaster back as Mod and Broadcaster which is a bit annoying

**Comment by prom3theu5** [comment]
Technically this is correct
A broadcaster is a Moderator in their own Twitch Channel

**Comment by Syzuna** [comment]
well ok then I have to rework my system for user tracking

**Comment by swiftyspiffy** [comment]
Actually, I do manually add the streamer as a broadcaster, and then GetChatters data adds it again as a moderator. I think the correct route is to just serve up what https://tmi.twitch.tv/group/user/{channelName}/chatters serves, which would mean that the streamer doesn't get "broadcaster" usertype. I will correct this now, just to prevent confusion.

**Comment by swiftyspiffy** [comment]
If you want to give that commit ^ a go, it should fix the confusion. The response will only include the results returned by Twitch, as expected. Sorry about that.

**Comment by Syzuna** [comment]
Thx  :) Will give it a try^^
