### ISSUE TITLE
Small README code sample mistakes

### ISSUE THREAD

**Issue by Subtixx** [swiftyspiffy/TwitchLib#199]
```csharp
private void onCommandReceived(object sender, OnWhisperCommandReceivedArgs e) {
	if(e.Command == "help")
    	client.SendMessage($"Hi there {e.ChatMessage.Username}! You can view all commands using !command");
}
```
Doesn't compile. Since e.ChatMessage doesn't exist. It should be e.WhisperMessage

EDIT:
Version: 1.4.9 from Nuget

**Comment by elu00** [comment]
Hiya,
In the future, I think you should feel free to just submit a PR for small changes like this. 
Anyway, just made a small PR for this: #200

**Comment by swiftyspiffy** [comment]
Looks good guys! Thanks!

**Comment by Subtixx** [comment]
elu00 Yes I probably should have :S.

I dunno what happened but I had more reported than this. I guess when I added the version number it got deleted.

Anyway. I made a pullrequest for the 2nd mistake I found
