### ISSUE TITLE
Calling client.JoinChannel seems to block joining channels

### ISSUE THREAD

**Issue by RickRosendaal** [swiftyspiffy/TwitchLib#2]
When creating a new client, initializing it (with or without providing a channel), calling .Connect(), and then client.JoinChannel("name"), will result into the client never joining the channel.
The following example will print "Connected". But not "Joined channel".
Removing the "client.JoinChannel" line, will print "Connected", as well as "Joined channel".
Removing the "DamnICantFly" channel parameter in the Initialize method, will again print "Connected", but not "Joined channel".

```csharp
private void Start()
{
	Client client = new Client();
	client.OnConnected += OnConnected;
	client.OnJoinedChannel += OnJoinedChannel;
	client.Initialize(new TwitchLib.Client.Models.ConnectionCredentials("DamnICantFly", "oauth_token"), "DamnICantFly");
	client.Connect();
	client.JoinChannel("LuckyNoS7evin");
}

private void OnConnected(object sender, TwitchLib.Client.Events.OnConnectedArgs e)
{
	Debug.Log("Connected");
}

private void OnJoinedChannel(object sender, TwitchLib.Client.Events.OnJoinedChannelArgs e)
{
	Debug.Log("Joined channel");
}
```

**Comment by swiftyspiffy** [comment]
Hey! I'm going to move this issue over to the proper repo so we can discuss it there. This repo is no longer active. Additionally, I'll edit out your oauth token ;)

Moved here: https://github.com/TwitchLib/TwitchLib.Client/issues/31
