### ISSUE TITLE
How to handle login exception?

### ISSUE THREAD

**Issue by Bootscreen** [swiftyspiffy/TwitchLib#2]
Hy,

first thanks for your realy nice lib =)
but i have a problem and hope you can help me. 

Every time i try to login with wrong login data i get this message after a few secounds:

> TwitchLib.Exceptions.ErrorLoggingInException was unhandled by user code
  HResult=-2146233088
  Message=:tmi.twitch.tv NOTICE * :Error logging in
  Source=TwitchLib
  StackTrace:
       bei TwitchLib.TwitchChatClient.onReadLine(Object sender, ReadLineEventArgs e) in D:\Dropbox\Codding & Scripting\C#\TwitchLib-master\TwitchLib\TwitchChatClient.cs:Zeile 242.
       bei Meebey.SmartIrc4net.ReadLineEventHandler.Invoke(Object sender, ReadLineEventArgs e)
       bei Meebey.SmartIrc4net.IrcConnection.ReadLine(Boolean blocking)
       bei Meebey.SmartIrc4net.IrcConnection.Listen(Boolean blocking)
       bei Meebey.SmartIrc4net.IrcConnection.Listen()
       bei TwitchLib.TwitchChatClient.<onConnected>b__62_0() in D:\Dropbox\Codding & Scripting\C#\TwitchLib-master\TwitchLib\TwitchChatClient.cs:Zeile 129.
       bei System.Threading.Tasks.Task.InnerInvoke()
       bei System.Threading.Tasks.Task.Execute()
  InnerException: 

I get this in my own project and in the twitchlib example project. can you tell me how i can handle this exception?

try and catch around the following doesn't work:
`TwitchChatClient client = new TwitchChatClient(textBox8.Text, credentials, '!');`
`client.NewChatMessage += new EventHandler<TwitchChatClient.NewChatMessageArgs>(MsgRec);`
`client.CommandReceived += new EventHandler<TwitchChatClient.CommandReceivedArgs>(ComReg);`
`client.connect();`

i hope you can help me.

greetings
Bootscreen

**Comment by swiftyspiffy** [comment]
Hey, sorry about this, I didn't have a focus on it as I have been using this library in my bot and I'm 100% credentials are correct.  Now that my school is done for the semester, I have a fix for this that will be pushed shortly.  

Because a login failure is detected only through a returned message from Twitch, I have implemented an event that fires with an exception in it detailing the login failure (and the account username it occurred to). You'll want to subscribe to the IncorrectLogin event on both the ChatClient or the WhsiperClient.

Cheers.

**Comment by swiftyspiffy** [comment]
Alright pushed. Let me know if that's what you were looking for. :)

**Comment by Bootscreen** [comment]
this is awesome. thx
i try it and let you know about the result

**Comment by Bootscreen** [comment]
it works fine =)
but is it possibled to get also an event when succesfull logged in and get a IsLoggedIn getter such as IsConnected ?

**Comment by swiftyspiffy** [comment]
Sure, I'll that later today. I'll comment here again when it's pushed.

**Comment by swiftyspiffy** [comment]
I'll add that later today*

**Comment by swiftyspiffy** [comment]
Alright, so the OnConnected event was fixed to properly detect an authenticated login on both the Whisper and Chat clients, so if you subscribe to it, it should fire pretty quickly after you call the connect() method if it logged in correctly.
Additionally, both the Chat and Whisper clients have a property IsConnected which is a boolean, and I believe returns the accurate state.

Cheers :)

**Comment by swiftyspiffy** [comment]
As a side note, the ChannelStateAssigned event fires pretty quickly after joining a channel.  Although it can be fired again after joining a channel (if r9k, slow mode, sub only, etc changes), if you insert logic for the first time this event is fired, you can essentially have an event for joining a channel successfully.

**Comment by Bootscreen** [comment]
Thanks, your work is awesome =)

**Comment by swiftyspiffy** [comment]
Thanks :)
