### ISSUE TITLE
Support for detecting hosting of connected channel

### ISSUE THREAD

**Issue by swiftyspiffy** [swiftyspiffy/TwitchLib#20]
A HOSTTARGET event message is sent when another channel hosts the client-connected channel.  This needs to be an event that can be subscribed to, parameters should be the channel that hosted, and the number of viewers.  It is possible that no channel name is presented, I guess ignore such events?  An example of such a message is below:

:tmi.twitch.tv HOSTTARGET #burkeblack :grawgh 16

I will work on this at some point this week.

**Comment by igor523** [comment]
According to [this](https://github.com/justintv/Twitch-API/blob/master/IRC.md#hosttarget), omitting channel name means that hosting has been stopped by channel, that previously hosted.

**Comment by igor523** [comment]
#21 Some baby steps towards hosting parse

**Comment by igor523** [comment]
I think, you can close it now, you've merged my commits for this

**Comment by swiftyspiffy** [comment]
Agreed.
