### ISSUE TITLE
Gitter Chat

### ISSUE THREAD

**Issue by elu00** [swiftyspiffy/TwitchLib#202]
Hiya,
Just wondering if there'd be any interest in providing a [gitter](https://gitter.im/) chatroom for this library.
As far as maintenance/setup, it doesn't seem like it'd be too much of a hassle, and I definitely think it'd be an improvement over the general twitch dev discord/irc channels. 
In addition, I'd definitely be willing to put in the time to moderate/organise it as necessary.

Thanks!

**Comment by swiftyspiffy** [comment]
I'd be interested in that, sure. I'll set one up.

**Comment by swiftyspiffy** [comment]
Went ahead and added it to the readme. I'll close this now :)
