### ISSUE TITLE
GetUserFollows only returns 25 results

### ISSUE THREAD

**Issue by drmazo** [swiftyspiffy/TwitchLib#205]
Hello,
First of all thanks for the amazing work, this has been working flawlessly for me except for this little issue.

When calling GetUserFollows, it only returns 25 results, despite having a total of 80+ follows.
I tried to change the limit or the offset parameter but to no avail (still 25 same results).
Thanks for your help.

**Comment by swiftyspiffy** [comment]
I'm at work at the moment, but I'll try to get this fixed in a few hours, I think I know what the problem is. This and another relatively serious bug should be in a new NuGet version tonight or early tomorrow morning.

Also thanks for the kind words :)

**Comment by drmazo** [comment]
No worries, thanks a lot !

**Comment by swiftyspiffy** [comment]
If you want to try to fix it locally, the issue is on line 1105 of TwitchLib/Internal/TwitchAPI/v5.cs

The API cal doesn't include the passed in parameters like it should. optionalParameters strings should be appended to the end of the URL.

**Comment by drmazo** [comment]
I'll try it

**Comment by drmazo** [comment]
Like this ?
`return await Requests.GetGeneric<Models.API.v5.Users.UserFollows>($"https://api.twitch.tv/kraken/users/{userId}/follows/channels" +optionalQuery ,null, Requests.API.v5);`

**Comment by swiftyspiffy** [comment]
Fixed.
