### ISSUE TITLE
TwitchAPI - server cached requests

### ISSUE THREAD

**Issue by horato** [swiftyspiffy/TwitchLib#207]
Hi,
Firstly, I'd like to say your library looks awesome. Everything is so transparent and there is almost no need to browse twitch api documentation.

Secondly, twitch servers are caching requests and, when you send 2 identical requests in a few minutes, it returns the same response. This means that any change made before the cache is emptied is not returned. At least thats how it used to work few years back.
I was using the following "workaround":
`var json = client.DownloadString("http://tmi.twitch.tv/group/user/horato2/chatters?rand=" + Environment.TickCount);`

Is there anything like it implemented in your library? Thanks :)

**Comment by swiftyspiffy** [comment]
I am aware of this style of a work around but I was not aware it'd work with the Twitch API. I had assumed they cached data based on the requested resource, not how the client is requesting the data. If you are certain this kind of workaround does indeed work, then I can go ahead and implement it.

Also that endpoint you're using is located in: TwitchLib.TwitchAPI.Undocumented.GetChatters I believe

**Comment by swiftyspiffy** [comment]
Going to go ahead and close this. Feel to re-open.
