### ISSUE TITLE
Room-id in ChatMessage

### ISSUE THREAD

**Issue by Devexer** [swiftyspiffy/TwitchLib#208]
I was just wondering if there is a reason room-id is not included in the parsing of PRIVMSG and included in the ChatMessage model? I see you have it included in the IRC message example comment in the model. With the move to V5 it would be handy to have this accessible in the chat message, and not need to request it from the API for every unknown channel.

**Comment by swiftyspiffy** [comment]
It was part of the model at one point I'm fairly sure. As to why it was removed I can't recall. I'll re-add it tomorrow though.

**Comment by Devexer** [comment]
Alright, sounds good. Thanks.

**Comment by swiftyspiffy** [comment]
Should be added now. As a side note, it seems user-id and room-id are the same, which I guess makes sense. Cheers :)
