### ISSUE TITLE
Get all followers

### ISSUE THREAD

**Issue by Legion-5** [swiftyspiffy/TwitchLib#209]
Hi.
Is there any way to get all followers by one command? How can I get them if using cursor with limit=100 by your lib?

Thank you!

**Comment by swiftyspiffy** [comment]
There isn't. Although it's probably not a good idea, I'll go ahead and add a way to get all followers similar to the function that returns all subscribers.

**Comment by swiftyspiffy** [comment]
Hey, sorry about the delay. This should be what you're looking for: a8c5c76be647328e07232534268b8a05e45a652c
