### ISSUE TITLE
Unbanned event

### ISSUE THREAD

**Issue by vaindil** [swiftyspiffy/TwitchLib#210]
I noticed there's no unbanned event in the library. It doesn't look like Twitch IRC even provides that, but I wanted to check if it's possible just in case I'm missing something.

**Comment by swiftyspiffy** [comment]
Well, there is unban information available in the library, but not through the conventional TwitchClient. What you need to do is use the PubSub client and then listen on the moderator actions topic. To do this requires a moderator's oauth token, but once listening, you an event will be raised for every timeout/tempban, ban, and unban.

**Comment by vaindil** [comment]
Is that undocumented? I don't see it in [the docs](https://dev.twitch.tv/docs/v5/guides/PubSub/).

**Comment by vaindil** [comment]
Gotcha, that makes sense. Awesome, I'll use that then. Thank you!

Side note: I'm happy to help write documentation if you need it.

**Comment by swiftyspiffy** [comment]
I've been using doxygen to do it because I'm lazy. 

Or wait, maybe you're referring to the topic being undocumented. What I meant by that was that Twitch hasn't documented the topic because they don't officially support it.

**Comment by vaindil** [comment]
Oh, no, I meant the library docs, just didn't want to open a new issue for a quick mention of that. I see there are broken links and whatnot on the site.

**Comment by swiftyspiffy** [comment]
On the doxygen docs there's broken links? Hmm, there shouldn't be.

**Comment by vaindil** [comment]
Yeah, none of the "click here for more info" links work.

> For a complete list of TwitchPubSub functionality, [click here](http://swiftyspiffy.com/TwitchLib/pubsub.html)

**Comment by swiftyspiffy** [comment]
I think this should be able to be resolved via doxygen generator, but idk. I'm still pretty new to it and it's fairly complex. If I can't figure it out, I'd be interested in taking you up on your offer, lol.
