### ISSUE TITLE
All followers doesn't return all followers

### ISSUE THREAD

**Issue by Legion-5** [swiftyspiffy/TwitchLib#211]
Hi.
This method TwitchLib.TwitchAPI.Channels.v5.GetAllFollowers doesn't return all followers, it seems this function TwitchLib.TwitchAPI.Channels.v5.GetChannelFollowers in loop always return 0 followers because named-param "direction" is missing asc is cursor.
Thanks!

**Comment by swiftyspiffy** [comment]
I ran into this problem testing it and could have sworn I fixed it. Guess not. Will fix it in a few hours.

**Comment by Legion-5** [comment]
I see, thanks a lot!

**Comment by swiftyspiffy** [comment]
So I just tested it using the TwitchLib-API-Tester on my channel (swiftyspiffy, id: 40876073) and it seemed to pull them all. Can you share the channel you're testing on?

**Comment by Legion-5** [comment]
this line var requestedFollowers = await GetChannelFollowers(channelId, 100, currentOffset, "asc"); 
must be var requestedFollowers = await GetChannelFollowers(channelId, 100, currentOffset, direction:"asc");
Otherwise function  GetChannelFollowers return <=200 (even if channel has more) because normally exec 2 times calling GetChannelFollowers:
 var firstBatch = await Channels.GetChannelFollowers(channelId, 100, 0, direction: "asc");
var leftOverFollowersRequest = await GetChannelFollowers(channelId, leftOverFollowers, currentOffset, direction: "asc");

**Comment by swiftyspiffy** [comment]
Oh, I see what you're saying, that makes sense. My channel has 129 followers so I wouldn't detect that error. Fixing now.

**Comment by swiftyspiffy** [comment]
Check that commit and let me know. Sorry about that.

**Comment by Legion-5** [comment]
Now it's correct, thanks a lot! You are doing a great job!
