### ISSUE TITLE
Whisper doesn't send

### ISSUE THREAD

**Issue by vaindil** [swiftyspiffy/TwitchLib#212]
I'm attempting to send a whisper in an OnMessageReceived handler, but it's not sent. No error in the logs; the logs don't indicate anything related to the whisper at all. The user is banned properly, just no whisper is sent. Not sure what's going on. I enabled logging with `client.Logging = true;`, not sure if there's another way to enable debug logging. (For the record, the handler is being hit, I made sure of that. Everything in the handler works properly except for the whisper.)

```csharp
async void OnMessageReceivedWhisper(object sender, OnMessageReceivedArgs e)
{
    var user = e.ChatMessage.Username.ToLowerInvariant();
    
    // do a bunch of filtering, I'm not whispering everyone on every message

    client.BanUser(client.GetJoinedChannel(e.ChatMessage.Channel), user, "Check your whispers.");
    client.SendWhisper(user, "test");
}
```

**Comment by swiftyspiffy** [comment]
Is it possible your account was blocked by Twitch? Can you try using your personal account and send a whisper from it using the library. For what it's worth, my whisper functionality seems to work

**Comment by vaindil** [comment]
Just tried with my personal token, still no dice. Also tested whispering a different user in case it was something with my test account, but he didn't receive the whisper either. Would a whisper show up in the normal log? There's nothing there related to a whisper at all, it's not even trying.

**Comment by swiftyspiffy** [comment]
I can't recall if there is a logged message when a whisper is sent (at work at the moment). Are you able to dive down into the whisper method and see if it appears to be firing the internal methods for whisper?

**Comment by vaindil** [comment]
Sure thing, I can check later tonight. I'll let you know.

**Comment by Syzuna** [comment]
I think the person needs to whisper the bot once first. The bot cant whisper an account that wasnt whispered before

**Comment by vaindil** [comment]
@Syzuna Why would the bot be treated differently than a normal account? Twitch doesn't distinguish them, and I can whisper someone without them having whispered me first. (Honest question, I don't know a lot of the intricacies of the Twitch API.)

**Comment by Syzuna** [comment]
@vaindil I only read about that in the Twitch forum thats why I thought It might help you.
https://discuss.dev.twitch.tv/t/unable-to-send-whispers-via-bot/9385/10
https://discuss.dev.twitch.tv/t/first-whisper-through-irc-doesnt-work-unless-conversation-already-established/9515/6

**Comment by vaindil** [comment]
@Syzuna Ah, okay, I see those now. I sent an email to support to ask if the bot can be whitelisted or something, not sure what's going on. I'll report back when I hear from them.

**Comment by swiftyspiffy** [comment]
Good point by Syzuna. Accounts connecting via irc/websockets have a different set of enforced rules than those connecting via browser for obvious reasons.

**Comment by swiftyspiffy** [comment]
Going to go ahead and close this. Feel to re-open if you're convinced issue is with library..
