### ISSUE TITLE
Cannot read from frame header after Connect()

### ISSUE THREAD

**Issue by phxvyper** [swiftyspiffy/TwitchLib#213]
In reference to #203 ... I finally have a chance to get back to this. I uninstalled TwitchLib and websocket- sharp and then reinstalled the latest version of TwitchLib... to no avail:

```cs
6/16/2017 13:12:56|Fatal|WebSocket.<startReceiving>b__175_2:0|WebSocketSharp.WebSocketException: The header of a frame cannot be read from the stream.
                            at WebSocketSharp.WebSocketFrame.processHeader(Byte[] header)
                            at WebSocketSharp.WebSocketFrame.<>c__DisplayClass73_0.<readHeaderAsync>b__0(Byte[] bytes)
                            at WebSocketSharp.Ext.<>c__DisplayClass55_0.<ReadBytesAsync>b__0(IAsyncResult ar)
```

I added the TwitchLib project to my solution and referenced the project instead of the nuget package. No luck.

.NET version doesnt change anything, as usual.

I even passed my compiled program through my firewall.

Also, the program doesnt crash or anything, its simply that called `Connect();` causes the previously described exception. What do.avi

I made a new issue since I was cannot reopen the old one (a collaborator closed it instead of myself).

**Comment by swiftyspiffy** [comment]
Is it possible for you to try the bot on a different network (I assume you are trying it from a home network)? Everything I've read about this error points to an issue in the network.

**Comment by phxvyper** [comment]
No I dont really have a way of doing that :/ Is there a port that needs to be open or something that needs to be changed on my network for it to work properly?

**Comment by swiftyspiffy** [comment]
Do you hit this error both in debugger and when you run the exe independent of VS? I'm reaching, but maybe try VS2015? I'm pretty much out of ideas, the error doesn't seem to have a hard fix judging by issues on websocksharp github repo.

**Comment by phxvyper** [comment]
Nothing at all happens when its ran outside of VS. If it connected or there was a connection error then something would show up in my event box. I'm also not able to get my program to output the exception to a log file, either.

**Comment by Syzuna** [comment]
do you know where the exception is thrown? if yes give the method the [HandleProcessCorruptedStateExceptions] attribute and use a try catch on it

**Comment by phxvyper** [comment]
I should've turned on logging in TwitchLib way ahead of time...

`JsonConvert` cant reflect a property's set routine if that routine is `internal`. This caused my saved `Username` value to be a non-null empty string, since I use `JsonConvert` to save and load my config. TwitchLib doesn't do simple verification on the string passed to see if its empty or null, causing it to successfully send to the server.

Empty strings always result in an `Invalid NICK` error . For some reason, an `Invalid NICK` error isnt properly caught by TwitchLib and ends up leading to the exception ive been getting for about a month now. I fixed the issue on my side by removing the `internal` access modifier from the property's set routine.

However, TwitchLib should at the very least do some simple verification on the username. I actually do this already like so:

```cs
public static string TwitchUsernamePattern => "^([a-zA-Z0-9][a-zA-Z0-9_]{3,25})$";

public static bool IsValidUsername(string username) => new Regex(TwitchUsernamePattern).Match(username).Success;
```

as Twitch usernames have to fulfill that regex completely in order for it to be a valid username (usernames cannot start with an underscore, must be at least 4 characters long, less than 25 characters long, and may contain alphanumeric characters)

**Comment by swiftyspiffy** [comment]
The closed connection should be handled by websocketsharp and a disconnect event raised to the library itself, I would think. That being said, it never occurred to me to validate the twitch username, but I'll go ahead and add that. Sorry about the issue.
