### ISSUE TITLE
Get unfollowed user

### ISSUE THREAD

**Issue by Legion-5** [swiftyspiffy/TwitchLib#215]
Hi,
one more question: Do you know way how to get unfollow user, or an event that indicates that follow user now is unfollow? Without to scan whole list of followers and to check with prev followers list?
Is your library has this func? Like the FollowerService has event OnNewFollowersDetected, but for unfollows?
I just see it in WizeBot.
Anyway thank you one more time.

**Comment by igor523** [comment]
Hello!
No, its not possible without full scan. Even if this lib will implement this, its will be a full scan anyway.

**Comment by Legion-5** [comment]
So, do you have any suggestions how it implement in wizebot? Is it scan too?

**Comment by igor523** [comment]
Yes. It's just impossible without it, because Twitch doesnt make any notifications about unfollowings.

**Comment by swiftyspiffy** [comment]
You'd basically have to have a master set of follows (all follows) and then constantly scan against those follows to see if any of them are missing (or to add new follows). Resource-wise it wouldn't be cheap.

**Comment by Legion-5** [comment]
Okay, I got it, thanks!
I was thinking in the same direction, but always scan all follows isn't a good solution.
