### ISSUE TITLE
ChatMessage IsPartnered does not reflect partner status

### ISSUE THREAD

**Issue by 3ventic** [swiftyspiffy/TwitchLib#217]
The IsPartnered is documented as "Property representing whether or not person is a partner", but this is inaccurate. It only represents the status/presence of the Verified badge, which _at the moment_ is exclusive to partners, but many choose to hide it breaking this functionality.

It should be IsVerified or at the very least documented correctly in the code.

https://github.com/swiftyspiffy/TwitchLib/blob/7af95c1e3f4bf2020e15b0be23eb1e127796bfdf/TwitchLib/Models/Client/Subscriber.cs#L48

**Comment by swiftyspiffy** [comment]
You make a good point. Will fix this after work tonight.
