### ISSUE TITLE
Special characters like Ä Ö Ü are not working.

### ISSUE THREAD

**Issue by DerpyDoom** [swiftyspiffy/TwitchLib#22]
Well the Titel tell everything, somehow my Console Twitch Bot can't send characters like ö ä or ü or even ß.

Is this an API problem, or is the problem on my site?

**Comment by swiftyspiffy** [comment]
I was having this issue too, but I figured it was localized to just me.  Give me a bit, and I'll look into it.

**Comment by swiftyspiffy** [comment]
I just tested, and the characters you listed in the title seem to be working correctly.  While the library does use the Default encoding, I wouldn't think that would be the issue.  Are you using the latest version of the library (v1.1.1)?

**Comment by DerpyDoom** [comment]
It seems like an Update to v1.1.1 helped. Thanks again :+1:
