### ISSUE TITLE
Autohost Message

### ISSUE THREAD

**Issue by D3thw0lf** [swiftyspiffy/TwitchLib#220]
Hey a Friend of mine found this thing here maybe you can use it to implement Autohost Responses (so bot can say thanks for Autohost or just to get a alert etc.)

https://discuss.dev.twitch.tv/t/differentiate-host-and-auto-host/7829

If this is already done just close my issue. ^^ <3

**Comment by swiftyspiffy** [comment]
This has not been implemented and should be pretty straight forward. I can't do it at the moment though. Will keep this issue open as a reminder.

**Comment by D3thw0lf** [comment]
Nice I'll try this out asap. 👍
