### ISSUE TITLE
Affiliate Subs

### ISSUE THREAD

**Issue by Syzuna** [swiftyspiffy/TwitchLib#221]
Hey swifty :)

I know you are kinda busy lately and the Affiliate Sub thing is new but is there a way you can get detection and stuff for that in to your libary? :)

Regards

**Comment by swiftyspiffy** [comment]
I could be wrong but I don't think there's an API route to discover this kind of information. There maybe information in the messages received in chat but that's fairly unlikely. I'll check both this weekend. Also, keep an eye on twitch developer forums, there's a good chance someone will ask about it if they haven't already.

**Comment by Syzuna** [comment]
Do you think twitch is labeling them as partnes too so I could use the new sub event?

**Comment by swiftyspiffy** [comment]
I'm not sure. Will need to listen to some messages in an affiliates channel with subs talking to know for sure.
