### ISSUE TITLE
Can't get the Emote Example to work

### ISSUE THREAD

**Issue by D3thw0lf** [swiftyspiffy/TwitchLib#222]
Is there any example yet how to get the emotes to work for example in a RichTextBox?

I would like to use them but the example (API Tester) does not work for me. :/

Cheers

**Comment by swiftyspiffy** [comment]
In a richtextbox? That can be tricky. There are two routes. One is that you can try to build a custom control that allows you to insert images in. This can be quite difficult if you don't have experience with custom controls in .NET. The second route is much easier using WPF. My friend SkyHuk is working on a twitch WPF client that has managed to insert badges and emotes in his form. You can see his project here: https://github.com/SkyHuk/Purple

**Comment by D3thw0lf** [comment]
Ah nice. WPF is exactly what I need. I'll take a look how he managed to get this done. 👍 

Thanks (as always) for your help.

**Comment by swiftyspiffy** [comment]
Will close this :)
