### ISSUE TITLE
GetCheermotes throws JsonSerializationException

### ISSUE THREAD

**Issue by RickRosendaal** [swiftyspiffy/TwitchLib#223]
When attempting to get information from cheermotes using: `await TwitchAPI.Bits.v5.GetCheermotes("DamnICantFly");`
A JsonSerializationException is thrown.

> Exception thrown: 'Newtonsoft.Json.JsonSerializationException' in Newtonsoft.Json.dll
> 
> Additional information: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'TwitchLib.Models.API.v5.Bits.Action[]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.

When checking out the data which is returned from the await before attempting to deserialize, it seems exactly the same as when checking out the direct url "https://api.twitch.tv/kraken/bits/actions?channel_id=damnicantfly&client_id=**[client_id]**&api_version=5".

Not sure if I'm doing something wrong, but this seems like a bug.

**Comment by swiftyspiffy** [comment]
Looks like a bug. Looking into it now.

**Comment by swiftyspiffy** [comment]
Feel free to reopen this if that commit didn't fix the problem. Pushing a new nuget package tonight/tomorrow morning: 1.5.3

**Comment by RickRosendaal** [comment]
I can confirm, this fixed the problem. Thank you for your quick response!
