### ISSUE TITLE
BadgeContent Image_Url_4x always returns empty

### ISSUE THREAD

**Issue by RickRosendaal** [swiftyspiffy/TwitchLib#224]
Within the class BadgeContent, the property "Image_Url_4x" always returns empty.
Changing `[JsonProperty(PropertyName = "image_url_3x")]` to `[JsonProperty(PropertyName = "image_url_4x")]
` fixed this issue for me.

**Comment by swiftyspiffy** [comment]
Should be resolved now, thanks!
