### ISSUE TITLE
How to get viewer watch time?

### ISSUE THREAD

**Issue by PlumpNuggets** [swiftyspiffy/TwitchLib#225]
i want to display the viewer watch time of this player

if(e.ChatMessage.Message.StartsWith("!hours", StringComparison.InvariantCultureIgnoreCase))
            {
                client.SendMessage($"{e.ChatMessage.Username} Has been watching for {hoursviewerwatched}");
            }

**Comment by Syzuna** [comment]
you have to track it yourself in a database. there is nothing in the lib or in the twitch api that does that for you

**Comment by swiftyspiffy** [comment]
As discussed, this is outside the scope of the project as TwitchLib strives to be the foundation of a Twitch bot and offer up the functionality to enable just about anything related to Twitch. To include such functionality in the bot would considerably bloat the library as most developers wouldnt use this functionality, I think.

As far as how to go about this. I would do what Syzuna said.
1. Create timer with an interval of 60000 (1 minute).
2. Your timer elapsed event should look something like this:
```
public async static void onWatchTimeElapsed(object sender, System.Timers.ElapsedEventArgs e)
{
            var viewers = await TwitchLib.TwitchAPI.Undocumented.GetChatters("channel_name");
            // do whatever you want with viewers object
}
```

**Comment by swiftyspiffy** [comment]
As mentioned earlier, because this is out of scope of the project, I'm going to go ahead and close this. If you need help with anything else, you can reopen though.
