### ISSUE TITLE
Chatters list with 1k+ chatters

### ISSUE THREAD

**Issue by Antilles7227** [swiftyspiffy/TwitchLib#228]
If there is more than 1k chatters in chat, OnExistingUsersDetectedArgs return only list of moderators, not the all users. Twitch Docs says that it's normal behavior of NAMES command, but it's not quite good, in my opinion.

**Comment by swiftyspiffy** [comment]
That is correct. Additionally, when there are a lot of viewers/chatters, the TwitchAPI.Undocumented.GetCHatters method is also very inaccurate at that point. I'm not sure there is a way to get the viewer/chatter list with a lot of viewers in the channel.

**Comment by Antilles7227** [comment]
tmi.twitch.tv/group/user/<channel>/chatters is the best way to solve that problem.
That link return JSON with number of chatters and lists of moderators, admin, staff, viewers etc.

**Comment by swiftyspiffy** [comment]
That endpoint is what TwitchAPI.Undocumented.GetChatters hits. But, as stated in the Twitch dev forums, even that endpoint becomes fairly inaccurate with larger channels.

**Comment by Antilles7227** [comment]
I think, it's happend because some viewers use somethink like BetterTTV, that extention has "Anon chat" option.
Anyway, ticket can be closed, I think.

**Comment by swiftyspiffy** [comment]
Gotcha. From what I've heard, Twitch chat API endpoint simply don't work well when there large streams. Anyways, I'll close it.
