### ISSUE TITLE
Issue with Twitch API settings

### ISSUE THREAD

**Issue by ubbaSWalter** [swiftyspiffy/TwitchLib#229]
So I am trying to set up TwitchLibs TwitchAPI.  I am trying to set up Client ID and Oauth Token.  However neither one is being picked up though Visual Studio .  I am wonder if they got moved or something?  I am using twitchLib version 1.5.3

**Comment by swiftyspiffy** [comment]
The correct way to set them is:
TwitchLib.TwitchAPI.Settings.ClientId = "";
TwitchLib.TwitchAPI.Settings.AccessToken = "";

And yes, the location of these settings were moved a while back. If you are having a problem and are certain your settings are correct, you can override exceptions by using TwitchLib.TwitchAPI.Settings.Validators class.

**Comment by swiftyspiffy** [comment]
I'm going to go ahead and close this now.
