### ISSUE TITLE
Noisy messages

### ISSUE THREAD

**Issue by igor523** [swiftyspiffy/TwitchLib#230]
Hello!

I don't know where should I ask things like that, so sorry for new issue.
I can't find any info on Noisy tag that your lib is parsing. Also, I don't see that tag on channels when i look raw strings captured. Can you tell more about it or give me some links to read?

 Thanks!

**Comment by swiftyspiffy** [comment]
I've heard and seen discussion regarding the Noisy tag in messages. From what I understand, ya largely beta feature and only enabled in certain channels. Last I saw was that it was slowly being rolled out. I think the Noisy tag indicates if a message would be perceived as being "noisy", as in being all caps or something. Although, it probably doesn't help that the default value is "false" even though most channels don't support the feature.

**Comment by igor523** [comment]
Okay, got it. Thanks for the reply! =)
