### ISSUE TITLE
Implement property for stream_type

### ISSUE THREAD

**Issue by smiithy** [swiftyspiffy/TwitchLib#236]
Twitch has implemented a new type of streams called VodCast which are only possible to differentiate from live streams by the property stream_type in the returned json from Twitch.

Would need this to mapped to a property in the Stream class so VodCasts are not treated as live streams.

More info here: https://discuss.dev.twitch.tv/t/vodcasts-not-reported-as-playlist-streams-in-api/10603

**Comment by swiftyspiffy** [comment]
Hi!

I just pushed the commit above that should add a StreamType property to the Stream model. It will either be "live"  (for live) or "watch_party" (for vod_cast). 

Let me know if it works.

**Comment by smiithy** [comment]
Works perfect.

Thank you!
