### ISSUE TITLE
PubSub:  The header of a frame cannot be read from the stream

### ISSUE THREAD

**Issue by damagefilter** [swiftyspiffy/TwitchLib#237]
Hello.

It seems like a very rare problem from what I've read it mostly happened in TwitchClient.

This here now happens in PubSub.
I'm trying it as follows:
````
this.pubSub = new TwitchPubSub(true);
this.pubSub.OnStreamUp += OnStreamStart;
this.pubSub.OnStreamDown += OnStreamEnd;
this.pubSub.OnPubSubServiceConnected += (sender, args) => {
    log.Info("Connected to PubSub");
};
this.pubSub.Connect();
````

It will connect, no problem. The OnOpen is called.
Then, after roughly 30 seconds it failes with the following:
````
21.07.2017 18:15:10|Fatal|WebSocket.<startReceiving>b__175_2:0|WebSocketSharp.WebSocketException: The header of a frame cannot be read from the stream.
                             bei WebSocketSharp.WebSocketFrame.processHeader(Byte[] header)
                             bei WebSocketSharp.WebSocketFrame.<>c__DisplayClass73_0.<readHeaderAsync>b__0(Byte[] bytes)
                             bei WebSocketSharp.Ext.<>c__DisplayClass55_0.<ReadBytesAsync>b__0(IAsyncResult ar)
````

Worth noting: After that exception is thrown it stays connected and receives the OnClose callback. Only after that the connection is actually terminated.

There is no indication, however, from where this exception is coming from or what exactly is causing it.

I've read somewhere in the docs that you need to receive at least one event from PubSub shortly after connecting to it in order to stay connected.
To make sure this isn't caused by the described behaviour I started streaming immediately after successfully connecting with PubSub. Unfortunately it made no difference, still an error.

I think I can rule out the network configuration because 

1) TwitchClient is working as expected
2) OnOpen and OnClose callbacks from PubSub are received

Am I perhaps missing something? 

The full code in case it helps:
https://github.com/damagefilter/damagebot4twitch

**Comment by swiftyspiffy** [comment]
In your OnConnected event, are you calling ListenToTopic and SendTopics?

**Comment by damagefilter** [comment]
Hello.

Sorry for my late reply and thanks for your quick one :)

I'm not calling any of the 2 methods.
Just updated to the latest 1.5.4 and I do have PubSub.sendTopics but not ListenToTopic().

But I gather from your response that I should probably do so.
So I'll go and figure that one out.

Thanks for your assistance so far :)

**Comment by swiftyspiffy** [comment]
Oops.

You want to call ListenTo{action_here} to listen to specific actions in your OnConnected event. Once you have listened to all the actions you want, then call sendTopics to send them to Twitch

**Comment by swiftyspiffy** [comment]
I'm going to go ahead and close this. Feel free to reopen as needed.
