### ISSUE TITLE
Reusing client issues.

### ISSUE THREAD

**Issue by VRequencyVisoR** [swiftyspiffy/TwitchLib#238]
Alright, so I'm working on a login system where I can use a client, connect to a channel, and then change the login credentials and reconnect. While doing so, I noticed that changing the ConnectionCredentials from the client after the initial creation, doesn't change the "TwitchUsername". In the ctor from the TwitchClient, it does set the TwitchUsername to _credentials.TwitchUsername, however in the 'set function from "ConnectionCredentials"' it doesn't. It just sets the _credentials. Leaving the actual "credentials.TwitchUsername" and "TwitchUsername" with different names.

Along with this, I noticed that if I used a valid OAuth, and used an username that doesn't belong to the OAuth, it won't call the OnChannelJoined event, but it won't call the OnIncorrectLogin event either. Leaving me with no actual callback of what's happening.

**Comment by swiftyspiffy** [comment]
I will look into these issues. Admittedly, the changing of credentials and accounts and reusing the client is a very rarely tested use scenario, so I'm not super surprised it's broke.

**Comment by RickRosendaal** [comment]
(Created that post on a wrong account) But thank you. A solution that I came up with for validating that the TwitchUsername is equal to the OAuth username, which seems to work perfectly for me is modifying the OnConnected code to the following:
![alt text](https://image.prntscr.com/image/LBeir-G9QOSGa35aUqJiKQ.png)
To fix the part where the TwitchUsername isn't modified when changing the ConnectionCredentials, I just added a line with `TwitchUsername = value.TwitchUsername;` like so:
![alt text](https://image.prntscr.com/image/TH-nB58AQOmYTz53M2g_9A.png)

**Comment by swiftyspiffy** [comment]
Quick update, I will get this and a few other bugs fixedf this weekend and get a new nuget package out.

**Comment by RickRosendaal** [comment]
Sounds awesome! Thank you!

**Comment by swiftyspiffy** [comment]
Alright, I added your recommended fixes. Let me know if it fixes it for ya.

**Comment by RickRosendaal** [comment]
The latest commit indeed fixed my issues!

**Comment by swiftyspiffy** [comment]
Awesome, will close this then.
