### ISSUE TITLE
Error when offset > 1600 in GetChannelFollowersAsync

### ISSUE THREAD

**Issue by Legion-5** [swiftyspiffy/TwitchLib#239]
Hello!
If I exceed the offset value in 1600, I get an error that the channel is not a numeric value or client is not installed
But the mistake is that the offset value can not exceed 1600. 
Twitch returns:
_{
    "error": "Bad Request",
    "status": 400,
    "message": "The parameter \"offset\" was malformed: the value must be less than or equal to 1600"
}_

Topic about issue: [justintv#647](https://github.com/justintv/Twitch-API/issues/647)
My solution is rework GetChannelFollowers something like:
      
            List<TwitchLib.Models.API.v5.Channels.ChannelFollow> followers = new 
            List<TwitchLib.Models.API.v5.Channels.ChannelFollow>();
            int totalFollowers;
            var firstBatch = await TwitchAPI.Channels.v5.GetChannelFollowers(channelId, 100);
            totalFollowers = firstBatch.Total;
            string cursor = firstBatch.Cursor;
            followers.AddRange(firstBatch.Follows);

            // math stuff
            int amount = firstBatch.Follows.Length;
            int leftOverFollowers = (totalFollowers - amount) % 100;
            int requiredRequests = (totalFollowers - amount - leftOverFollowers) / 100;

            System.Threading.Thread.Sleep(1000);
            for (int i = 0; i < requiredRequests; i++) {
                var requestedFollowers = await TwitchAPI.Channels.v5.GetChannelFollowers(channelId, 100, cursor: cursor);
                cursor = requestedFollowers.Cursor;
                followers.AddRange(requestedFollowers.Follows);

                // we should wait a second before performing another request per Twitch requirements
                System.Threading.Thread.Sleep(1000);
            }

            // get leftover subs
            var leftOverFollowersRequest = await TwitchAPI.Channels.v5.GetChannelFollowers(channelId, limit: leftOverFollowers, cursor: cursor);
            followers.AddRange(leftOverFollowersRequest.Follows);

            return followers;

**Comment by swiftyspiffy** [comment]
This is interesting. I was not aware of this requirement. Give me a bit of time and I'll commit a fix.

**Comment by swiftyspiffy** [comment]
As a side note, that function should actually be called GetAllChannelFollowersAsync, not GetChannelFollowersAsync. Oops.

**Comment by swiftyspiffy** [comment]
I tested that commit above (which has your fix in it) and it seems to work. Thanks :) I'll leave this open for you to confirm.

**Comment by Legion-5** [comment]
Yes, everything works well. Thank you.

**Comment by swiftyspiffy** [comment]
No worries, thanks for notifying me of this, I learned something.
