### ISSUE TITLE
Plans to add Client.GetUsers(bool state) or something similar?

### ISSUE THREAD

**Issue by Arefu** [swiftyspiffy/TwitchLib#24]
Just wondering if this is on any todo list

**Comment by swiftyspiffy** [comment]
Not sure I quite understand what you mean. Would  you be able to point to a link in the Twitch API documentation regarding this?

**Comment by Arefu** [comment]
https://discuss.dev.twitch.tv/t/url-for-chatters/2302

That I guess, I'm not to sure if you can get the state of users, but it would be nice if you can.

**Comment by igor523** [comment]
@Arefu, TwitchLib has TwitchApi with GetChatters method. I think, this is what you're looking for:

GetChatters(string channel) - Async function returns list of Chatter objects detailing each chatter in a channel

**Comment by Arefu** [comment]
Oh my, this I did not see. That can work for the time being, but is it possible at all to integrate this to the 
TwitchChatClient class so I can just go Client.GetChatters(Channel)?

**Comment by igor523** [comment]
@Arefu, well, it's POSSIBLE, but TwitchLib is trying to make things as they are in Twitch documentation. TwitchChatClient works with Twitch IRC, and nothing else. TwitchApi works waith common Twitch Api and nothing else. So, I don't think, that integrating API part in IRC class is good idea.

**Comment by Arefu** [comment]
Fair enough, I guess I'll just work with what I've got.

Thanks :).
