### ISSUE TITLE
InvalidCredentialException with correct AccessToken?

### ISSUE THREAD

**Issue by Extragracz** [swiftyspiffy/TwitchLib#240]
Hello.
First of all - I'd like to thank you for this amazing library :)

AFAIK - client_id is not required when you provide an access token, so that's what I do.
I got my token from your generator but here is my problem - whenever I try to set TwitchAPI.Settings.AccessToken to this token I get an InvalidCredentialException, even though I'm sure it is correct (I can send a TwitchAPI request with it from my browser).

Looks like I am doing something not the right way, I wouldn't be surprised, cause I'm a C# beginner.
Any help would be appreciated :)

**Comment by swiftyspiffy** [comment]
If you do add a client id, does it work? I'm interested to know. You can disable the check by doing something like:
```
TwitchLib.TwitchAPI.Validators.SkipAccessTokenValidation = true;
```

this will force the library to perform the request even if it thinks it wont work. Would be interested to see if it works for you with the skipped validation.

**Comment by Extragracz** [comment]
Thanks, looks like library requires ClientId. Without it set and with SkipAccessTokenValidation I was getting a scope exception. Now everything works, thanks once again :)

**Comment by M4sterZer0** [comment]
I've the same problem, but skip access token is only a temporary solution.
https://blog.twitch.tv/client-id-required-for-kraken-api-calls-afbb8e95f843
https://dev.twitch.tv/docs/v5/guides/using-the-twitch-api#translating-from-user-names-to-user-ids

**Comment by swiftyspiffy** [comment]
If you guys want to give the latest code a try, should resolve your problem, I hope.

**Comment by Extragracz** [comment]
Yep, seems like the problem is gone, I am able to successfully send a request without setting a ClientId,

**Comment by swiftyspiffy** [comment]
Awesome, will close this issue.
