### ISSUE TITLE
Attempting to join a non existent channel

### ISSUE THREAD

**Issue by RickRosendaal** [swiftyspiffy/TwitchLib#241]
When attempting to join a non existent channel using TwitchClient.JoinChannel(), there seems to be no callback which allows us to handle this issue.
It would be quite nice to have this implemented somehow. I implemented a solution for myself which does it's job perfectly. It would be nice to have this, or something similar to this implemented. I set everything up in a way so that these checks are optional and it shouldn't break any existing code.

Created a OnNonExistentChannelDetected event.
```
/// <summary>
/// Fires when the library detects that a channel does not exist after calling JoinChannel() with param 'validateChannelExistence' set to true.
/// </summary>
public event EventHandler<OnNonExistentChannelDetectedArgs> OnNonExistentChannelDetected;
```
Created the required OnNonExistentChannelDetectedArgs class for the event.
```
namespace TwitchLib.Events.Client
{
    #region using directives
    using System;
    #endregion
    /// <summary>Args representing on join channel failed event.</summary>
    public class OnNonExistentChannelDetectedArgs : EventArgs
    {
        /// <summary>Property representing the reason why the client couldn't join the channel.</summary>
        public string Reason;
    }
}
```
Added an extra parameter `bool validateChannelExistence = false` which is passed along to the JoinedChannel ctor. Can now throw an InvalidCredentialException.
```
/// <summary>
/// Join the Twitch IRC chat of <paramref name="channel"/>.
/// </summary>
/// <param name="channel">The channel to join.</param>
/// <param name="overrideCheck">Override a join check.</param>
/// <param name="validateChannelExistence">Whether to check if the channel actually exists or not before attempting to join. (Requires Client-Id)</param>
/// <exception cref="InvalidCredentialException">Throws InvalidCredentialException if Client-Id was not set while <paramref name="validateChannelExistence"/> was set to true.</exception>

public void JoinChannel(string channel, bool overrideCheck = false, bool validateChannelExistence = false)
{
	// Channel MUST be lower case
	channel = channel.ToLower();
	// Check to see if client is already in channel
	if (JoinedChannels.FirstOrDefault(x => x.Channel.ToLower() == channel && !overrideCheck) != null)
		return;
	if (validateChannelExistence && string.IsNullOrEmpty(TwitchAPI.Settings.ClientId))
		throw new InvalidCredentialException("Validating the channel existence requires a Client-Id. Set Client-Id by using TwitchAPI.Settings.ClientId = \"client_id_here\"");
	joinChannelQueue.Enqueue(new JoinedChannel(channel, validateChannelExistence));
	if (!currentlyJoiningChannels)
		queueingJoinCheck();
}
```
Added a property `ValidateChannelExistence` with an optional ctor argument.
```
namespace TwitchLib.Models.Client
{
    /// <summary>Class representing a joined channel.</summary>
    public class JoinedChannel
    {
        /// <summary>Object representing current state of channel (r9k, slow, etc).</summary>
        public ChannelState ChannelState { get; protected set; }
        /// <summary>The current channel the TwitcChatClient is connected to.</summary>
        public string Channel { get; protected set; }
        /// <summary>The most recent message received.</summary>
        public ChatMessage PreviousMessage { get; protected set; }
        /// <summary>Whether to check if the channel actually exists or not before attempting to join.</summary>
        internal bool ValidateChannelExistence { get; set; }

        /// <summary>JoinedChannel object constructor.</summary>
        public JoinedChannel(string channel, bool validateChannelExistence = false)
        {
            Channel = channel;
            ValidateChannelExistence = validateChannelExistence;
        }

        /// <summary>Handles a message</summary>
        public void HandleMessage(ChatMessage message)
        {
            PreviousMessage = message;
        }
    }
}
```
Modified the queueingJoinCheck to first validate the channel existence (if requested), before sending a JOIN request to Twitch. Also used the already existing 'channelToJoin' to add to the JoinedChannels, instead of creating a new instance like you have right now: `JoinedChannels.Add(new JoinedChannel(channelToJoin.Channel));`
```
private void queueingJoinCheck()
{
	if(joinChannelQueue.Count > 0)
	{
		currentlyJoiningChannels = true;
		JoinedChannel channelToJoin = joinChannelQueue.Dequeue();
		if (channelToJoin.ValidateChannelExistence && !channelIsValid(channelToJoin.Channel))
		{
			log($"{channelToJoin.Channel} is not a valid channel.");
			OnNonExistentChannelDetected?.Invoke(this, new OnNonExistentChannelDetectedArgs { Reason = $"{channelToJoin.Channel} is not a valid channel." });
			currentlyJoiningChannels = false;
			return;
		}
		log($"Joining channel: {channelToJoin.Channel}");
		_client.Send(Rfc2812.Join($"#{channelToJoin.Channel}"));
		JoinedChannels.Add(channelToJoin);
	}
	else
	{
		log("Finished channel joining queue.");
	}
}
```
The function to check if a channel is valid/exists.
```
private bool channelIsValid(string channelName)
{
	try
	{
		HttpWebRequest request = WebRequest.Create($"https://api.twitch.tv/kraken/channels/{channelName}?client_id={TwitchAPI.Settings.ClientId}") as HttpWebRequest;
		request.Method = "HEAD";
		HttpWebResponse response = request.GetResponse() as HttpWebResponse;
		response.Close();
		return (response.StatusCode == HttpStatusCode.OK);
	}
	catch
	{
		return false;
	}
}
```

**Comment by swiftyspiffy** [comment]
This looks good, thanks for bringing it to my attention, give me a day or two as I've been quite busy with stuff, but I'll add the commits with your recommended fixes.

**Comment by swiftyspiffy** [comment]
Want your input here if you don't mind. The potential problem here is that it's a valid use case for someone to try to connect using TwitchClient but not have a ClientId set in the TwitchAPI leading to the check failing unless a clientid has been set. The clientid should not be required if the programmer is looking to just use the TwitchClient.

**Comment by prom3theu5** [comment]
Tbh you could just add a timeout of like 3 seconds on receiving the MODE response for the channel.
Joining a valid channel you'd receive something like:

`<- :prom3theu5!prom3theu5@prom3theu5.tmi.twitch.tv JOIN #burkeblack
-> tmi.twitch.tv MODE #burkeblack
<- :prom3theu5.tmi.twitch.tv 353 prom3theu5 = #burkeblack :matt_thomas
<- :prom3theu5.tmi.twitch.tv 366 prom3theu5 #burkeblack :End of /NAMES list`

Where as on joining a channel that doesn't actually exist - you wouldn't get any response. It stops at:

`-> tmi.twitch.tv JOIN #prom3theu53232323232`

**Comment by swiftyspiffy** [comment]
I was kind of hoping we could avoid monitoring the messages, but I suppose it's really the only correct route to go. Will look into implementing it. Currently working on core nuget package.

**Comment by swiftyspiffy** [comment]
This has been implemented with the latest commits from Syzuna.
