### ISSUE TITLE
ClientId not being set

### ISSUE THREAD

**Issue by DuncanGarrettBWG** [swiftyspiffy/TwitchLib#244]
Hey there,
I'm trying to integrate TwitchLib with Unity 2017.1. TwitchClient seems to be fairly doable - I've gotten the basic chat functionality working and set up a bunch of things for that route. However I've been told that the client (on Twitch's side, not yours) is fairly unreliable and that I should use the API for getting various datapoints.

Trying to implement TwitchAPI has been an inexplicable nightmare. Unity outright ignores and doesn't report exceptions at all, which was weird in its own right. But 
`TwitchAPI.Settings.ClientId = "a_valid_client_id";`
does nothing.

```
try
{
    Debug.Log("Passed Client ID:" + clientID);
    TwitchAPI.Settings.ClientId = clientID;
    Debug.Log("Client ID:" + TwitchAPI.Settings.ClientId);
    TwitchLib.Models.API.v3.Channels.Channel channel = await TwitchAPI.Channels.v3.GetChannelByName(channelName);
    Debug.Log("Get channel by name returned: " + channel.DisplayName);
}
catch (System.Exception ex)
{
    Debug.Log(ex.Message);
}
```

returns the following:
```
Passed Client ID:8dsf6h78dsfhidufys78dfy9s7yf
Client ID:
All API calls require Client-Id or OAuth token. Set Client-Id by using SetClientId("client_id_here")
```
For reference, this is the second time I try to set the ClientId. I set the ClientId and OAuth token when the class is initialized as well.

I'm at a loss here - There's no exception, it just tosses the ClientId when I try to pass it.

**Comment by swiftyspiffy** [comment]
Hi. I did change some of the logic belonging to ClientId. Can you try reverting to version 1.5.4 and let me know if it works.

**Comment by swiftyspiffy** [comment]
I just tested it in the test application provided in the project and it seems to work:

![https://swfty.xyz/598GRD589](https://swfty.xyz/598GRD589)

**Comment by DuncanGarrettBWG** [comment]
Reverting TwitchLib appears to have corrupted the Unity project. Will get back to you when I've got it working again.

**Comment by swiftyspiffy** [comment]
ohhhh, sorry about that. Ya, it seems to work on 1.5.5. Let me reach out to the guy who wrote the guide and ask.

**Comment by DuncanGarrettBWG** [comment]
No worries, my own dumb fault for trying to do it recklessly. It looks like I was using an older version (1.5.3 or so) and just jumping forward caused problems. I got the project working again and the 1.5.4 version seems to work as intended. Thanks for the help!

**Comment by swiftyspiffy** [comment]
Yup, glad you got it to work!
