### ISSUE TITLE
Always getting "Token Issues"

### ISSUE THREAD

**Issue by D3thw0lf** [swiftyspiffy/TwitchLib#245]
Works the whole day but at some Point (for no reason) I get this error in Log
```
2017-08-07 01:14:01.9449 TRACE TwitchLib.Exceptions.API.InvalidCredentialException: The passed Access Token was not valid. To get an access token, go here:  https://twitchtokengenerator.com/
   bei TwitchLib.Internal.TwitchAPI.Shared.setAccessToken(String accessToken)
   bei TwitchLib.Internal.TwitchAPI.Shared.set_AccessToken(String value)
   bei TwitchLib.TwitchAPI.Settings.set_AccessToken(String value)
```

Code behind:
```c
                TwitchAPI.Settings.ClientId = "MyClientID";
                TwitchAPI.Settings.AccessToken = AppSettings.OAuthToken;
                var stream = await TwitchAPI.Streams.v5.GetStreamByUserAsync(AppSettings.LastChannelID);
                if (stream.Stream != null)
                {
                    ViewerCount.Text = Convert.ToString(stream.Stream.Viewers);
                }
```
This Code sets the Viewercount (for example: Viewers: 10) nothing less or more. :3 

As I said: The Viewercount and all the other stuff works for a very Long time and at some Point it breaks the application with the Access token warning. :/

I've put in every scope to make sure I've not missed one but same issue. (And yes, I generated with my own web script)

So I guess it's an issue with the Lib not with the token itself that's why I report this to you. Maybe I missed something then I would be glad if you can tell me what I've missed. :) 

As always:
Thanks for the help and great work. <3 ^w^

**Comment by swiftyspiffy** [comment]
This is interesting. For now you can disable the check via TwitchLib.TwitchAPI.Settings.Validators.SkipAccessTokenCheck = true;

I will look into this.

**Comment by swiftyspiffy** [comment]
I'm going to go ahead and close this.
