### ISSUE TITLE
Inconsistend UserId data types

### ISSUE THREAD

**Issue by Syzuna** [swiftyspiffy/TwitchLib#246]
Hey Swifty!

I just wanted to rework some stuff to rely on userIds bcs more and more ppl change their name and that is bad for a points system e.g.
But I now discovered that the data type the libary returns are inconsistent. 
E.g. in the Command Chat message its a string and in the whispercommand message its a long. 
I mean I can build around that but its still a bit weird

**Comment by swiftyspiffy** [comment]
Yup, it's kind of similar to the twitch api docs (which are also all screwed up). I'll get them fixed when I get some time.

**Comment by swiftyspiffy** [comment]
Should be fixed with that commit.
