### ISSUE TITLE
PubSub - ListenToChatModeratorActions using int for channelTwitchId

### ISSUE THREAD

**Issue by Mahsaap** [swiftyspiffy/TwitchLib#247]
All but one listen event is set to **int** instead of **string** and could be confusing to others.
Additionally the userID is **int** on the same line.
### TwitchPubSub.cs Line 289 
_public void ListenToChatModeratorActions(**int myTwitchId**, **int channelTwitchId**, string moderatorOAuth)
        {
            listenToTopic($"chat_moderator_actions.{myTwitchId}.{channelTwitchId}");
        }_

### TwitchPubSub.cs Line 298 
__public void ListenToBitsEvents(**string channelTwitchId**)
        {
            listenToTopic($"channel-bits-events-v1.{channelTwitchId}");
        }_

### TwitchPubSub.cs Line 307
_public void ListenToVideoPlayback(**string channelTwitchId**)
        {
            listenToTopic($"video-playback.{channelTwitchId}");
        }_

### TwitchPubSub.cs Line 316
_public void ListenToWhispers(**string channelTwitchId**)
        {
            listenToTopic($"whispers.{channelTwitchId}");
        }_

### TwitchPubSub.cs Line 325 
_public void ListenToSubscriptions(**string channelId**)
        {
            listenToTopic($"channel-subscribe-events-v1.{channelId}");
        }_

**Comment by swiftyspiffy** [comment]
Good catch on this. Will fix it in a few hours.

**Comment by Mahsaap** [comment]
;) np updated my name on here so you know who it is.

**Comment by swiftyspiffy** [comment]
Should be fixed now, let me know.

**Comment by swiftyspiffy** [comment]
Going to go ahead and close this, feel free to reopen as needed.
