### ISSUE TITLE
Looking for a Specific Event

### ISSUE THREAD

**Issue by PFCKrutonium** [swiftyspiffy/TwitchLib#25]
In this case, I am wondering if an event exists for when someone Follows the channel? If I am not mistaken, follows are announced in the Broadcasters Chat.

**Comment by swiftyspiffy** [comment]
I do not believe there is an event for when someone follows a channel. It is my understanding that applications ping the Twitch Follower API on an interval and retrieve the most recent 25/50/100 followers. They can then keep a cache of old followers, and compare against any new people in the recent follower list, and can announce them on stream.

You can use this library's TwitchApi GetTwitchFollowers() function to get the most recent followers (100 or less), and check every minute and compare and announce new follows.

**Comment by PFCKrutonium** [comment]
Ah okay, will do!

**Comment by swiftyspiffy** [comment]
I know you closed this, but that being said, I think a service in the library might be an interesting idea. The developer could specify the channel and the check interval, and then an event fires when the service detects new followers.

**Comment by PFCKrutonium** [comment]
I would love that - Should I re-open the issue?

**Comment by swiftyspiffy** [comment]
Yup, go for it. I'll work on it at some point, I have opened a couple issues on things I want to add, so this would be a good addition.

**Comment by swiftyspiffy** [comment]
I just created a Services directory and wrote a FollowerService and pushed those changes. I also added an example usage to the TwitchLibExample application.  I'll create a new version for NuGet here shortly. I'll close this perhaps tomorrow or the day early given no problems arise.

Cheers :)

**Comment by PFCKrutonium** [comment]
Cheers! On a related note, I am going to be making a basic bot in VB, would you be open to adding it as another example project?

**Comment by PFCKrutonium** [comment]
![For the LOL's btw](https://cloud.githubusercontent.com/assets/3945538/17122538/45cc4b36-52aa-11e6-9f0f-0986cac3148e.png)

**Comment by swiftyspiffy** [comment]
Sure, when you finish, message me, and I'll link it on the README :)

Oh ya, me and another guy had some issues with cyrillic characters earlier, but solved it using Encoding.Default, unfortunately it didn't fix Console applications it seems. Are you using the latest version of the library from NuGet or compiled from github?

**Comment by PFCKrutonium** [comment]
It's not an issue with your library, this is an issue with the console not supporting Unicode, so it just fucks off and does that.

**Comment by swiftyspiffy** [comment]
Gotcha. This seems to be resolved, I'll close for now :)
