### ISSUE TITLE
Streamer XYZ is online/offline request

### ISSUE THREAD

**Issue by D3thw0lf** [swiftyspiffy/TwitchLib#26]
I tried to fetch the online status of a streamer with the TwitchApi but it always shows (everyone...I tried some channels) "offline" (even in the example). Maybe this needs an update? :)

And another Question: Is the "TwitchApi.BroadcasterOnline" = Channel is Streaming or just "online" ? I'm a bit confused 'cause I try to grab the data to display a badge with "you're currently live" (or similar) as long as the channel is streaming.

I hope everything I've written here is clear enough. Sorry for my bad english ^^

Thanks in advance

**Comment by swiftyspiffy** [comment]
Hi, I'll look into this in a few hours. The call checks to see if their stream is active and online, not that they're necessarily "online", as that could mean a number of things.

**Comment by D3thw0lf** [comment]
Ok so TwitchApi.BroadcasterOnline is the call I need to check for if stream is live. Good to know. :)


Thanks for taking the time to look into this. <3 ^w^

**Comment by swiftyspiffy** [comment]
Sorry was tired when I made that last response.  Ya, TwitchApi.BroadcasterOnline should be what you're looking for. I'll close this now :)

**Comment by D3thw0lf** [comment]
But it's not working (even in example) :/ it always responds with "offline".

`if(await TwitchApi.BroadcasterOnline(this.appSettings.LastChannelName))
                    {
                        username_data.Foreground = new SolidColorBrush(Colors.Red);
                    }
                    else
                    {
                        username_data.Foreground = new SolidColorBrush(Colors.DeepSkyBlue);
                    }`

Am I'm doing something terrible wrong?

If online check is positive it should just change a color from "blue" to "red" for live y know? :3

**Comment by swiftyspiffy** [comment]
What is the channel your trying at the moment?

**Comment by D3thw0lf** [comment]
kaefgames_entertainment
or try
amarouk_rex (it's currently live)

**Comment by swiftyspiffy** [comment]
For now, make sure you're calling:

```TwitchApi.SetClientId("your twitch client id");```

Before calling BroadcasterOnline()

**Comment by D3thw0lf** [comment]
Ok I'll try that. If something wents wrong I'll let you know. :)

Thanks again for your support.

**Comment by swiftyspiffy** [comment]
I'll be fixing it though, the way  the broadcaster call works is that it catches any thrown exception as "FALSE", when InvalidCredentialException should be thrown all the way to the top developer indicating no client id.

This will be fixed, and FollowerService will be added and pushed to the NuGet listing here shortly :dancer:

Cheers

**Comment by D3thw0lf** [comment]
Nice. Keep up the good work. :heart_eyes:
