### ISSUE TITLE
client.TimeoutUser help

### ISSUE THREAD

**Issue by 15w34r0n3D4y** [swiftyspiffy/TwitchLib#260]
Hey!

Can someone help me with:

private void onMessageReceived(object sender, OnMessageReceivedArgs e) {
	if(e.ChatMessage.Message.Contains("badword"))
    	client.TimeoutUser(e.ChatMessage.Username, TimeSpan.FromMinutes(30), "Bad word! 30 minute timeout!");

I can't use "client.TimeoutUser"... How can i use "TimeoutUser" in onMessageReceived? Thank you for help.

**Comment by swiftyspiffy** [comment]
Off the top of my head, you have to use an extension. Something like:
```
using TwitchLib.Extensions.Client;
```

I'll check more later on when I get to my computer.

**Comment by 15w34r0n3D4y** [comment]
You are right! 

Thank you sir! :)

**Comment by swiftyspiffy** [comment]
Awesome, glad you got it working!
