### ISSUE TITLE
Client.OnNewFollower event - feature request

### ISSUE THREAD

**Issue by MathijsBesten** [swiftyspiffy/TwitchLib#263]
Is it possible to get a client."OnNewFollower" eventhelper, if somebody follows the channel?
We already got the "client.OnNewSubscriber" event.

**Comment by Syzuna** [comment]
there is a follower service extension. sadly twitch doesnt have an event/irc message for followers so the service extenstion someone wrote for this lib has to do it with a work around

**Comment by swiftyspiffy** [comment]
Syzuna is correct, Twitch does not make this information available on an event basis. Basically the FollowerService pings the channel followers API endpoint and then checks for any new users and raises an event when it detects them.

**Comment by Syzuna** [comment]
There will be a webhook for new follower tho with the new api although webhooks might be somewhat hard to handle on local machines

**Comment by MathijsBesten** [comment]
Thanks for the advice people!
