### ISSUE TITLE
OnBanArgs expose bannedUserId aka target_user_id

### ISSUE THREAD

**Issue by JabLuszko** [swiftyspiffy/TwitchLib#264]
Almost the same [I guess now (sic!) Twitch is moving from name-based to id-based] as 74cf3e9851f7f2bce3a9b77709acc104d4b2c046 but for banned users.
I'd rather log the userId (and maybe name, no reason to delete it now if it's still in pubsub message) than log username that they can change and render logs useless.

Cheers,

**Comment by JabLuszko** [comment]
If you think about it I guess it would be cool if we had target_user_id for every Moderator action from PubSub. Ban/unban/timeout/untimeout.

**Comment by swiftyspiffy** [comment]
Looking into this, pretty sure I did do it for unban, but not sure I ended up doing it for the rest.

**Comment by swiftyspiffy** [comment]
Alright, if you want to give those a glance, it should implement what you suggested above.

**Comment by JabLuszko** [comment]
That was fast! 👍
Will test in few hours, but looks good from commits.
