### ISSUE TITLE
IndexOutOfRangeException in Models\Client\Subscriber.cs

### ISSUE THREAD

**Issue by Vxrl** [swiftyspiffy/TwitchLib#265]
My program uses TwitchLib to monitor subscribers in a small channel, and once every 1–2 days (so one in every ~25 subscriptions) the program crashes with an unhandled IndexOutOfRangeException. This is because of [this line of Subscriber.cs](https://github.com/swiftyspiffy/TwitchLib/blob/master/TwitchLib/Models/Client/Subscriber.cs#L77). This code assumes that `badgeValue` contains `'/'`. So when `badgeValue` is empty (when the `section` is `"@badges="` and the `value` is `""`) an IndexOutOfRangeException occurs, because `badgeValue.Split('/')` is   an array of strings with only one element (`""`).

To fix this problem, change that line to these two lines:
```
if (badgeValue.Contains('/')) // Prevent IndexOutOfRangeException
    Badges.Add(new KeyValuePair<string, string>(badgeValue.Split('/')[0], badgeValue.Split('/')[1]));
```

**Comment by swiftyspiffy** [comment]
Good catch, will push this tonight or tomorrow!

**Comment by Vxrl** [comment]
It also exists in the netcore branch [here](https://github.com/swiftyspiffy/TwitchLib/blob/netcore/TwitchLib/Models/Client/Subscriber.cs#L78).

**Comment by prom3theu5** [comment]
Thanks I'll merge it from master once it's done :)

**Comment by swiftyspiffy** [comment]
Alright, that should fix your problem, let me know

**Comment by swiftyspiffy** [comment]
Will close this since it should be fixed.
