### ISSUE TITLE
Having issue with Logging

### ISSUE THREAD

**Issue by kiyoshi-kurosaki** [swiftyspiffy/TwitchLib#266]
Hello,
I turned the logging to false but nothing happens, it always output all received messages from the twitch server, what can i do to disable the logging of the connection, just need the onMessage output and not the other debug things, can you please tell me what's wrong, or is it a bug?

Regards

**Comment by swiftyspiffy** [comment]
Yes, looking into another issue and now this. Will get back to you shortly.

**Comment by swiftyspiffy** [comment]
Alright, that should fix your problem, I hope. Let me know :D

**Comment by kiyoshi-kurosaki** [comment]
So thanks the problem is gone :) i implemented a logging true/false, can be set in a config ^^
But another problem takes, after hours it appears, and need to be restarted,

Error message:
15.09.2017 03:11:26|Fatal|WebSocket.<startReceiving>b__175_2:0|WebSocketSharp.WebSocketException: The header of a frame cannot be read from the stream.
                             bei WebSocketSharp.WebSocketFrame.processHeader(Byte[] header)
                             bei WebSocketSharp.WebSocketFrame.<>c__DisplayClass73_0.<readHeaderAsync>b__0(Byte[] bytes)
                             bei WebSocketSharp.Ext.<>c__DisplayClass55_0.<ReadBytesAsync>b__0(IAsyncResult ar)

**Comment by swiftyspiffy** [comment]
I assume this is with pubsub, correct?

**Comment by kiyoshi-kurosaki** [comment]
The problem is, i dont know, it random appears :/

**Comment by swiftyspiffy** [comment]
In my experience, this error occurs as a result of Twitch forcing a disconnect on the client. It could be a result of the client failing to respond/send PING/PONG messages to Twitch, but it could also be a result of Twitch forcing a disconnect on their side. You might try catching that exception and then having the client reconnect. I will look into seeing if this can be done within the client itself.

**Comment by kiyoshi-kurosaki** [comment]
Okii wil be nice if you can help me to resolve the problem ^^
It needs to be online and nowmaly it PING/PONG message to be connected to twitch so i don't understand why twitch would force disconnect the client so if twitch forces it.
Sry for my bad english ^^

Regards

**Comment by swiftyspiffy** [comment]
Generally, Twitch doesn't disconnect clients. I think the only reason they would is if they are pushing updates to their servers or restarting their servers. Regardless, it is something the client /should/ handle automatically.

**Comment by swiftyspiffy** [comment]
Will close this since the main issue is resolved. Still looking into the ability for the client to detect the issue automatically.
