### ISSUE TITLE
Emotes

### ISSUE THREAD

**Issue by BubbaSWalter** [swiftyspiffy/TwitchLib#267]
So Currently I have it where when someone types it into chat that message appears a on a local webpage.  I was wondering if there is a function to swap the part of the message for a emote they use.  I was looking at the documentation and I saw that it should be possible but I could not figure out how.  attached I have included all my code that I believe to be relent on a hastebin link. https://hastebin.com/guyuzejama.cs

**Comment by swiftyspiffy** [comment]
Yes, there is a way to do it.
use `ChatMessage.EmoteSet` property.
The property is a model that contains a List of Emote models called `Emotes`. An Emote model contains `Id`, `Name`, `StartIndex`, `EndIndex`, `ImageUrl` properties. What you're interested in is the `StartIndex` (the index in the message string where the emote word starts) and `EndIndex` (the index where the emote ends in the message string). You'll want to replace this range of text with an image sourced from `ImageUrl`. And of course, set Name as the hover tip dialog if you wish, as it is the name of the emote itself.

**Comment by BubbaSWalter** [comment]
Do I have to include anymore extra using statements. I have tried both e.ChatMessage.EmoteSet.Emotes(); and e.ChatMessage.EmoteSet.Emotes.id();  or is there an example on how to call the Emote Model;

**Comment by swiftyspiffy** [comment]
You're using the properties like methods by adding () to them. To use the EmoteSet property, you'd do something like:
```csharp
foreach(var emote in e.ChatMessage.EmoteSet.Emotes) {
     var id = emote.Id;
}
```

**Comment by BubbaSWalter** [comment]
One Final question is there away to add in BTTV emote and FankerZ Emotes?

**Comment by BubbaSWalter** [comment]
How I was able to do the emote insertion
            foreach(var emote in e.ChatMessage.EmoteSet.Emotes)
            {
                var name = emote.Name;
                var start = emote.StartIndex;
                var url = emote.ImageUrl;

                ChatMessage = ChatMessage.Replace(name, " " + "<img  class=\"emote\" src=\"" +url +"\" + ></img>" + " ");

            }

**Comment by swiftyspiffy** [comment]
BTTV and FFZ emotes are currently unsupported with the master code (some changes are still required to get them to work again).

As far as your second question, what are you trying to emote insertion into? a textbox?

**Comment by BubbaSWalter** [comment]
I have them being inserted it to a local webpage. It currently does what I want it to do.

**Comment by swiftyspiffy** [comment]
Awesome :)
