### ISSUE TITLE
Subscriber.Months property is 0 for new subscribers

### ISSUE THREAD

**Issue by Vxrl** [swiftyspiffy/TwitchLib#269]
The "msg-param-months" parameter is only included in a resub notice, so when the [Subscriber constructor](https://github.com/swiftyspiffy/TwitchLib/blob/master/TwitchLib/Models/Client/Subscriber.cs#L63) parses the IRC string, the [Months field](https://github.com/swiftyspiffy/TwitchLib/blob/master/TwitchLib/Models/Client/Subscriber.cs#L37) is never changed from 0, the default for an `int`.

To fix this, change [this line](https://github.com/swiftyspiffy/TwitchLib/blob/master/TwitchLib/Models/Client/Subscriber.cs#L37) to
`public int Months { get; protected set; } = 1;`

**Comment by prom3theu5** [comment]
It is probably right to change this to 1, however at the same time it's (in my opinion) semantically incorrect to be utilising the Months property on a OnSubscription event. The only reason it's on the class is because the class is also shared and used by the OnResubscription event :)

**Comment by swiftyspiffy** [comment]
I agree with you guys that really months shouldn't be included in the OnSubscription event. That would mean we need another model and have the Months property removed. That is a possibility, or we can just set Months = 1 as you suggested. Thoughts?

**Comment by prom3theu5** [comment]
Implemented in new release
