### ISSUE TITLE
Checking users time in channel

### ISSUE THREAD

**Issue by arcanewater** [swiftyspiffy/TwitchLib#27]
Hey thanks for this great lib first! Also one question any idea on what base does "loyal bots" work? Do they just scan list like every 1 minute and give points or any other idea? I was also checking on following two methods OnViewerJoined and on OnViewerLeft if this would be better. Any ideas (i know its not really related to TwitchLib but thanks for any help)

**Comment by arcanewater** [comment]
Thanks! One more question i have txt and button which sends message as bot, but function onMessageReceived does not display this message, so i should just add it manually to chat windows when i press or any better idea?

**Comment by swiftyspiffy** [comment]
I believe there is a `onSentMessage` event that you might be able to subscribe to and when that fires, add that message to your text box. This ensures that wherever you send a message from in your program, it will always reflect in your program.

**Comment by arcanewater** [comment]
Yeah that worked, actually what the thing behind CheckForIllegalCrossThreadCalls ? I tryed to transfer now code to WPF and man i can get this working mostly because of threads.

**Comment by swiftyspiffy** [comment]
The `CheckForIllegalCrossThreads = false;` is a lazy way of delegating. I would not recommend using that line of code in anything production facing. 

The accepted answer here does a pretty good job of explaining why it exists: http://stackoverflow.com/questions/13345091/is-it-safe-just-to-set-checkforillegalcrossthreadcalls-to-false-to-avoid-cross-t

**Comment by swiftyspiffy** [comment]
Additionally, I'll go ahead and close this, as the issue seems to be resolved :)
