### ISSUE TITLE
Getting output even if Logging is disabled

### ISSUE THREAD

**Issue by DerpyDoom** [swiftyspiffy/TwitchLib#272]
Hey,

I wanted to disable the output of TwitchLib compleatly so i can see my own events in my Console.
But even if i disable Logging by triggering it to false, it still puts out the raw text of the irc server.

how can i fix this?

**Comment by kiyoshi-kurosaki** [comment]
This is issue normaly fixed weeks ago, have you updated the code from repo? ^^

**Comment by DerpyDoom** [comment]
No I only use it from NuGet, seems like it's still an old version that I'm using

**Comment by swiftyspiffy** [comment]
I will get a new version out this weekend 100%, just been super busy with real life stuff. Sorry about delays

**Comment by prom3theu5** [comment]
Fixed in current Release
