### ISSUE TITLE
IndexOutOfRangeException for Empty Message

### ISSUE THREAD

**Issue by Vxrl** [swiftyspiffy/TwitchLib#273]
Somehow someone sent a message with length 0.

From TwitchLib\Models\Client\ChatMessage.cs (netcore):
![](https://i.imgur.com/2hu5pqw.png)

To fix this, prepend `Message.Length > 0 &&` to the condition of the `if` statement on line 178 (netcore).

**Comment by prom3theu5** [comment]
I have seen these zero length messages too
Will patch tonight

**Comment by swiftyspiffy** [comment]
Recommended fix applied, feel free to reopen if the issue isn't solved.
