### ISSUE TITLE
IndexOutOfRangeException for message with 2 spaces in a row

### ISSUE THREAD

**Issue by Vxrl** [swiftyspiffy/TwitchLib#274]
Someone sent a message with two spaces in a row, so `message.Split(' ')` (`message` is the raw IRC message) contains a string with length 0. TwitchLib\Internal\Parsing\Chat.cs (netcore line 23) tries to check if the first character of this string is `'#'` without checking if the length of this string is 1 or greater.

![](https://i.imgur.com/l0uxxXi.png)

As far as I can tell, the `if (word[0] == '#')` isn't even necessary because the code still checks `if (word == $"#{channel}")`. So I think just removing this first `if` statement would fix the problem.

I recommend refactoring `getReadType` to:
```
public static string getReadType(string message, string channel)
{
    string[] splitByChannel = message.Split(new string[] { $" #{channel}" }, System.StringSplitOptions.None);
    if (splitByChannel.Length > 1) // If the message contains $" #{channel}"
        return splitByChannel[0].Split(' ').Last();

    string[] splitBySpace = message.Split(' ');
    if (splitBySpace.Length > 1 && splitBySpace[1] == "NOTICE")
        return "NOTICE";

    return null;
}
```

**Comment by prom3theu5** [comment]
Does this only occur when blank messages are sent?
They mustn’t be filtered out

Might be better to just check the array isn’t null with something like:

`
/// <summary>Indicates whether the specified array is null or has a length of zero.</summary>
/// <param name="array">The array to test.</param>
/// <returns>true if the array parameter is null or has a length of zero; otherwise, false.</returns>
public static bool IsNullOrEmpty(this Array array)
{
    return (array == null || array.Length == 0);
}
`

**Comment by Vxrl** [comment]
The message that caused this exception was not blank. There were two spaces between the second-to-last and last words.

**Comment by Vxrl** [comment]
This code should work:

```
public static string getReadType(string message, string channel)
{
    if (message.Contains($"#{channel}"))
    {
        string[] splitter = message.Split(new string[] { $" #{channel}" }, System.StringSplitOptions.None);

        return splitter[0].Split(' ').Last();
    }

    if (message.Split(' ').Length > 1 && message.Split(' ')[1] == "NOTICE")
        return "NOTICE";

    return null;
}
```

**Comment by swiftyspiffy** [comment]
Good catch on this, will push the fix shortly. Thank you.

**Comment by swiftyspiffy** [comment]
Feel free to reopen, but I applied your fix and it seems to work :D
