### ISSUE TITLE
No longer receive messages

### ISSUE THREAD

**Issue by Bziks** [swiftyspiffy/TwitchLib#275]
If I use TwitchClient and OnMessageReceived method, after long time (15-30 min) receiving messages are break. In log isn't message about disconnect.

![1](https://user-images.githubusercontent.com/9319018/31046145-4e6b30b2-a5fc-11e7-939e-d9145796b006.png)
![2](https://user-images.githubusercontent.com/9319018/31046146-4e6b7784-a5fc-11e7-9034-44fc07f2ec00.png)

**Comment by prom3theu5** [comment]
What kind of object is the list you are using. Is it  just a list or is it an observable collection / concurrentlist

Lists aren’t thread safe, and running each update like that in a new thread could cause you issues which would produce a system aggregate exception, which would not actually crash your application just cause the task to hang. 

Behind the scenes lots of things happen, including reallocating buffers and copying elements. That code will cause danger. Very simply, there are no atomic operations when adding to a list, at the least the "Length" property needs to be updates, and item needs to be put in at the right location, and (if there's a separate variable) the index needs to be updated. Multiple threads can trample over each other. And if a grow is required then there is lots more going on. If something is writing to a list nothing else should be reading or writing to it.

You should use lock or a Concurrent Collection of some kind

That’s if it isn’t a library issue. I haven’t seen that issue though :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Bziks** [comment]
So, I create clear project, without threads and other logic. You can see the project here - https://github.com/Bziks/TestTwitchChat
I use only TwitchLib and connect to channel and just reading messages. And all, more I do nothing.
I going to the channel and writing messages. These messages are written to the log. Then I wait 10-20 minutes and writing new message, and these message are don't written to the log. I think that is library problem, or I'm doing something wrong.

**Comment by swiftyspiffy** [comment]
Does OnMessageReceived still fire after that period of time, or does  nothing work after that period?

**Comment by Bziks** [comment]
I use only OnMessageReceived, for other logic I use api and it work fine. Therefore does not work only OnMessageReceived.

**Comment by swiftyspiffy** [comment]
I'm not sure if it'll fix it or not, but can you try the latest code? I just sent out a new package last night.

**Comment by swiftyspiffy** [comment]
Issue seems inactive.
