### ISSUE TITLE
Pubsub OnListenResponse Event doesnt fire

### ISSUE THREAD

**Issue by Syzuna** [swiftyspiffy/TwitchLib#276]
Hey Swifty,

another pubsub issue ^^
I subscribed to the OnConnect Event where I start listening to topics and the pubsub also delivers data on that topics but the OnListenResponse Event doesnt seem to fire for me bcs I dont get any success message in my logs from it

**Comment by swiftyspiffy** [comment]
Can I see your connect and event subscription code please

**Comment by Syzuna** [comment]
![connectcode](https://user-images.githubusercontent.com/22714301/31060325-e65e9c54-a711-11e7-835f-ed82b30b10c1.PNG)

![pubsub_eventsubscription](https://user-images.githubusercontent.com/22714301/31060326-ee64f740-a711-11e7-9ce2-d03f2655640e.PNG)

![pubsub_eventcode](https://user-images.githubusercontent.com/22714301/31060328-f11a63ee-a711-11e7-9cf5-aa8b5df5da19.PNG)

not the cleanest code bcs its more like "I need it to be done for now" but I works. the only thing that doesnt work is the OnListenResponse Event. The OnConnect fires fine and the data from the subscriptions is getting to my bot too

**Comment by swiftyspiffy** [comment]
I think, and I'm not 100%, but it *should* still be working even without OnListenResponse. I remember this issue, I was hitting it earlier. I think Twitch modified the success message. Try turning on logging and seeing the responses manually.

**Comment by Syzuna** [comment]
ye it works just wanted to bring the not firing event to your attention like I said earlier :D

**Comment by JabLuszko** [comment]
The reason why OnListenResponse never triggers is that because previousRequest object is always null, I guess it should be set in *SendTopics* - it was deleted here https://github.com/swiftyspiffy/TwitchLib/commit/0bf652740b0f97739b519cf277b260ed98a1408e#diff-2d8f176775522ad2bfe0345b416c6d78L240 when you introduced multi topic support and never put back

**Comment by swiftyspiffy** [comment]
Yup, good catch. Will correct this this weekend. Thanks :D

**Comment by Syzuna** [comment]
Fixed in latest version! :)
