### ISSUE TITLE
PubSub ListenToVideoPlayback / null in VideoPlayback

### ISSUE THREAD

**Issue by JabLuszko** [swiftyspiffy/TwitchLib#277]
Hi,

ListenToVideoPlayback needs a channel name, not a channel Id. I would also suggest putting some comment in documentation that is not "official" part of Twitch API and can change without any kind of notice.

```
 public void ListenToVideoPlayback(string channelName)
        {
            listenToTopic($"video-playback.{channelName}");
        }
```

and when I actually make that work there is a null crash in VideoPlayback.cs 
```
 if (Type != VideoPlaybackType.ViewCount)
                PlayDelay = int.Parse(json.SelectToken("play_delay").ToString());
            else
                Viewers = int.Parse(json.SelectToken("viewers").ToString());
```
play_delay token exists only on *stream-up* type this code triggers on *stream-down* too.
I guess you want something like
```
 if (Type == VideoPlaybackType.StreamUp)
                PlayDelay = int.Parse(json.SelectToken("play_delay").ToString());
  else if (Type == ViewCount)
                Viewers = int.Parse(json.SelectToken("viewers").ToString());
```
and consequence changes to OnStreamDownArgs event

**Comment by swiftyspiffy** [comment]
Thanks for this, and yes it does need some improved documentation. Will fix both this weekend.

**Comment by Syzuna** [comment]
Hey I know its a late response but try it again with the latest version. It should contain all your mentions and should fix your problems.

If not dont hesistate to tell us what went wrong :)

**Comment by swiftyspiffy** [comment]
This issue seems dead, going to go ahead and close it.
