### ISSUE TITLE
LiveMonitorService improvements

### ISSUE THREAD

**Issue by LuckyNoS7evin** [swiftyspiffy/TwitchLib#278]
Been looking at the live monitor service... I think it's a good basis for something, but think we can do better

I have, a requirement to monitor multiple channels however the issue with the service is, 

a) you have to have at least one channel before starting the service
b) it checks each channel individually rather than in batches of 100
c) it only returns the channel id in the is online event

What I would like to do is
i) check in batches
ii) add remove channels from the "list" of channels you're checking
iii) return the stream object to the online event
iv) not require at least one channel before starting the service
v) have a public getter for getting the current status of the streams
vi) store the stream object, this will mean you have an updated version of the object on each check interval(edited)

**Comment by prom3theu5** [comment]
I'll get these enhancements done for the weekend :)

**Comment by prom3theu5** [comment]
This is now part of the project - Thanks
