### ISSUE TITLE
Getting full list of Followers (more than 100 followers)

### ISSUE THREAD

**Issue by igor523** [swiftyspiffy/TwitchLib#28]
Hello!

To get full list of followers we need to know _cursor value, that comes with response, so we can request next page. But, well, I can't find where GetTwitchFollowers returns this value. And, as I read in Twitch API docs, this is the only way to request full list (>100 followers). Is there anything I've missed in your lib?

Thanks!

**Comment by swiftyspiffy** [comment]
Very good point, it currently does not return the cursor value. I will add this tonight and push it into a new NuGet version tomorrow along with your host detection, and a GetUptime bug.

**Comment by swiftyspiffy** [comment]
I just pushed code that should fix this. GetTwitchFollowers() now returns an object that houses the followers, cursor, and total follower count. Perhaps you can get back to me about that.

**Comment by swiftyspiffy** [comment]
I'm going to close this, as the issue seems to be resolved :)
