### ISSUE TITLE
OnModeratorsReceived == null

### ISSUE THREAD

**Issue by Moerty** [swiftyspiffy/TwitchLib#284]
Hey man!

I have a class called "chat" that listen to various events. one of them is "OnModeratorsReceived".
```
public Chat() {
    Messages = new ObservableCollection<Models.Chat.Messages>();
    Viewers = new ObservableCollection<Models.Chat.Viewers>();
    Messages.CollectionChanged += MessagesCountCheck;
    Core.AivaClient.Instance.AivaTwitchClient.OnMessageReceived += ChatMessageReceived;
    Core.AivaClient.Instance.AivaTwitchClient.OnModeratorsReceived += ModeratorsReceived;
    Core.AivaClient.Instance.AivaTwitchClient.OnUserLeft += RemoveViewerFromViewers;
    Core.Client.Internal.Users.OnNewUserFound += OnNewUserFound;
}
```

And now my problem:
you see, i subscribed first to OnModeratorsReceived and then on OnNewUserFound.
and when OnNewUserFound fires, i check if the user is a moderator and then i get an exception cause the event is 'null', triggered from TwitchClient.cs line 497:
```
if (OnModeratorsReceived == null)
    throw new EventNotHandled("OnModeratorsReceived");
```

yeah, i dont know why this event is null, maybe you?
hope to hear from you with any ideas, im out if it...

should i implement a delay to check it? maybe something is to slow in the background?

**Comment by swiftyspiffy** [comment]
Is it possible you're connecting/joining channel/getting moderators before you are subscribing to the events? I just tested with my bot and it seems to work correctly.

**Comment by Moerty** [comment]
Yeah, i think i have a workaround.
