### ISSUE TITLE
NET.2.0 not working

### ISSUE THREAD

**Issue by kiyoshi-kurosaki** [swiftyspiffy/TwitchLib#286]
So i just tried to update TwitchLib, but i not working with the Error:
System.IO.FileNotFoundException: File or Assembly "netstandard" not found or something like that, and i can't add netstandard reference.

Where is the problem, i hope you can help.

Regards Kiyoshi

**Comment by prom3theu5** [comment]
If you are using the git repo and building yourself, you need .Net Core 2.0.2 Installed and at least patch 15.3 for Visual Studio 2017.

You also have to target a minimum runtime version of .net 4.6.1, and add a nuget reference to NetStandard.Library

**Comment by kiyoshi-kurosaki** [comment]
No i'm downloaded from github ^^ but i can't change the netcore, it' locked by the project :/

**Comment by prom3theu5** [comment]
You don't need to change to .net core
You simply have to target a minimum framework version of .Net Framework 4.6.1

**Comment by kiyoshi-kurosaki** [comment]
Yes i changed the framework minimum but not working and displayed the error System.IO.FileNotFoundException: File or Assembly "netstandard" not found or something like that,

**Comment by prom3theu5** [comment]
If you have Visual Studio 2017 minimum patch 15.3 (current live version is 15.4) it will automatically handle this, as thats when .net standard 2.0 was introduced.
If not - add a nuget reference to NetStandard.Library

Take a look at the PubSub test app in the testing folder - that is a .net framework 4.6.1 application

**Comment by prom3theu5** [comment]
Also - if you are building the Repo version, you will need .Net Standard 2.0 sdk locally on your machine.
[](https://www.microsoft.com/net/download/core)

With the SDK installed locally, and visual studio running on the latest version, this is the result of referencing the library in a brand new Windows Classic Desktop WinForms 4.6.1 application:

![sample](https://user-images.githubusercontent.com/1518610/32143815-6b5d5ae4-bca7-11e7-9b98-a09bd9e05546.gif)

**Comment by kiyoshi-kurosaki** [comment]
I dont need to add a application to the project but just compile the TwitchLib.dll to use it on my own project :/

**Comment by prom3theu5** [comment]
Then you dont need to change anything

Install .Net Standard 2.0 SDK (which will be needed to build a .net standard library)
You can get that from the link I posted above.

Once that is installed - if you don't want to update your visual studio, simply open a command prompt in the TwitchLib\TwitchLib folder, and run:

```
dotnet restore
dotnet build
```

You'll have your class library in the bin folder.

**Comment by prom3theu5** [comment]
I'll ask swifty to get a new version up on Nuget when he gets a chance

**Comment by swiftyspiffy** [comment]
Hi guys. I just pushed out 1.5.8 twitchlib package to nuget which should be what you're looking for.

**Comment by kiyoshi-kurosaki** [comment]
So now i think the problem is fixed, but when you update the source here on github, i need to import the update from nuget?

Regards Kiyo

**Comment by prom3theu5** [comment]
You have a choice really
Github is updated frequently, once enough feature changes have occurred to warrant a new subversion, or critical hotfixes have been applied, then a new package will be pushed to NuGet, which will show as an update in Visual Studio

**Comment by kiyoshi-kurosaki** [comment]
Also i don't need to update from github, but it's enough to update from nuget if update is available.

**Comment by prom3theu5** [comment]
It's fine to stick with nuget - unless you want "bleeding edge" most current library changes.
the Nuget package is updated very often though.
