### ISSUE TITLE
API Issue

### ISSUE THREAD

**Issue by BubbaSWalter** [swiftyspiffy/TwitchLib#289]
So I was having an issue with Twitch Lib API 

The Error was 
Exception thrown: 'TwitchLib.Exceptions.API.BadResourceException' in mscorlib.dll
An exception of type 'TwitchLib.Exceptions.API.BadResourceException' occurred in mscorlib.dll but was not handled in user code
The resource you tried to access was not valid.

        async void funStreamSubs()
        {
            //List<TwitchLib.Models.API.v5.Subscriptions.Subscription> allSubs = await TwitchAPI.Channels.v5.GetAllSubscribers("wizardsrwe");
            List<TwitchLib.Models.API.v5.Subscriptions.Subscription> allsubs = await TwitchAPI.Channels.v5.GetAllSubscribersAsync("wizardsrwe");
            lbSubList.DataSource = allsubs;
        }

        private void Form1_Load(object sender, EventArgs e)
        {
            TwitchAPI.Settings.AccessToken = TwitchToken;
            Console.WriteLine(TwitchAPI.Settings.AccessToken);
            funUserList();
            funStreamSubs();
        }

**Comment by BubbaSWalter** [comment]
Opps my bad. I forgot v5 requires the channel ID not Channel name.  Does v5 or TwitchLib API have a way to translate a channel name to an id number?

**Comment by MagiusRerecros** [comment]
You can use the TwitchAPI.Users.v5.GetUserByNameAsync method to retrieve a User object based on a name (string), which has an ID property.

**Comment by MagiusRerecros** [comment]
If it helps, this is the method I use for retrieving ID's from usernames:

```
public async Task<string> GetIDByNameAsync(string username)
{
    string id;

    try
    {
        var user = await TwitchAPI.Users.v5.GetUserByNameAsync(username);

        id = user.Matches[0].Id;
    }
    catch
    {
        id = string.Empty;
    }

    return id;
}
```
