### ISSUE TITLE
Possible to use Proxy?

### ISSUE THREAD

**Issue by DerpyDoom** [swiftyspiffy/TwitchLib#291]
Hello, It's me again :D

Is it possible to use Proxies? Since I'm building a project which has a lot of connections to twitch chats,
each streamer in my database gets his own connection. And since it's only allowed to connect 10 times per second it is quite slow.

Thaths why I would like to use a proxy, or multiple proxies to fasten up my project.

**Comment by swiftyspiffy** [comment]
I'm a bit conflicted on this one. It is relatively simple to implement I think for API, Client, and PubSub and there are clear use cases of this being a legit feature as you've mentioned as well as load balancing related. However, I can't help but think that this would make creating massive chat spamming bots really easy, almost too easy to create. Thoughts?

**Comment by DerpyDoom** [comment]
Well that's not what I intented to make, my project joins the channels anonymously so it can't talk to the chat but read it. 

I want to experiment with MongoDB and BigData so i'm counting the lines per second and put it in the database for the streamers that are in my database.

since the streamer list ist quite big it takes ages to connect to all of them, thats why i wanted to use a proxy

(Sorry for my bad explanation, i'm not really good in english :P)

**Comment by swiftyspiffy** [comment]
Fair enough, I'll look into implementing this, this weekend.

**Comment by swiftyspiffy** [comment]
This has been implemented :)
