### ISSUE TITLE
Video upload issues

### ISSUE THREAD

**Issue by croxxx** [swiftyspiffy/TwitchLib#295]
While trying to use TwitchLib for a simple console application that uploads videos to Twitch I came across a problem. When browsing through the code to find the cause for that I noticed two other things in `uploadVideoParts(...)` that need to be taken a look at.

#### 1. Uploads time out on slow internet connections
My upload is a whopping 60 kBytes/second which causes the connection opened to upload a video fragment to timeout. In my opinion a customizable timeout should be presented as an option to the user to account for such slow upload speeds.

#### 2. The entire video file is read into memory at once
https://github.com/swiftyspiffy/TwitchLib/blob/a75a218eb610d38992b1de95eca37d5bda47cd22/TwitchLib/Api/Sections/Videos.cs#L225
After checking the file size the library proceeds with loading the entire file into memory. This will be a problem for large files (remember the API limit of 10 GB). An alternative would be using a FileStream and reading segments from it.

#### 3. The segmentation process cuts off the last 24MB of a file
https://github.com/swiftyspiffy/TwitchLib/blob/a75a218eb610d38992b1de95eca37d5bda47cd22/TwitchLib/Api/Sections/Videos.cs#L231
After examining the code used to segment the video file I noticed that the for loop misses 1 iteration. Reason for this is `parts` not taking the last part into account. This results in the last 24 MB of the file being cut off. I have tested this with a 35 second long 25MB big file. The resulting video on Twitch is one second long. This can be solved by adding 1 to the number.
Alternatively I imagine one could also move the code for the last part out of the loop and execute it afterwards.
Another option might be using a while loop that exits once `FileStream.Read()` returns 0 as per [the documentation][1].

[1]: https://msdn.microsoft.com/en-us/library/system.io.filestream.read(v=vs.110).aspx

**Comment by swiftyspiffy** [comment]
Good catch with these, I had not considered memory or slower connections when writing this code, so I was a bit naive in those respects. I agree with the changes. Thanks!

**Comment by swiftyspiffy** [comment]
Merged your fixes in which I think should resolve the problem. Thanks again :)

**Comment by croxxx** [comment]
Thanks for merging the changes. My pull request solves the segmentaton and memory problems.
It does however not affect behaviour regarding slow upload speeds. It might be useful to provide more information to the user here, for example using something like a `ApiTimeoutException`. Currently the exception thrown only says "A Task has been cancelled", if I remember correctly.

**Comment by swiftyspiffy** [comment]
I will look into this, my time is a bit constrained so there's abit of a backlog to get through, but I'll definitely add this at some point.
