### ISSUE TITLE
Crash when getting the current uptime of a channel

### ISSUE THREAD

**Issue by PFCKrutonium** [swiftyspiffy/TwitchLib#30]
System.NullReferenceException was unhandled
Message: An unhandled exception of type 'System.NullReferenceException' occurred in mscorlib.dll
Additional information: Object reference not set to an instance of an object.

```
        If e.Command = "uptimee" Then
            If e.ChatMessage.ModFlag Then
                Dim uptime As TimeSpan = Await TwitchApi.GetUptime(Authentication.twitchChannel)
                ChatClient.SendMessage((String.Format("uptime: {0} days, {1} hours, {2} minutes, {3} seconds", uptime.Days, uptime.Hours, uptime.Minutes, uptime.Seconds)))
            End If
        End If
```
This is based on your code, and the crash itself is not in my code. Any ideas?

**Comment by swiftyspiffy** [comment]
The reason is because you are trying to get the uptime of a channel that is not currently live, I think. I have just now pushed code that will instead return uptime of 0, instead of throwing a nullref exception.  The new code will likely go out in a NuGet version tonight or tomorrow.

**Comment by swiftyspiffy** [comment]
This should be resolved, I'll go ahead and close it :)

**Comment by PFCKrutonium** [comment]
I was testing it against a live channel though :/ I'll test it again though.

**Comment by swiftyspiffy** [comment]
That's odd. Can you try running the latest github code?
