### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by BubbaSWalter** [swiftyspiffy/TwitchLib#300]
Is there a way to check most recent follower and when someone new follows?

**Comment by swiftyspiffy** [comment]
For getting recent followers, there’s an example in the README on how to do it. For getting live follows, you’ll need to use a webhook, and for that you’ll need a server to receive the calls from Twitch. Alternatively you can use FollowerService in the library, but you’ll have a delay from both the library (30 seconds) and Twitch itself (1-5 minutes?).
