### ISSUE TITLE
When building TwitchLib project I only get the TwitchLib.dll no Newtonsoft.Json.dll or websocket-sharp.dll

### ISSUE THREAD

**Issue by WesleyThompson** [swiftyspiffy/TwitchLib#301]
Hey there, might be a dummy issue. I was following the Unity instructions [here](https://github.com/swiftyspiffy/TwitchLib/blob/master/unity.md). I got to step 2 where I build the TwitchLib solution, however, it only created the TwitchLib.dll.

I assumed maybe the doc was out of date and so I just finished the rest of the doc's instructions. I'm still missing assembly references though and am unable to use any TwitchLib functionality.

Am I missing something stupid or is this an actual issue?

**Comment by swiftyspiffy** [comment]
Yes, this problem has been reported a few times. Looking into it. A temp fix is just to add those packages via NuGet and that should fix your problem.

**Comment by WesleyThompson** [comment]
I did that and it didn't work. Just TwitchLib.dll up in there. If it helps any here's the output from my build:
`Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
1>------ Build started: Project: TwitchLib, Configuration: Release Any CPU ------
1>TwitchLib -> C:\Users\watdrb\Desktop\TwitchLib-master\TwitchLib\bin\Release\netstandard2.0\TwitchLib.dll
1>Successfully created package 'C:\Users\watdrb\Desktop\TwitchLib-master\TwitchLib\bin\Release\TwitchLib.1.5.8.nupkg'.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
`

**Comment by swiftyspiffy** [comment]
This should be fixed, feel free to reopen if it is not.

**Comment by vaindil** [comment]
@swiftyspiffy I'm having this issue when I target `netstandard2.0`. The project builds from the command line just fine with `dotnet build -c Release -f netstandard2.0`, but the extra files are not included and I can't run my solution on .NET Core as a result.

**Comment by prom3theu5** [comment]
You need to use
`dotnet publish` to output dependencies instead of build

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vaindil** [comment]
Wow, I forgot to put this in my comment, sorry. I did try that, but even if I reference the Newtonsoft.Json.dll that's generated by `dotnet publish` my code still complains that it's not found. I have Copy Local set to true, and TwitchLib itself works just fine, but it won't pick up the dependencies even when directly referenced.
