### ISSUE TITLE
Receiving Chatmessages is very slow lately

### ISSUE THREAD

**Issue by D3thw0lf** [swiftyspiffy/TwitchLib#302]
It seems like that the receiving of new Messages can take ages since a couple of Releases now. I'm not 100% sure if it's twitch or the lib bc I'm using the same Code (to process Chat Messages) and for mixer.com it works just 100% fine (realtime Chat receiving).

Example:
Twitch: https://youtu.be/ZbOvCwfFVPU
Mixer: https://youtu.be/dsJTI3uvqBg

Code behind to process the Chat Messages against my class:

```c
                        var items = new List<ChatModel>
                        {
                            new ChatModel
                            {
                                UserColor = "#2EFE2E",
                                UserAvatar = avatar,
                                ShowUserAvatar = AppSettings.ThemeCustomShowChatAvatars,
                                UserName = e.ChatMessage.Username,
                                ChatTime = time,
                                ChatMessage = e.ChatMessage.Message
                            }
                        };
                        Manager.Instance.Chat.Items.Add(items);
```

**Comment by D3thw0lf** [comment]
Hmn seems like it's rly something on my end. Very confusing that this is happening. Keeping you updated if I can resolve my issue.

**Comment by D3thw0lf** [comment]
ok I guess I got it now ... sorry for disturbing ... had to priorize some calls before go through them through my class.

**Comment by swiftyspiffy** [comment]
All good, glad you got it figured out :D
