### ISSUE TITLE
OnModeratorsReceived not fired if there's no moderator

### ISSUE THREAD

**Issue by der-andy** [swiftyspiffy/TwitchLib#303]
When my bot joined a channel, I invoke `GetChannelModerators` to check whether my bot is a mod. The problem is that the `OnModeratorsReceived` event isn't fired if there's no mod at all. I see the notice in the log, but no event. I would expect the event to be fired with an empty list.

**Comment by swiftyspiffy** [comment]
I agree with you. Will leave this open until I have a chance to implement it.

**Comment by Syzuna** [comment]
The IRC message for no mods in that channel is: There are no moderators of this room.

**Comment by swiftyspiffy** [comment]
Feel free to reopen this if needed.
