### ISSUE TITLE
Request: /raid detection

### ISSUE THREAD

**Issue by D3thw0lf** [swiftyspiffy/TwitchLib#306]
Would be great to have something like "ongetraided" like we already have for new subscriptions/follows in the lib to give away for example 500 Points as a bot or whatever you want to do if this happens. :)

**Example: Notice sent when a channel is raided.**
> @badges=turbo/1;color=#9ACD32;display-name=TestChannel;emotes=;id=3d830f12-795c-447d-af3c-ea05e40fbddb;login=testchannel;mod=0;**msg-id=raid**;msg-param-displayName=TestChannel;msg-param-login=testchannel;msg-param-viewerCount=15;room-id=56379257;subscriber=0;system-msg=15\sraiders\sfrom\sTestChannel\shave\sjoined\n!;tmi-sent-ts=1507246572675;tmi-sent-ts=1507246572675;turbo=1;user-id=123456;user-type= :tmi.twitch.tv USERNOTICE #othertestchanne

I've copied the example from here: https://dev.twitch.tv/docs/irc

I don't know if it's possible to get the list of everyone in that raid but if so this would be an awesome Addition. :)

**Comment by swiftyspiffy** [comment]
Check the OnRaidNotification :)

**Comment by D3thw0lf** [comment]
Aww geez thanks a lot. Haven't seen that yet. <3

**Comment by D3thw0lf** [comment]
Is the example missing?

**Comment by swiftyspiffy** [comment]
No problem :D . Will close this now.
