### ISSUE TITLE
TwitchAPI.Settings cannot be accessed

### ISSUE THREAD

**Issue by yunghze** [swiftyspiffy/TwitchLib#309]
Hi, I'm trying to integrate the library into a Unity program and somehow I am unable to set the TwitchAPI.Settings as it is returning me an error, stating that an object reference is required for the non-static field, method, or property.

Could you let me know if there is a fix for this?

**Comment by Syzuna** [comment]
The TwitchApi isnt a static class anymore. it now needs an instance to be created to be used.
This was made to make it DI capable for the new .net core work flow.

**Comment by yunghze** [comment]
I see. So how do I pass my client ID and oauth token in?

**Comment by Syzuna** [comment]
you can do that in the constructor like TwitchApi api = new TwitchApi(clientId, oauth);

**Comment by Syzuna** [comment]
or you can do it like you would do it in the old version once you have an instance

**Comment by yunghze** [comment]
I see. I need to try it, because I did that, and I'm getting some errors. It may be unrelated. Thanks for the help!

**Comment by Syzuna** [comment]
You're welcome ;)

**Comment by yunghze** [comment]
Sorry, one last question. Then how do you pass the access token over to the client instance?

**Comment by yunghze** [comment]
Thank for your help Syzuna! I'm closing the thread.

**Comment by Syzuna** [comment]
Did you find an answer on the client question? wasnt home and didnt have time to answer on phone. Wanted to do it now but it looks like you found an answer already ^^

**Comment by yunghze** [comment]
Yeah, the guide I was following was slightly outdated. So I explored a little and managed to get it to connect.

**Comment by swiftyspiffy** [comment]
Glad you got it figured out :)
