### ISSUE TITLE
Users.v5.GetUsersByNameAsync() design inconsistency

### ISSUE THREAD

**Issue by hepherino** [swiftyspiffy/TwitchLib#315]
Users.v5.GetUsersByNameAsync() executes a method which was designed for Helix.

Re: https://raw.githubusercontent.com/swiftyspiffy/TwitchLib/master/TwitchLib/Api/TwitchAPI.cs
Relevant Code: https://puu.sh/ytYv4/f1227f881b.png

v5 requires ?login=name (for 1)
and ?login=name,x,y,z (comma separated)

Currently, it only pulls the last name specified.

Example:

https://api.twitch.tv/kraken/users?login=heph,3v
vs
https://api.twitch.tv/kraken/users?login=heph&login=3v

Obviously this wont be an issue once Helix takes over, but v5 will be around until Dec 31, 2018.

**Comment by Syzuna** [comment]
There is nothing wrong with this code. the comma seperated list of logins gets passed in as a comma seperated string into the post method from the Users.v5.GetUsersByNameAsync()

Ref: https://github.com/swiftyspiffy/TwitchLib/blob/master/TwitchLib/Api/Sections/Users.cs

`            #region GetUsersByName
            public async Task<Models.API.v5.Users.Users> GetUsersByNameAsync(List<string> usernames)
            {
                if (usernames == null || usernames.Count == 0) { throw new Exceptions.API.BadParameterException("The username list is not valid. It is not allowed to be null or empty."); }
                List<KeyValuePair<string, string>> getParams = new List<KeyValuePair<string, string>>() { new KeyValuePair<string, string>("login", string.Join(",", usernames)) };
                return await Api.GetGenericAsync<Models.API.v5.Users.Users>($"https://api.twitch.tv/kraken/users", getParams, null, ApiVersion.v5).ConfigureAwait(false);
            }
#endregion`

**Comment by Syzuna** [comment]
so its only one get param with login=xyz,zxy,yzx

**Comment by swiftyspiffy** [comment]
That is correct @Syzuna . When I was looking at this earlier I was only seeing the code snippet and then imagining why that might be a problem. Forgot that a CSV is passed in as a get parameter and now it looks good. Will scan over this for any inconsistencies in other methods.

**Comment by swiftyspiffy** [comment]
Will close this now, feel free to reopen.
