### ISSUE TITLE
Fetching list of videos fails if no video id is given

### ISSUE THREAD

**Issue by croxxx** [swiftyspiffy/TwitchLib#316]
## Issue
While trying to fetch a list of videos for a certain channel I came across an issue in TwitchLib.
If you only specify a `userId`, calls to `GetVideoAsync` in the Helix API fail.

## Reproducing and workaround
Calling the API endpoint with the following code after correctly initializing the library results in an exception.
```csharp
var res = api.Videos.helix.GetVideoAsync(userId: channelId);
```
This can be prevented if an empty list is given as the `videoIds` parameter as follows:
```csharp
var res = api.Videos.helix.GetVideoAsync(videoIds: new List<string>(), userId: channelId);
```

## Expected behaviour
The Twitch documentation [allows only specifying a `userId`][1]:
```
Each request must specify one or more video ids, one user_id, or one game_id.
```

## Proposed Fix
The code failing can be found in [TwitchLib/TwitchLib/Api/Sections/Videos.cs][2] where the count of video IDs is used once without being checked for null.
```csharp
if(videoIds.Count == 0)
```
The problem could be solved by using the same checks as other parts of the method:
```csharp
if(videoIds == null || videoIds.Count == 0)
```

[1]: https://dev.twitch.tv/docs/api/reference#get-videos
[2]: https://github.com/swiftyspiffy/TwitchLib/blob/31176f71f90849bd504b810eb4b8683653a633f1/TwitchLib/Api/Sections/Videos.cs#L262

**Comment by swiftyspiffy** [comment]
Will look into this. Thanks for the nicely formatted issue :)

**Comment by swiftyspiffy** [comment]
Sorry about the delay, this should be fixed now. Feel free to reopen as necessary.
