### ISSUE TITLE
Is there a way to Limit SendMessage via Api?

### ISSUE THREAD

**Issue by DerpyDoom** [swiftyspiffy/TwitchLib#32]
Hey.

Is there a way to limit the client so it doesn't get banned from twitch chat?

**Comment by swiftyspiffy** [comment]
Not at the moment, but I can add that tomorrow. :)

**Comment by DerpyDoom** [comment]
that would be an awesome feature, i'm a little bit concerned about my bot account that's why i asked :P Awesome library by the way! Keep working on it :+1:

**Comment by swiftyspiffy** [comment]
It's done :) Check the example project for implementation details. Basically, you'll just assign it to the client as such:
`chatClient.MessageThrottler = new MessageThrottler(200, TimeSpan.FromMinutes(3));`

The above example would limit the client to sending 200 messages per 3 minutes, the duration starting on when the first message is sent. I'll close this issue, but feel free to respond if need be!
