### ISSUE TITLE
GetChattersAsync - Not async?

### ISSUE THREAD

**Issue by GlobalHive** [swiftyspiffy/TwitchLib#320]
The function which gets the chatters isn't async or i guess it not since if it gets to run my program freezes...

Code
`List<TwitchLib.Models.API.Undocumented.Chatters.ChatterFormatted> chatter = await api.Undocumented.GetChattersAsync(CHANNEL_NAME);`

**Comment by swiftyspiffy** [comment]
Checking on this now.

**Comment by swiftyspiffy** [comment]
Sorry about the delay. It does look like it's an async call. Here's the actual call:
https://github.com/swiftyspiffy/TwitchLib/blob/c6a3ad541313ba8a4306c1b5759c0bf4cf1cbdbc/TwitchLib/Api/Sections/Undocumented.cs#L91

**Comment by swiftyspiffy** [comment]
Going to go ahead and close this, feel free to reopen as necessary.
