### ISSUE TITLE
Some events going through parsing as "unaccounted" after a client reconnect

### ISSUE THREAD

**Issue by Syzuna** [swiftyspiffy/TwitchLib#322]
As discussed shortly in Discord already some events go through parsing as "unaccounted" after a client reconnect.

I will append the logs already posted in the discord for better visibility.

`[Info] '' [TwitchLib, 1.5.9.0] Received: @badges=broadcaster/1;color=#B22222;display-name=Syzuna;emotes=;id=eb07c43b-7926-4dc7-96cf-19dc7dd53736;mod=0;room-id=102943601;subscriber=0;tmi-sent-ts=1513378400545;turbo=0;user-id=102943601;user-type= :syzuna!syzuna@syzuna.tmi.twitch.tv PRIVMSG #syzuna :!test`

`[Info] '' [TwitchLib, 1.5.9.0] Unaccounted for: @badges=broadcaster/1;color=#B22222;display-name=Syzuna;emotes=;id=eb07c43b-7926-4dc7-96cf-19dc7dd53736;mod=0;room-id=102943601;subscriber=0;tmi-sent-ts=1513378400545;turbo=0;user-id=102943601;user-type= :syzuna!syzuna@syzuna.tmi.twitch.tv PRIVMSG #syzuna :!test`

`[Info] '' [TwitchLib, 1.5.9.0] Received: @badges=broadcaster/1;color=#B22222;display-name=Syzuna;emotes=;id=eb07c43b-7926-4dc7-96cf-19dc7dd53736;mod=0;room-id=102943601;subscriber=0;tmi-sent-ts=1513378400545;turbo=0;user-id=102943601;user-type= :syzuna!syzuna@syzuna.tmi.twitch.tv PRIVMSG #syzuna :!test`

`[Info] '' [TwitchLib, 1.5.9.0] Unaccounted for: @badges=broadcaster/1;color=#B22222;display-name=Syzuna;emotes=;id=eb07c43b-7926-4dc7-96cf-19dc7dd53736;mod=0;room-id=102943601;subscriber=0;tmi-sent-ts=1513378400545;turbo=0;user-id=102943601;user-type= :syzuna!syzuna@syzuna.tmi.twitch.tv PRIVMSG #syzuna :!test`

`[Info] '' [TwitchLib, 1.5.9.0] Received: :syzuna_bot!syzuna_bot@syzuna_bot.tmi.twitch.tv JOIN #syzuna`

`[Info] '' [TwitchLib, 1.5.9.0] Unaccounted for: :syzuna_bot!syzuna_bot@syzuna_bot.tmi.twitch.tv JOIN #syzuna`

**Comment by Syzuna** [comment]
somehow only happens after a refresh? setted up a command to reconnect and it works well even after.

I am kinda helpless there bcs it makes no sense to me

**Comment by swiftyspiffy** [comment]
What do you mean a refresh?

Also, if I were to guess the issue, it'd be that when a reconnect happens, there's a variable that is set/modified that is used in chatmessage detection parsing .

Will look into this later.

**Comment by Syzuna** [comment]
token refresh. I refresh my access tokens after an invalid login bcs that is what twitch recommends
