### ISSUE TITLE
Is it possible for OnMessageRecieve to get messages sent with TwitchClient.SendMessage() ?

### ISSUE THREAD

**Issue by Amyyyyyyyyyy** [swiftyspiffy/TwitchLib#323]
It seems to get Messages sent by the same Twitch account via the Web chat fine, but won't recieve messages sent from itself. Is it possible to enable that?

**Comment by swiftyspiffy** [comment]
So, Twitch doesn’t send data to the client when messages are sent via the client. What you can do is use the OnMessageSent which the library fires when the the library sends a message. The properties are created by the library itself (and not based on data Twitch received).

**Comment by swiftyspiffy** [comment]
Going to close this, feel free to reopen as necessary.
