### ISSUE TITLE
Client Chat Throttler prevent send messages

### ISSUE THREAD

**Issue by ArthurFSharp** [swiftyspiffy/TwitchLib#328]
Hello,

I'm trying to limitting messages sends by bot using ChatThrottler property og TwitchClient object like this : 

`TwitchClient client = new TwitchClient(credentials, "channel_name", logging: true);
client.ChatThrottler = new TwitchLib.Services.MessageThrottler(client, 20, TimeSpan.FromSeconds(30));`

Here for example, i'm limitting to 20 messages from the bot all 30 secondes. 

but when i added the second line, the bot can't send any message anymore.

**Comment by swiftyspiffy** [comment]
Looking into this.

**Comment by Syzuna** [comment]
you need to start the Queue with client.ChatThrottler.StartQueue()

the best point to do this is in the OnConnect imo

**Comment by ArthurFSharp** [comment]
Oh ok ty @Syzuna . I could actually see that in the Program.cs example of the .NET Core project. 
Thanks for your help !

**Comment by swiftyspiffy** [comment]
Sorry about the delay, got side tracked shortly after writing the previous comment. Glad Syzuna was able to help you out. :D
