### ISSUE TITLE
Follow Webhook URL needs additonal Parameter (PR Included)

### ISSUE THREAD

**Issue by Syzuna** [swiftyspiffy/TwitchLib#334]
As announced in the TwitchDev TwitchApp server the follow webhook url changed a bit.
The old url is only deprecated and would still work for a month or 2 but rather change it earlier than later.

DISCLAIMER: New URL callback data has a diffrent data schema to be consistent with the api data schema

PR: #333

**Comment by swiftyspiffy** [comment]
This was merged :)
