### ISSUE TITLE
Where is "FollowersOnlyOn" ?

### ISSUE THREAD

**Issue by Moerty** [swiftyspiffy/TwitchLib#336]
Hey man,

I can't find the opposite of "FollowersOnlyOff".
Where can I set that only followers are able to write in the chat?

**Comment by Syzuna** [comment]
Like you can see here he copy pasted to fast without renaming Kappa

https://github.com/swiftyspiffy/TwitchLib/blob/master/TwitchLib/Extensions/Client/FollowersOnlyExt.cs

**Comment by Syzuna** [comment]
Fixed method name in PR #337

**Comment by swiftyspiffy** [comment]
Thanks guys!
