### ISSUE TITLE
Current stream game

### ISSUE THREAD

**Issue by sprunk97** [swiftyspiffy/TwitchLib#338]
Hi there. Im trying to get current game to put it to the !uptime but seems like something has changed since this thread: https://github.com/swiftyspiffy/TwitchLib/issues/106

How can i initializate Stream object by using channelId or channelName? If i get it right, TwitchLib.Models.API.v5.Streams.Stream object still works properly and after initialization i will only have to write something like stream.Game;
By the way if im trying to find some solves like in previous one, there is converting problem appears like Stream cannt be convert to StreamByUser etc.

**Comment by swiftyspiffy** [comment]
Hi!

Indeed, things have changed :)
Try:
```csharp
TwitchLib.TwitchAPI api = new TwitchAPI("clientid", "oauth");
var stream = await api.Streams.v5.GetStreamByUser("userid");

string msg = $"{channel} has been streaming for {(DateTime.Now - stream.Stream.CreatedAt).ToString()} and they've been playing {stream.Stream.Game}.";
```

This was off the top of my head, there might be some small syntax issues.

**Comment by sprunk97** [comment]
Thank's a lot, this worked for me (sorry, part of the code wont get into case):
`
        public async void uptimeThread(object callerNickname)
        {

            String username = Convert.ToString(callerNickname);
            User[] userList = twitchApi.Users.v5.GetUserByNameAsync(textBox2.Text).Result.Matches;
            var userId = userList[0].Id;
            var stream = await twitchApi.Streams.v5.GetStreamByUserAsync(userId);
            HHmmss = getUptime(userId)?.Hours.ToString() + ":" + getUptime(userId)?.Minutes.ToString() + ":" + getUptime(userId)?.Seconds.ToString();

            client.SendMessage(" Стрим идет уже - " + HHmmss + ". Игра - " + stream.Stream.Game);

            logBox.Text = logBox.Text + HHmm + " << Current game is " + stream.Stream.Game + " >>" + "\r\n";
        }

        public TimeSpan? getUptime(String userId)
        {
            return twitchApi.Streams.v5.GetUptimeAsync(userId).Result;
        }
`


I will handle with formatting of date later, idk why TimeSpan wont format by ToString("HH:mm:ss") and any variations of it. I took this code with TimeSpan? from HardlyDifficult. 
One thing more, any else command like !pc or something works jus in time it called by someone in chat but when person calls !uptime it takes bot ~5 seconds to answer back, Though there is no any delay such as thread.sleep(); Is it just a specificity of using async/await or something else?

**Comment by swiftyspiffy** [comment]
Looking at your code, you're making like five Twitch API calls everytime !uptime is used. This would cause some delay in response and isn't very efficient.
To cut down on some calls, I'd recommend making a few changes:

1. You should cache your userid so that you don't need to call GetUserByNameAsync everytime. Perhaps call it once after textbox2.text is set, and then store it in an accessible variable that you can use later.
2. If you are looking to just get the hours, minutes, and seconds, you don't need to call the API again to get this. Do something like:
```csharp
TimeSpan uptime = getUptime(stream.Stream.CreatedAt);
string HHmmss = uptime.Hours.Tostring() + ":" + uptime.Minutes.ToString() + ":" + uptime.Seconds.ToString();

public TimeSpan getUptime(DateTime dt) {
        return DateTime.Now - dt;
}
```

**Comment by sprunk97** [comment]
Yes, thats helped me. I thought about solutions like this one but you boost me alot. Now it works as fast as it works in moobot. Thx

**Comment by swiftyspiffy** [comment]
Awesome! Glad I could help :)
