### ISSUE TITLE
Example not aviable for UserState (Other Class)

### ISSUE THREAD

**Issue by D3thw0lf** [swiftyspiffy/TwitchLib#34]
Hey! It's me again. ;)

Is there any example for this? I just want to grab Color of Chatter and check if he/she is mod and/or broadcaster to add icon infront of their names (like normal chat on twitch.tv does).

Would appreciate a small example like that (if you have time for that). :+1: 

Thanks again.

**Comment by D3thw0lf** [comment]
Got it. Is there a way to detect that Channel is Broadcaster? There's a "ModFlag" but I can't see any "BroadcasterFlag" or is it just called otherwise? Thanks in advance. :)

**Comment by igor523** [comment]
Message.Username == TwitchChatClient.Username, maybe?

**Comment by swiftyspiffy** [comment]
I don't believe there a broadcaster flag at the moment. I can add one tonight though.

**Comment by D3thw0lf** [comment]
Got it with e.ChatMessage.DisplayName == e.ChatMessage.Channel :)

**Comment by swiftyspiffy** [comment]
I would use .Username not .DisplayName, since some people don't have a set DisplayName

**Comment by igor523** [comment]
Good to know :)
Maybe you're right, swiftyspiffy, about adding this flag, could be useful

**Comment by D3thw0lf** [comment]
I guess twitch.tv sets display name default to username (is it possible to change dat name?) because it worked since I used it (for now longer than 4 Months with every user in chat or using my program) :3

**Comment by swiftyspiffy** [comment]
I had an issue with my bot when it was connected to massive channels with 100,000+ viewers where occasionally someone wouldn't have a DisplayName, it'd be empty, which is why I resort to Username. If you are interested in the casing (upper vs lower case), then I'd use DisplayName.

**Comment by swiftyspiffy** [comment]
I added IsBroadcaster and UserType Broadcaster enum, which is also set, so there's two built in ways to check if the message came from the broadcaster :dancer: 

Issue seems to be resolved, I'll close this now.

**Comment by D3thw0lf** [comment]
Nice! Thank you. :)
