### ISSUE TITLE
Adding API V5 undocumented Comments endpoint?

### ISSUE THREAD

**Issue by DumpsterDoofus** [swiftyspiffy/TwitchLib#345]
Twitch's V5 API has an undocumented endpoint `https://api.twitch.tv/v5/videos/{id}/comments` to retrieve comments on past streams. Would anyone be interested if I submitted a pull request to add support for it? I've been using the endpoint to download chat for old videos so I can display chat as subtitles on VLC, but I'm sure other people can find other fun uses.

Also, does anyone know if the current ("Helix", aka v6) Twitch API supports downloading comments on past streams? I haven't seen anything in their documentation.

**Comment by LuckyNoS7evin** [comment]
go ahead with the PR, the more the merrier.

In terms of Helix, not as of yet!

**Comment by DumpsterDoofus** [comment]
This will be added in https://github.com/swiftyspiffy/TwitchLib/pull/346.

**Comment by swiftyspiffy** [comment]
Ya, this sounds like an awesome undocumented endpoint to add.

**Comment by swiftyspiffy** [comment]
Merged, thanks!
