### ISSUE TITLE
Helix API GET Videos model is missing pagination

### ISSUE THREAD

**Issue by DumpsterDoofus** [swiftyspiffy/TwitchLib#347]
The endpoint GET https://api.twitch.tv/helix/videos returns a pagination relation when there is more than 1 page of results, for example:

```
{
	"data" : [{
			"id" : "152158955",
			"user_id" : "8683614",
			"title" : "OoT Low% MST (22 item) in 3:15:09",
			"description" : "low% mst explanation https://pastebin.com/4qp1yHhX",
			"created_at" : "2017-06-16T01:55:50Z",
			"published_at" : "2017-06-16T01:55:50Z",
			"url" : "https://www.twitch.tv/videos/152158955",
			"thumbnail_url" : "https://static-cdn.jtvnw.net/s3_vods/6aaf92e374ea66412188_zfg1_25517224432_663497019//thumb/thumb152158955-%{width}x%{height}.jpg",
			"viewable" : "public",
			"view_count" : 1008,
			"language" : "en",
			"type" : "highlight",
			"duration" : "3h17m20s"
		}, 
                {... many more videos...}
	],
	"pagination" : {
		"cursor" : "eyJiIjp7Ik9mZnNldCI6MjB9LCJhIjp7Ik9mZnNldCI6NjB9fQ"
	}
}

```

However, the `TwitchLib.Models.API.Helix.Videos.GetVideos.GetVideosResponse` model doesn't include the pagination. As a result, it's impossible to get subsequent pages of results, since the cursor for the next page is discarded during deserialization.

I think the [Twitch API documentation](https://dev.twitch.tv/docs/api/reference#get-videos) is at fault for using a bad example. It documents the `before` and `after` cursors, but their example (which only returns 1 page of results) doesn't include the pagination required to actually use them.

If no one objects, I'll file a pull request to fix this (will be a pretty small addition).

Also, I'm noticing that the `duration` property (which is documented) is missing from `TwitchLib.Models.API.Helix.Videos.GetVideos.Video`. And there are three undocumented properties (`url`,  `viewable`, and `type`) returned in actual responses that are also missing. What's your policy on adding missing documented vs missing undocumented fields? My gut reaction is to add only the documented properties, since the undocumented ones may be subject to breaking change.

**Comment by DumpsterDoofus** [comment]
Created proposal at https://github.com/swiftyspiffy/TwitchLib/pull/348.

**Comment by swiftyspiffy** [comment]
Sorry about my delay, left a comment on the PR.

**Comment by swiftyspiffy** [comment]
Merged, thanks!
