### ISSUE TITLE
Helix GET videos logic bug around optional fields

### ISSUE THREAD

**Issue by DumpsterDoofus** [swiftyspiffy/TwitchLib#349]
In https://github.com/swiftyspiffy/TwitchLib/blob/a876415a3e0cb8c83cb70a6502785cb3be08daf4/TwitchLib/Api/Sections/Videos.cs#L262 there appears to be a logic bug; it's supposed to add the optional fields if a `user_id` or `game_id` is provided, but not if video IDs are provided (see [docs](https://dev.twitch.tv/docs/api/reference#get-videos)). However, it's doing the opposite, which means optional fields get discarded when searching by `game_id` or `user_id`, and erroneously included when searching by video IDs.

I noticed this while testing manually and inspecting outbound traffic with Fiddler. It was discarding my optional fields when searching by `user_id`. For example, `api.Videos.helix.GetVideoAsync(userId: "8683614", type:VideoType.Highlight)` will ignore the `VideoType.Highlight`. Here's a screenshot of the bug:

![capture](https://user-images.githubusercontent.com/6626631/35374598-6c756a0c-0158-11e8-83ed-4c6d6a9358ae.PNG)

I think the correct statement should be 
```
                if(videoIds == null || videoIds.Count == 0)
```

or better yet

```
                if(userId != null || gameId != null)
```

Does this seem right? If so, I can file a PR.

**Comment by Syzuna** [comment]
` if(videoIds == null || videoIds.Count == 0)`

This looks about right and is a good catch! 
The helix code is still relative new and not well tested bcs of limited use cases and bcs of not many ppl using helix yet.

And yes PRs are always welcome if you can fix a bug yourself 👍

**Comment by DumpsterDoofus** [comment]
Created proposal at https://github.com/swiftyspiffy/TwitchLib/pull/350.

**Comment by swiftyspiffy** [comment]
Left a comment on the PR.

**Comment by swiftyspiffy** [comment]
Merged, thanks!
