### ISSUE TITLE
Automatic bot use timeout?

### ISSUE THREAD

**Issue by Rumaruka** [swiftyspiffy/TwitchLib#355]
Hello swiftyspiffy, I'll use your lib the first time.
And I have questions

Can bot use timeout and bans commands ?

**Comment by Syzuna** [comment]
Yes they can do that. 

The necessary Extension Methods for the TwitchClient class are located here: 
https://github.com/swiftyspiffy/TwitchLib/tree/master/TwitchLib/Extensions/Client

**Comment by Rumaruka** [comment]
Thanks, Im close :3
