### ISSUE TITLE
PubSub Problem, pubsub is null

### ISSUE THREAD

**Issue by Mitsukiii** [swiftyspiffy/TwitchLib#357]
Something seems wrong on my Code:

I get always a Exception pubSub is null on the    pubSub.ListenToBitsEvents part.

```

                client = new TwitchClient(credentials, TwitchInfo.Channelname, logging: false);
                client.OnLog += Client_OnLog;
                client.OnConnectionError += Client_OnConnectionError;
                client.OnMessageReceived += Client_OnMessageReceived;
                client.OnWhisperReceived += Client_OnWhisperReceived;
                client.OnUserJoined += Client_OnUserJoined;
                client.OnNewSubscriber += Client_OnNewSubscriber;
                client.OnReSubscriber += Client_OnResubscriber;
                client.OnUserBanned += OnBannedUser;
                  client.Connect();

TwitchPubSub pubSub = new TwitchPubSub(true);
pubSub.OnPubSubServiceConnected += onPubSubConnected;
pubSub.OnListenResponse += OnListenResponse;
pubSub.OnBitsReceived += OnBitsReceived;
pubSub.Connect();

  private void onPubSubConnected(object sender, EventArgs e)
        {
           Console.WriteLine("PubSub Connected");
                pubSub.ListenToBitsEvents("AccountID/ChannelID");
          
            }

        private void OnListenResponse(object sender, OnListenResponseArgs e)
        {
            if (e.Successful)
            {
                Console.WriteLine($"Successfully verified listening to topic: {e.Topic}");
            }
            else
            {
                Console.WriteLine($"Failed to listen! Error: {e.Response.Error}");
            }
        }

  private void OnBitsReceived(object sender, OnBitsReceivedArgs e)
 {
client.SendMessage($"Just received { e.BitsUsed} bits from { e.Username}. That brings their total to { e.TotalBitsUsed} bits!");
}

```

**Comment by Mahsaap** [comment]
did you forget pubsub.Connect();
i don't see it in that snippet

**Comment by Syzuna** [comment]
He is Calling it somewhere. Bcs he is Calling the Listen method in the Connect Event

**Comment by Mitsukiii** [comment]
forgot to Add the Connect in the Issue, but yes i connect.

**Comment by Mahsaap** [comment]
makes sense. have you double checked you account ID and o-auth. I can see that returning null if incorrect.
or your pubsub instance is out of scope (looking at that is shouldn't be)

**Comment by Syzuna** [comment]
This is strange tho.. if pubsub is null that means that it was disposed somehow. I am only on Phone atm will look into this later. Already 2:40 am here :/

**Comment by Mitsukiii** [comment]
the pubsub part ist right under the TwitchClient part.
Pubsub only want the ChannelID, oauth doesnt seems to be required.

**Comment by Mahsaap** [comment]
ok, can you hastebin the whole code, without tokens. see exactly how you have it set up?

**Comment by Mitsukiii** [comment]
this is basically all what i have, Edited First Post.

**Comment by Mahsaap** [comment]
if `TwitchPubSub pubSub = new TwitchPubSub(true);`
is in a method, you need `TwitchPubSub pubSub;` outside of it. otherwise your event cant grab it.

**Comment by Mitsukiii** [comment]
still the same,

it still says its Connected, but never Listen to a Response,

![image](https://user-images.githubusercontent.com/28743231/35657302-156b6cb2-06fc-11e8-860a-42b5ffdac1b3.png)

**Comment by swiftyspiffy** [comment]
Can you set a break point on ListenToBitsEvents and see if it hits it or not. If it does, dive down and see if you can see if it seems to execute correctly.

**Comment by Mitsukiii** [comment]
i just moved the .ListentoBitsEvents outside of the void, it doesnt break anymore, but it still dont Listen.
maybe im wrong and the AccountID != ChannelID ? Ex. pubSub.ListenToBitsEvents("158750XXX");

**Comment by Mahsaap** [comment]
channel has name and ID, account id is your bots id. 
https://github.com/swiftyspiffy/TwitchLib/blob/c6a3ad541313ba8a4306c1b5759c0bf4cf1cbdbc/TwitchLib/Api/Sections/Channels.cs
is where the calls are to get the channel, and you can get the id from there. i wish there was easier way.

**Comment by Mitsukiii** [comment]
Im gonna take a look later, its 3:30 Am here, need to take a nap. Thank u alot. I will reply in some hours.

**Comment by Mahsaap** [comment]
GL

**Comment by Syzuna** [comment]
After the Listen you Need to Call SendTopics

**Comment by Mitsukiii** [comment]
i tried this now:

  public async void Pubsubreconnect()
        {
            
            TwitchPubSub pubSub = new TwitchPubSub(true);
            pubSub.OnPubSubServiceConnected += onPubSubConnected;
            pubSub.OnListenResponse += OnListenResponse;
            pubSub.OnBitsReceived += OnBitsReceived;
            pubSub.OnTimeout += OnTimeout;
            var channel = await api.Channels.v3.GetChannelByNameAsync("channelname");

            //Console.WriteLine(channel.Id.ToString());

            if (Pubsubconnected)
            {
                pubSub.Disconnect();
                pubSub.Connect();
                pubSub.ListenToBitsEvents(channel.Id.ToString());
                pubSub.ListenToSubscriptions(channel.Id.ToString());
                pubSub.SendTopics("token");
                Pubsubconnected = true;
            }
            else
            {

                Pubsubconnected = true;
                pubSub.ListenToBitsEvents(channel.Id.ToString());
                pubSub.ListenToSubscriptions(channel.Id.ToString());
                pubSub.Connect();
                pubSub.SendTopics("token");

            }
            Thread.Sleep(100);
        }

now i get this Error: "You must send data by websocket after websocket is opened"

**Comment by Syzuna** [comment]
first pls move the variables out of your method. you will get object lifecycles and Garbage Collection problems like that. second never use async void but async Task

**Comment by Syzuna** [comment]
also do the 
```
            pubSub.ListenToBitsEvents(channel.Id.ToString());
            pubSub.ListenToSubscriptions(channel.Id.ToString());
            pubSub.Connect();
```

in the OnPubSubConnected event callback to be sure that the connection to the pubsub server is open

**Comment by Mitsukiii** [comment]
```
      internal void Connect()
        {

                client = new TwitchClient(credentials, TwitchInfo.Channelname, logging: false);
                client.OnLog += Client_OnLog;
                client.OnConnectionError += Client_OnConnectionError;
                client.OnMessageReceived += Client_OnMessageReceived;
                client.OnWhisperReceived += Client_OnWhisperReceived;
                client.OnUserJoined += Client_OnUserJoined;
                client.OnNewSubscriber += Client_OnNewSubscriber;
                client.OnReSubscriber += Client_OnResubscriber;
                client.OnUserBanned += OnBannedUser;
                
                client.Connect();

                TwitchPubSub pubSub = new TwitchPubSub(true);
                pubSub.OnPubSubServiceConnected += onPubSubConnected;
                pubSub.OnListenResponse += OnListenResponse;
                pubSub.OnBitsReceived += OnBitsReceived;
                pubSub.OnTimeout += OnTimeout;
                Test();
                pubSub.Connect();
            }

      private async Task Test()
        {
            var channel = await api.Channels.v3.GetChannelByNameAsync("channelname");
            Console.WriteLine(channel.Id.ToString());
            pubSub.ListenToBitsEvents(channel.Id.ToString());
            pubSub.ListenToSubscriptions(channel.Id.ToString());
            pubSub.SendTopics();
        }

  private void OnTimeout(object sender, OnTimeoutArgs e)
        {
            Console.WriteLine(e.TimedoutUser + " Timeouted by " + e.TimedoutBy);
        }

        private void onPubSubConnected(object sender, EventArgs e)
        {
           Console.WriteLine("PubSub Connected");
        }


        private void OnListenResponse(object sender, OnListenResponseArgs e)
        {
            if (e.Successful)
            {
                Console.WriteLine($"Successfully verified listening to topic: {e.Topic}");
            }
            else
            {
                Console.WriteLine($"Failed to listen! Error: {e.Response.Error}");
            }
        }

```

Output:

only it is Connected, never trigger OnListenResponse.

**Comment by Syzuna** [comment]
Try this

I assume that client and pubsub variables are declared in a class global way

`      internal void Connect()
        {
                client = new TwitchClient(credentials, TwitchInfo.Channelname, logging: false);
                client.OnLog += Client_OnLog;
                client.OnConnectionError += Client_OnConnectionError;
                client.OnMessageReceived += Client_OnMessageReceived;
                client.OnWhisperReceived += Client_OnWhisperReceived;
                client.OnUserJoined += Client_OnUserJoined;
                client.OnNewSubscriber += Client_OnNewSubscriber;
                client.OnReSubscriber += Client_OnResubscriber;
                client.OnUserBanned += OnBannedUser;
                
                client.Connect();

                pubSub = new TwitchPubSub(true);
                pubSub.OnPubSubServiceConnected += onPubSubConnected;
                pubSub.OnListenResponse += OnListenResponse;
                pubSub.OnBitsReceived += OnBitsReceived;
                pubSub.OnTimeout += OnTimeout;
                pubSub.Connect();
            }

      private async Task Test()
        {
            var channel = await api.Channels.v3.GetChannelByNameAsync("channelname");
            Console.WriteLine(channel.Id.ToString());
            pubSub.ListenToBitsEvents(channel.Id.ToString());
            pubSub.ListenToSubscriptions(channel.Id.ToString());
            pubSub.SendTopics();
        }

  private void OnTimeout(object sender, OnTimeoutArgs e)
        {
            Console.WriteLine(e.TimedoutUser + " Timeouted by " + e.TimedoutBy);
        }

        private void onPubSubConnected(object sender, EventArgs e)
        {
           Console.WriteLine("PubSub Connected");
           Test();
        }


        private void OnListenResponse(object sender, OnListenResponseArgs e)
        {
            if (e.Successful)
            {
                Console.WriteLine($"Successfully verified listening to topic: {e.Topic}");
            }
            else
            {
                Console.WriteLine($"Failed to listen! Error: {e.Response.Error}");
            }
        }`

**Comment by Mitsukiii** [comment]
seems to work but:
![image](https://user-images.githubusercontent.com/28743231/35691355-8c364c00-0778-11e8-867e-9086ea6b33ea.png)

**Comment by Syzuna** [comment]
Does the Channel you are trying to Listen for Bits and subs on a Partner Program with twitch? Like affiliate or Partner?

**Comment by Mitsukiii** [comment]
Affilate, so yes

**Comment by Syzuna** [comment]
try 

`pubsub.SendTopics(authtoken)`

I think that topics need an auth token

**Comment by Syzuna** [comment]
for bits no special scope is needed but for subs you need the channel_subscription scope for your auth token

**Comment by Mitsukiii** [comment]
Different Error:

but seems to listen? iono

![image](https://user-images.githubusercontent.com/28743231/35692334-5ccdc42c-077b-11e8-98ef-de38dfa1ac43.png)

**Comment by Syzuna** [comment]
yes its listening for bits now and the other error will be for the subs I think bcs you dont have the channel_subscription scope for your auth token

**Comment by Mitsukiii** [comment]
i commented subs out, still get this Response Error but listen to bits.

**Comment by Syzuna** [comment]
oh wait no this isnt an error. :D this is the response from the server on your listen request thats why its of type RESPONSE and the error is blank

**Comment by Mitsukiii** [comment]
oh, awesome. Thanks alot buddy !

**Comment by Syzuna** [comment]
no problem. and yes I know the docs need to be updated :D but time is limited for all of us^^

**Comment by swiftyspiffy** [comment]
Thanks @syzuna . I’ve been bit but this one a number of times. That response from Twitch is super confusing.

**Comment by Mitsukiii** [comment]
most of the docs are up2date, so i had no problem with all other stuff.

Can be closed.

**Comment by swiftyspiffy** [comment]
Glad you figured everything out!
