### ISSUE TITLE
Twitch API needs some work

### ISSUE THREAD

**Issue by igor523** [swiftyspiffy/TwitchLib#36]
Hello!

I think, its time to think about Twitch API. Many of API calls seems to be unimplemented yet. Also, it would be great to categorize methods as they are in Twitch docs. I know, this part may break existing apps, but it also could make adding new methods easier.

**Comment by swiftyspiffy** [comment]
Agreed, this should be the priority, at least until Cheers become more widely available.

**Comment by igor523** [comment]
Is Cheers - a big problem? Just some special emotes, actually. Would be easy for you, I think. API is more important thing, because some really important calls like getting user's followed list (not followers list!) are missing. Or I'm wrong?

**Comment by swiftyspiffy** [comment]
Cheers is a bit more than just an emote, I think. There are some additional tags that need parsing, etc. And you're correct about a user's followed list is not currently supported.

**Comment by swiftyspiffy** [comment]
Recently I've been working on adding more functionality to TwitchApi. Today I have added follow/unfollow, block/unblock/getblockedlist. Hoping to have a majority of the API covered soon.

**Comment by swiftyspiffy** [comment]
I'm going to close this as 95% of the API seems to be covered. If I am missing anything feel free to let me know or pull request it in.
