### ISSUE TITLE
Server Pinger?

### ISSUE THREAD

**Issue by D3thw0lf** [swiftyspiffy/TwitchLib#38]
Hey!

Me again (sorry for disturbing so much xD)

Could you add API Check for Server Pings? I'm trying to ping "Live-fra.Twitch.TV" (Frankfurt Germany DE) Server but it seems that twitch.tv does not allow that w/o using the api. :3

Thanks again. Love your great and powerful work. ❤️

**Comment by swiftyspiffy** [comment]
Hi.

I will look into this now.

**Comment by swiftyspiffy** [comment]
Also, perhaps you meant you want to send a PING via one of the IRC clients (whisper/chat)? I see official support for that in the Twitch API, but not for API (wouldn't make much sense in an API). I will work on implementing PING/PONG support in both clients.

**Comment by D3thw0lf** [comment]
Cool, thanks again. Don't want to disturb so much. Sorry if I do ^w^

**Comment by swiftyspiffy** [comment]
I have added code to auto-pong back to Twitch. Is this kind of what you were looking for? You can disable this feature by setting the TwitchChatClient's DisableAutoPong property to true.

**Comment by swiftyspiffy** [comment]
Additionally, this new code is in the new NuGet version i just sent out tonight :dancer:

**Comment by swiftyspiffy** [comment]
This seems to work, I'll go ahead and close it now :)
