### ISSUE TITLE
Chat Message Caps, Symbols & stuff

### ISSUE THREAD

**Issue by D3thw0lf** [swiftyspiffy/TwitchLib#40]
Is there a way to check if (for example) the message received by
ChatMessage.Message caps > anyIntValue

example:
if(ChatMessage.Message.Caps > 10)
{
// Do what is coded here
}

the same for Symbols (!, :, Emoticons etc)

---
If there's a possible way to do this I would appreciate a Little Code example :3 (I can't figure out how to do this)

Thanks (as always) in advance :)

PS: Sorry if this is the wrong way to ask for help like this. :3

**Comment by swiftyspiffy** [comment]
I'll check symbols later, but for caps, something like this should work:
`
ChatMessage.Message.Count(x => Char.IsUpper(x))
`

**Comment by D3thw0lf** [comment]
Ah nice I'll try that :)

**Comment by igor523** [comment]
For counting symbols you could create your own count function like IsSymbol, that will take char as argument and return true, if this char is "symbol" (detect that as you wish), and false either. And then you could do ChatMessage.Message.Count(x => Char.IsSymbol(x)) to count all chars, that match to your function

**Comment by igor523** [comment]
Oops, I meant
ChatMessage.Message.Count(x => IsSymbol(x))

**Comment by swiftyspiffy** [comment]
In the IsSymbol, you'll probably want to get the character ASCII code and see if it is larger than or equal to 32 or smaller than or equal to 127 should validate it with the "printable" characters.

**Comment by swiftyspiffy** [comment]
That would be the easiest way of validating the character I believe.

**Comment by igor523** [comment]
This will detect Cyrillic as symbols, I believe =)

**Comment by swiftyspiffy** [comment]
[http://www.ascii-code.com/](ascii-code.com)

I think Cyrillic character lie outside of the 127 judging by that table.

**Comment by swiftyspiffy** [comment]
That being said, OP included ! In their initial post, so we'd need to exclude some ascii codes to accommodate that, as the range I gave includes that and other commonly used symbols.

**Comment by igor523** [comment]
Agreed =)

**Comment by swiftyspiffy** [comment]
So to clear this up, if you want to track any character that isn't a number or a capital or lower case English letter, you're going to want to iterate through the message contents and for each character convert it to an ASCII code. Using that code, check if the code is:
 -  between 47 (noninclusive) and 58 (noninclusive) 
AND 
 - between 64 (noninclusive) and 91 (noninclusive)
AND
 - between 96 (noninclusive) and 123 (noninclusive)

So the code that demonstrates how many symbols are in a message would look something like:
`
ChatMessage.Message.Count(x => isSymbol(x))

private bool isSymbol(char character)
{
    int ascii = (int)character;
    if (ascii > 47 && ascii < 58)
        return false;
    if (ascii > 64 && ascii < 91)
        return false;
    if (ascii > 96 && ascii < 123)
        return false;
    return true;
}
`

**Comment by swiftyspiffy** [comment]
Looks like github butchered the formatting on the function :(

**Comment by swiftyspiffy** [comment]
I'm going to close this, hopefully my messages above have cleared it up a bit.
