### ISSUE TITLE
Chat Message ColorHex

### ISSUE THREAD

**Issue by RamonRobben** [swiftyspiffy/TwitchLib#41]
Hi I want to report a problem.
So for some reasons the ChatMessage.ColorHex does not return a color.
To make sure its not the fault of my code I have tried these solutions:

This just printed nothing
`Console.WriteLine(ColorHex)`

This gave me some colors but also a few black colors while the color in the twitch chat is certainly not black.
`Color color = ColorTranslator.FromHtml(e.ChatMessage.ColorHex);`

This gave me an error about wrong input but in a Try catch it gave me the same results as my first code.
```
int argb = Int32.Parse(e.ChatMessage.ColorHex.Replace("#", ""), NumberStyles.HexNumber);
Color clr = Color.FromArgb(argb);
```

I've also set the RichTextBox to this color "#FF7F50" to see if it displays black but it doesn't.

**Comment by RamonRobben** [comment]
Here are some more colors that weren't received or incorrectly:

#FF0000
#008000
#5F9EA0
#5F9EA0
#9ACD32

**Comment by RamonRobben** [comment]
For some reasons the colors above do get received correct but sometimes not. Some of the colors did work with other users with the exact same color.

**Comment by D3thw0lf** [comment]
It's when People not set any specific Color Hand have the "random Color" on every reload. I've did the following if they're Color is null.

for example:
`if (e.ChatMessage.ColorHex == "" && e.ChatMessage.IsBroadcaster == true)
                    {
                        List<User> items = new List<User>();
                        items.Add(new User() { ChatTime = DateTime.Now.ToString("HH:mm "), IsTeamMember = "Collapsed", IsBroadcaster = "Visible", IsMod = "Collapsed", UserColor = "#FF9652E8", UserName = e.ChatMessage.Username + ": ", ChatMessage = e.ChatMessage.Message });
                        Chat.Items.Add(items);
                    }
                    else if (e.ChatMessage.ColorHex != "" && e.ChatMessage.IsBroadcaster == true)
                    {
                        List<User> items = new List<User>();
                        items.Add(new User() { ChatTime = DateTime.Now.ToString("HH:mm "), IsTeamMember = "Collapsed", IsBroadcaster = "Visible", IsMod = "Collapsed", UserColor = e.ChatMessage.ColorHex, UserName = e.ChatMessage.Username + ": ", ChatMessage = e.ChatMessage.Message });
                        Chat.Items.Add(items);
                    }`

maybe not the best solution but it worked so far :)

**Comment by swiftyspiffy** [comment]
@RamonRobben Those hex colors were in the IRC raw string, but were not parsed into the ChatMessage object? Or are those color strings your browser rendered and you copied from your browser?

**Comment by RamonRobben** [comment]
@swiftyspiffy Those where colors from the browser that I manually copied and pasted.

**Comment by swiftyspiffy** [comment]
Interesting, so it seems that no value is assigned if the chatter has a HEX value of null. This seems like an alright way to handle it, do you have suggestions or ideas? I'm pretty flexible on ways to handle it.

**Comment by swiftyspiffy** [comment]
We can make chat messages with no assigned hex color a random color, or we can make all unassigned users the same color. Hmmm

**Comment by RamonRobben** [comment]
A random color would be fine only if it can be saved for that session. But it has to be viewable on a light or dark background depending on the GUI of the bot. Also, when the user has lots of viewers ram usage can go up pretty quickly. So maybe a limit on the list would be cool. After that just assign a static color.

This is my guess on the best solution to this problem.
But twitch really gotta send that temp color instead of null...

**Comment by igor523** [comment]
You're right. Some users doesn't have any color assigned. You can update Twitch page and see, that color of user's messages has changed. Twitch uses random color (one of the non-Turbo colors) for session.

**Comment by swiftyspiffy** [comment]
Alright, so what direction do we want to go then? We could assign random colors and maintain that state for each user, but that'd take a decent amount of effort as to maintain the scoping for ChatMessage object. I personally don't mind having an empty value or even a null value as to indicate that the message had no hex color assigned, and then let developer implementing the library determine how to handle it.

**Comment by igor523** [comment]
I don't think that implementing that "randomness" in TwitchLib is good idea, you're right. It's better to leave it to RamonRobben.

**Comment by igor523** [comment]
Null is pretty good, cause we can make != null check and go on with random color. I think, it's not that hard for OP - just a list with all chatters, that doesn't have any colors. If color in message is null - we're looking in that list. If we haven't found chatter, we're adding him in the list with random color. If we found him, using color in list. Of course, you could optimize it with Dictionary<string, Color>, if you wish.

**Comment by D3thw0lf** [comment]
@RamonRobben yes this is just an example how you can handle the != null or "" check like @igor523 said in the last answer. :)

**Comment by RamonRobben** [comment]
Yes I think its a good idea to leave it to the developer but you might want to tell people about this somehow. But anyways I think this one is solved. Its not a fault in the TwitchLib but from twitch itself.

**Comment by swiftyspiffy** [comment]
I'll update the XML descriptor for ChatMessage and ColorHEX detailing this. Thanks for pointing out the potential issue.
