### ISSUE TITLE
TwitchApi not that simple to use.

### ISSUE THREAD

**Issue by RamonRobben** [swiftyspiffy/TwitchLib#42]
Or it can be only the GetChatters function. I'm having a hard time trying to guess how to use the GetChatter function to retrieve a list of current chatters. I tought it would be as simple as:
`var chatters = TwitchApi.GetChatters(channel);`
But it sadly isn't.

Then I used the exact same code as in the usage description:
`List<TwitchLib.TwitchAPIClasses.Chatter> x = await TwitchApi.GetChatters(channel);`
Didn't work because await operator can only be used with async methods.

Well I only want to get a list. How hard can it be? I removed the await but then it gave me a task.
`List<TwitchLib.TwitchAPIClasses.Chatter> x = TwitchApi.GetChatters(channel);`
It wants to give me some thread that does the same thing...

How do I need to use this? Maybe I'm just really stupid but I don't see the logic for this.
I think it should be just as simple as doing this:
`var chatters = TwitchApi.GetChatters(channel);`
and now the var chatters contains the list.

**Comment by swiftyspiffy** [comment]
Hi, I recommend checking out the example project that is a part of this project, it has a ton of examples of how to use the TwitchApi. 
Regarding the issue you're having, I think your methods calling the TwitchApi are not asynchronous methods. Every function in TwitchApi are asynchronous. This should be a very easy fix for you. Below is a button click calling GetChatters(channel):


```
private async void button10_Click(object sender, EventArgs e)
{
        List<TwitchLib.TwitchAPIClasses.Chatter> chatters = await TwitchApi.GetChatters(textBox10.Text);
        foreach(TwitchLib.TwitchAPIClasses.Chatter user in chatters)
            MessageBox.Show($"User: {user.Username}\nUser type: {user.UserType}");
}
```

Please note how the prototype of the method:
`private async void button10_Click(object sender, EventArgs e)`
has async after the scope identifier. This async tells .net framework that the method is an asynchrouns method. Once you add that async to your method, it should work.

Cheers.

**Comment by RamonRobben** [comment]
Yea I have it working now but the async is a little bit annoying. Can't you make it optional?

**Comment by swiftyspiffy** [comment]
In the future it's possible there could be async and sync calls, but at the moment it's not possible because the method prototypes have to identify async or not. What you can do if you don't want to use async is append `.Result` to the end of the call. This will have the thread wait synchronously for the result. Do be careful though, this can lead to race conditions and a lock of your application.

Example:
`var chatters = TwitchApi.GetChatters(channel).Result;`

**Comment by swiftyspiffy** [comment]
Hopefully this issue has been sort of fixed, at least for the time being. I/we'll look into implementing async and sync calls down the line.
