### ISSUE TITLE
Fody Issues

### ISSUE THREAD

**Issue by stuntguy3000** [swiftyspiffy/TwitchLib#43]
Hi there,

I am trying to compile my project but I am having issues with Fody.

![image](https://cloud.githubusercontent.com/assets/1522389/18027905/0c422812-6caf-11e6-8ecf-042d16cc6808.png)

I have reinstalled the project to no luck.

**Comment by stuntguy3000** [comment]
Fixed, did a full reinstall

**Comment by swiftyspiffy** [comment]
Cool. I've run into that issue as well, and had the same fix.
