### ISSUE TITLE
TwitchLib usage issues

### ISSUE THREAD

**Issue by stuntguy3000** [swiftyspiffy/TwitchLib#44]
![image](https://cloud.githubusercontent.com/assets/1522389/18027921/83140e38-6caf-11e6-97ab-457dce0aaab8.png)

Using this code, it says false twice and no event method fires.

**Comment by igor523** [comment]
Connect is kind of async. It STARTS connection procedure, but not WAITS until it done. So second show runs before connection have been done completely, that's where second false comes from. You'll have to wait for OnConnected event.

**Comment by swiftyspiffy** [comment]
igor is correct, the Connect method is not async, but acts asynchronous. For that reason, you should utilize OnConnected event as your identifier that the library successfully connected. Also, you may want to listen to IncorrectLogin as well.

Cheers

**Comment by D3thw0lf** [comment]
does not connecting for me, too. had to revert to v.1.1.6 where it works perfectly.

**Comment by swiftyspiffy** [comment]
Can you explain a bit more indepth. I have two applications (one a 24hour bot) running on the latest version of the library, and both can connect.  This is something that needs to be looked into if it turns out to be a technical problem.

**Comment by D3thw0lf** [comment]
Getting this as Output:
:tmi.twitch.tv NOTICE * :Improperly formatted auth
Unaccounted for: :tmi.twitch.tv NOTICE * :Improperly formatted auth

this is the Code:
`                ConnectionCredentials credentials = new ConnectionCredentials(this.appSettings.LastChannelName, this.appSettings.OAuthToken);
                TwitchClient newClient = new TwitchClient(this.appSettings.LastChannelName, credentials, '!', true);`

**Comment by igor523** [comment]
Is your token has right scopes and "oauth:" prefix?

**Comment by D3thw0lf** [comment]
aww shit... >.> and I've commented my old Code with that...geez thanks. seems to work 👍

**Comment by swiftyspiffy** [comment]
I think your token requires an "oauth:" prefix as ignore mentions. I am adding a check now to the library to make that a little more known.

**Comment by swiftyspiffy** [comment]
awesome :)

**Comment by igor523** [comment]
You're welcome! By the way, @swiftyspiffy, I think it's better to parse this response, calling OnIncorrectLogin event.

**Comment by D3thw0lf** [comment]
Chat Messages appear and i can send Messages, commands etc. but log says this:
:tmi.twitch.tv 001 kaefgames_entertainment :Welcome, GLHF!
Unaccounted for: :tmi.twitch.tv 001 kaefgames_entertainment :Welcome, GLHF!
:tmi.twitch.tv 002 kaefgames_entertainment :Your host is tmi.twitch.tv
Unaccounted for: :tmi.twitch.tv 002 kaefgames_entertainment :Your host is tmi.twitch.tv
:tmi.twitch.tv 003 kaefgames_entertainment :This server is rather new
Unaccounted for: :tmi.twitch.tv 003 kaefgames_entertainment :This server is rather new
:tmi.twitch.tv 004 kaefgames_entertainment :-
Unaccounted for: :tmi.twitch.tv 004 kaefgames_entertainment :-
:tmi.twitch.tv 375 kaefgames_entertainment :-
Unaccounted for: :tmi.twitch.tv 375 kaefgames_entertainment :-
:tmi.twitch.tv 372 kaefgames_entertainment :You are in a maze of twisty passages, all alike.
:tmi.twitch.tv 376 kaefgames_entertainment :>
Unaccounted for: :tmi.twitch.tv 376 kaefgames_entertainment :>
:tmi.twitch.tv CAP * ACK :twitch.tv/membership
Unaccounted for: :tmi.twitch.tv CAP * ACK :twitch.tv/membership
:tmi.twitch.tv CAP * ACK :twitch.tv/commands
Unaccounted for: :tmi.twitch.tv CAP * ACK :twitch.tv/commands
:tmi.twitch.tv CAP * ACK :twitch.tv/tags
Unaccounted for: :tmi.twitch.tv CAP * ACK :twitch.tv/tags

crazy

**Comment by swiftyspiffy** [comment]
Yup, that's normal usage @D3thw0lf :D If you want to turn off logging, remove the 'true' you have in the TwitchClient constructor's last argument. There are many IRC messages that the library ignores.

Also, good idea igor.

**Comment by D3thw0lf** [comment]
ok thanks again. ^^

**Comment by swiftyspiffy** [comment]
Cheers :) I'll close this now.
