### ISSUE TITLE
UpdateStreamTitle not changing anything on Twitch

### ISSUE THREAD

**Issue by tsuneko** [swiftyspiffy/TwitchLib#45]
Twitch channel shows no visible changes when I execute
`TwitchApi.UpdateStreamTitle("Title",channel,oauth);`
(Same issue with UpdateStreamTitleAndGame)

I also tested using the Example project, and that did not do anything. The values for channel and oauth should be correct since I can send and receive messages without issue (and I have a ClientID set already).

Am I doing something wrong here?

**Comment by igor523** [comment]
Not any oauth could be used here. You'll have to get oauth with some extra permissions. See official Twitch API documentation

**Comment by swiftyspiffy** [comment]
I will test this in a few hours and get back to you about it.

**Comment by swiftyspiffy** [comment]
I can confirm that both UpdateStreamTitle, UpdateStreamGame, and UpdateStreamTitleAndGame all work. Please check that your access token has the correct scope to modify these channel settings.

I created a page that should generate an access token for a Twitch account with ALL scopes. If you trust me, you can use the tool I used to get my access token: [burkeblack.tv/testapp/twitchauth.php](https://burkeblack.tv/testapp/twitchauth.php)

**Comment by tsuneko** [comment]
Alright, thanks for the reply :)
