### ISSUE TITLE
ReSubscriber Message Parsing Bug

### ISSUE THREAD

**Issue by Examed** [swiftyspiffy/TwitchLib#46]
If the first character of a ResubMessage is a character like # the parsing fails and adds "tmi.twitch.tv USERNOTICE" to the string.
In all other cases its working perfect :+1: 

Example: 
tmi.twitch.tv USERNOTICE #hype :I missed my 6 month and 3 month resub :P can i get added on sc and steam?

**Comment by swiftyspiffy** [comment]
I'll look into this now.

**Comment by Examed** [comment]
Ok :) I just noticed while I was testing it in some random channels and ppls started using #.... in their messages.
Btw you really did an awesome job with programming :+1:

**Comment by swiftyspiffy** [comment]
I have an idea of what may be causing the problem, but not 100% sure. Going to verify here shortly and then push an update. New NuGet version out tonight with this fix and new TwitchApi functionality.

Also, thanks, that means a lot :dancer: 
Cheers!

**Comment by Examed** [comment]
Ohh awesome :) What TwitchApi functions will be added ?
And will the cheering-feature also be added in the future ?

**Comment by Examed** [comment]
I currently noticed its not triggerd by #in the message has to be something else. 

tmi.twitch.tv USERNOTICE #kaypealol :Never been subbed to anyone this long before KP! Jag gillar verkligen din stream ( i really like your stream) some swedish again :D

**Comment by Examed** [comment]
Even getting Messages like this .

10-17;login=worgenrunt01;mod=0;msg-id=resub;msg-param-months=5;room-id=20694610;subscriber=1;system-msg=Worgenrunt01\ssubscribed\sfor\s5\smonths\sin\sa\srow!;turbo=0;user-id=67365913;user-type= :tmi.twitch.tv USERNOTICE #towelliee :towLegion towHAMUP

**Comment by swiftyspiffy** [comment]
NuGet change notes at the moment:  Fixes critical whisper command bug, follow and unfollow added, adds block, unblock and get blocked list, adds get channel editors.

Cheer is supported at the moment. The Message object has a property `Bits` (number of bits in message) and `BitsInDollars` (bits converted to US dollars using the percentage system Twitch has in place). I may add an event that fires when a message is received that has bits in it, dunno yet though.

Also, Message objects have a `CheerBadge` property (returns CheerBadge object if one is present, null otherwise) and a `Badges` property (which returns a keyvalue list with all badges a user has).

**Comment by swiftyspiffy** [comment]
Interesting, I'm writing a method that will be able to test parsing. Should make debugging easier. You are using the latest code right?

**Comment by Examed** [comment]
I'm using the Nugget Code Version 1.1.9 

Ohh I will look into Cheering then :)

**Comment by swiftyspiffy** [comment]
Do you have the entire IRC message that was causing issues? It seems
```
tmi.twitch.tv USERNOTICE #kaypealol :Never been subbed to anyone this long before KP! Jag gillar verkligen din stream ( i really like your stream) some swedish again :D
```
is only part of the entire IRC message.

**Comment by Examed** [comment]
Let me add something that is story the full IRC message too

**Comment by swiftyspiffy** [comment]
Alright, let me know when you have that, it will help significantly in solving this problem :)

Thanks.

**Comment by Examed** [comment]
ResubMessage :
tmi.twitch.tv USERNOTICE #dansgaming :danChamp 19 inches danChamp

IRC Message :
@badges=subscriber/1;color=#5F9EA0;display-name=BrotherJon;emotes=86559:0-7,19-26;login=brotherjon;mod=0;msg-id=resub;msg-param-months=19;room-id=7236692;subscriber=1;system-msg=BrotherJon\ssubscribed\sfor\s19\smonths\sin\sa\srow!;turbo=0;user-id=30809633;user-type= :tmi.twitch.tv USERNOTICE #dansgaming :danChamp 19 inches danChamp

**Comment by Examed** [comment]
Failing ResubMessage:
tmi.twitch.tv USERNOTICE #lirik :hi @KING_GORDON lirikH

@badges=subscriber/1;color=#008000;display-name=haaralab;emotes=15020:16-21;login=haaralab;mod=0;msg-id=resub;msg-param-months=7;room-id=23161357;subscriber=1;system-msg=haaralab\ssubscribed\sfor\s7\smonths\sin\sa\srow!;turbo=0;user-id=57156133;user-type= :tmi.twitch.tv USERNOTICE #lirik :hi @KING_GORDON lirikH

Working Resub Message : 
tmi.twitch.tv USERNOTICE #lirik :hi @KING_GORDON lirikH

@badges=subscriber/1;color=#008000;display-name=haaralab;emotes=15020:16-21;login=haaralab;mod=0;msg-id=resub;msg-param-months=7;room-id=23161357;subscriber=1;system-msg=haaralab\ssubscribed\sfor\s7\smonths\sin\sa\srow!;turbo=0;user-id=57156133;user-type= :tmi.twitch.tv USERNOTICE #lirik :hi @KING_GORDON lirikH

**Comment by swiftyspiffy** [comment]
Awesome, thanks.

**Comment by Examed** [comment]
haha just realized we are talking all the time about a twitchAPI so you definitly have a Twitch Stream. 
So I just dropped you a follow :+1:

**Comment by swiftyspiffy** [comment]
I don't really stream, just develop for various streamers, right now almost primarily for https://twitch.tv/BurkeBlack

I just tried running that broken IRC message through the message parser and I didn't get any issues, and the ReSubscriber event was fired. What error specifically are you getting?

**Comment by Examed** [comment]
![02-09-_2016_01-11-20](https://cloud.githubusercontent.com/assets/21694673/18187497/4fd8aafc-70aa-11e6-9544-6be801410044.png)

ResubMessage contains "tmi.twitch.tv USERNOTICE #summit1g :"  and then the message.

But it only happends about ever 4-5. Message maybe even less.

**Comment by swiftyspiffy** [comment]
Ohh, is that the issue you are having? That it is placing that extra irc data in the resub message? I thought you were having a parse-causing crash issue. I will look into that now.

**Comment by swiftyspiffy** [comment]
Can you confirm the working and broken IRC messages are the same/different? They look identical to me. I see the problem, but just wanted to confirm that you aren't getting different results from the exact same IRC message.

**Comment by Examed** [comment]
![02-09-_2016_01-26-18](https://cloud.githubusercontent.com/assets/21694673/18187724/5e0953ae-70ac-11e6-938e-4bbdb8f89080.png)

Thats how a normal Message looks like

**Comment by swiftyspiffy** [comment]
Would you mind pasting the IRC message in a comment please.

**Comment by Examed** [comment]
@badges=subscriber/1;color=#0000FF;display-name=Voljan123;emotes=;login=voljan123;mod=0;msg-id=resub;msg-param-months=10;room-id=26301881;subscriber=1;system-msg=Voljan123\ssubscribed\sfor\s10\smonths\sin\sa\srow!;turbo=0;user-id=51438980;user-type= :tmi.twitch.tv USERNOTICE #sodapoppin :aids

**Comment by swiftyspiffy** [comment]
Found the problem, it's related to a resub message having an emote set or not. Fixing now.

**Comment by Examed** [comment]
ok awesome :+1: 
wrote you on twitch also ^^

**Comment by Examed** [comment]
![02-09-_2016_02-37-53](https://cloud.githubusercontent.com/assets/21694673/18188930/66bd104e-70b6-11e6-9464-aa0c6ad44414.png)

**Comment by Examed** [comment]
@badges=subscriber/1;color=#FF0000;display-name=Nerfed4u;emotes=;login=nerfed4u;mod=0;msg-id=resub;msg-param-months=7;room-id=26490481;subscriber=1;system-msg=Nerfed4u\ssubscribed\sfor\s7\smonths\sin\sa\srow!;turbo=0;user-id=63095411;user-type= :tmi.twitch.tv USERNOTICE #summit1g

**Comment by Examed** [comment]
But the next one worked finde so I dont know whats wrong.

![02-09-_2016_02-39-35](https://cloud.githubusercontent.com/assets/21694673/18188953/9b14eeb6-70b6-11e6-8ce5-c81242332261.png)

@badges=subscriber/1;color=#FF69B4;display-name=Kippyyysmith;emotes=;login=kippyyysmith;mod=0;msg-id=resub;msg-param-months=9;room-id=26490481;subscriber=1;system-msg=Kippyyysmith\ssubscribed\sfor\s9\smonths\sin\sa\srow!;turbo=0;user-id=57052758;user-type= :tmi.twitch.tv USERNOTICE #summit1g :Yo we making a baby!

**Comment by Examed** [comment]
I think now its putting the RawIrc in the ResubMessage whenever the ResubMessage is empty

**Comment by swiftyspiffy** [comment]
I believe this issue has been solved :)
