### ISSUE TITLE
IRC connection drop seems to break chat client

### ISSUE THREAD

**Issue by igor523** [swiftyspiffy/TwitchLib#47]
Hello again!

Well, it's king of ghost bug for now cause of lack of data. My bot silently faulted twice. When I've tried to restart it (restart code reuses existent chat client with Reconnect method) I've got an exception, something from SmartIrc4Net. Can't provide specific error message, sorry. I'll post here if I'll catch this bug again, but maybe you'll find bug without it, if you'll double check what exceptions could be thrown by Irc4Net.

Thanks!

**Comment by swiftyspiffy** [comment]
Interesting, I had something like this a while ago, but I thought I resolved it by setting the autoreconnect property on the smartirc client to true.

**Comment by igor523** [comment]
Well, there is no problems yet. I'll close it for now
