### ISSUE TITLE
Fody Issues

### ISSUE THREAD

**Issue by stuntguy3000** [swiftyspiffy/TwitchLib#48]
Hi, I am having too many issues with Fody failing or corrupting, Can i get a DLL to use?

**Comment by stuntguy3000** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Fody: No configured weavers. It is possible you have not installed a weaver or have installed a fody weaver nuget into a project type that does not support install.ps1. You may need to add that weaver to FodyWeavers.xml manually. eg. <Weavers><WeaverName/></Weavers>. see https://github.com/Fody/Fody/wiki/SampleUsage	FUGSTwitch

**Comment by swiftyspiffy** [comment]
Are you obtaining the library through NuGet, or cloning through Github? I would strongly recommend pulling it from NuGet.

**Comment by swiftyspiffy** [comment]
I'll build you a DLL here in a few hours of it turns out your NuGet isn't working.

**Comment by stuntguy3000** [comment]
NuGet. Whenever it stuffs up I just remove all dependencies and reimport, but its working _for now_ fine.

**Comment by swiftyspiffy** [comment]
This seems to be resolved now:)
