### ISSUE TITLE
System.StackOverflowException' when trying to GetUser

### ISSUE THREAD

**Issue by rafalrozek** [swiftyspiffy/TwitchLib#49]
Error:

> An unhandled exception of type 'System.StackOverflowException' occurred in mscorlib.dll

My code:
```
          var x = await TwitchApi.GetUser("myuser");
            if (x != null)
            {
                MessageBox.Show(x.Name);
            }
```

VisualStudio show this error in 160 line in Common.cs file. How to repait it?

**Comment by swiftyspiffy** [comment]
I'll look into this now.

**Comment by swiftyspiffy** [comment]
A couple things I'd like to confirm with you:
1. Make sure you're setting a ClientId. To do this, call `TwitchApi.SetClientId("twitch app id")`
2. Just to be sure, you are using a valid username right? You're not trying to get `myuser`? If a bad username is given, should return null.

I was able to fetch a user object successfully.

As a side note, I don't think there is a line 160 in the Common.cs file.

**Comment by rafalrozek** [comment]
1. Oh, I forget to add SetClientID function, but when I add it in window constructor, my application is crashing..
![image](https://cloud.githubusercontent.com/assets/17208383/18234152/7b880b36-72fb-11e6-8143-9a9c64b97c73.png)

**Comment by swiftyspiffy** [comment]
Are you able to set a break point and go into the library and see what is causing it to blow the stack?

**Comment by rafalrozek** [comment]
It always show me this line: 
`return Assembly.Load(assemblyData);`
How to check what is causing blowe the stack?..

**Comment by swiftyspiffy** [comment]
I have absolutely no clue why you are hitting this issue. Can I see all of your code related to this call, anything that affects it?

**Comment by swiftyspiffy** [comment]
Out of curiosity, try completely removing the library and readding it. This has solved other people's problems and may solve yours. It's kind of a shot in the dark, but may be worth a try.

**Comment by swiftyspiffy** [comment]
I will close this since I haven't heard back from you.
