### ISSUE TITLE
Follower Service Problems

### ISSUE THREAD

**Issue by D3thw0lf** [swiftyspiffy/TwitchLib#50]
Hi,

Your Follower Service has some problems (since some of the latest updates). It seems that sometimes it won't get any response from twitch and sometimes it grabs the latest follower more than once which returns (in my project) in chat spam.

This is my code:

private void OnNewFollowersDetected(object sender, TwitchLib.Services.FollowerService.OnNewFollowersDetectedArgs e)
        {

            if (this.appSettings.Bot_Follower_Notify == true)
            {
                string newFollower = "";

                foreach (TwitchLib.TwitchAPIClasses.Follower follower in e.NewFollowers)
                {
                    if (newFollower == "")
                    {
                        newFollower = follower.User.Name;
                    }
                    else
                    {
                        newFollower += ", " + follower.User.Name;
                    }
                }
                string followmessage = this.appSettings.Bot_Message_On_Follower + " " + newFollower;
                foreach (TwitchClient client in clients)
                {
                    client.SendMessage(followmessage);
                }
            }
        }

If Git is messing around the code: http://pastebin.com/zKHMPivX

As I said: It worked fine (for me) in older Versions. Maybe you can get a look into it and tell me if I'm doing something wrong since new Updates. :/

As always: Thanks in advance. :)

**Comment by swiftyspiffy** [comment]
Looks like your event code is correct, is it possible to see the instantiation of the FollowerService and the settings applied to it so I can try to recreate it.

**Comment by D3thw0lf** [comment]
this.appSettings.Bot_Messae etc is just a string for example "Thanks for your follow," + " " + xXuserxyz123overl0rd9500Xx; ;)

http://pastebin.com/cK4t0DzL <- Hope this helps :3

**Comment by swiftyspiffy** [comment]
I will test this code out when I get home and see if I can recreate your issue. I don't see anything immediately wrong, but it's possible the web call is doing something spooky.

**Comment by D3thw0lf** [comment]
Thank you. I hope you can find out what is happening with the darn twitch api and their serverz :)

**Comment by swiftyspiffy** [comment]
Alright, so using the Example application in the project, I was able to connect to NoahJ456's channel (he had 24,000 viewers at the time). It appears to be working.
![Image of Example Application Twitch Follower Service](http://swfty.xyz/?id=377Efa365)

**Comment by D3thw0lf** [comment]
hmn crazy...I'll try that out but could this also a problem with contentcontrol? Everytime a user clicks on "Stream-Admin" in my Software the page get switched back to that said Stream-Admin page. Is there any way to say "stay loaded and do not reload any element on button click"? :3

Googled a lot but not finding a proper solution maybe someone here knows. Tried to set "KeepAlive" on the wpf but this does not worked for me. :/

**Comment by D3thw0lf** [comment]
The element on wpf is called "Frame"

**Comment by swiftyspiffy** [comment]
I can't imagine it'd be a problem with a specific control supported by the .Net framework, but then again, I've never really worked with wpf, so i can't say for sure. If you are using a webbrowser control, I know there is a `AllowNavigation` property that you can set to false, but that may not prevent navigation via links. The best direction i can think of would be to read the document text and strip out the anchor tags or nullify them somehow, before having the browser render it. There is an event for when the browser finishes loading.

**Comment by D3thw0lf** [comment]
Thanks. I'll take a look at your solutions. :)

**Comment by D3thw0lf** [comment]
Thanks. I'll take a look at your solutions. :)

**Comment by D3thw0lf** [comment]
Another Follower related question:
I'm trying to write the latest 5 followers into a textfile for OBS (so it has to be on one line)

this is my code
`foreach (TwitchLib.TwitchAPIClasses.Follower follower in response.Followers)
{
    LastFollowerList.Items.Add(string.Format("{0} " + "folgt dir", follower.User.Name));                        
    File.WriteAllText(this.GetFollowerFile(), string.Format("{0}", follower.User.Name + "    "));
}`

The thing is, it just returns only one follower in Textfile but has to return 5 followers like in my listbox. :/

Sorry for disturbing...I guess the solution is easy but I'm not finding the problem. :(

**Comment by swiftyspiffy** [comment]
I'll have a solution for you in a few hours. Need to catch some sleep.

**Comment by D3thw0lf** [comment]
Nice. Thanks :)

**Comment by swiftyspiffy** [comment]
Try:
```
File.WriteAllText(this.GetFollowerFile(), response.Followers.Count > 4 ? string.Join(" ", response.Followers.Take(5)) : "Less than 5 recent followers!");
```

**Comment by D3thw0lf** [comment]
I'll try that. As always thanks for your great support (even if it's not much related to your lib). :+1:

**Comment by swiftyspiffy** [comment]
Awesome, I'll go ahead and lose this then.

Cheers!
