### ISSUE TITLE
TwitchApi.GetChatters ERROR

### ISSUE THREAD

**Issue by Examed** [swiftyspiffy/TwitchLib#51]
TwitchApi.GetChatters(Channel) gives me an Error 400.

An unhandled exception of type 'System.Net.WebException' occurred in mscorlib.dll
Additional information: The remote server returned an error : ( 400 ) Bad Request.

![06-09-_2016_05-10-48](https://cloud.githubusercontent.com/assets/21694673/18260802/a2c3f13c-73f1-11e6-8e18-602df9539f9c.png)

**Comment by Examed** [comment]
OK I found the Error.
The channel has to be .ToLower() otherwise it will crash if there is an uppercase in the name

**Comment by swiftyspiffy** [comment]
Thanks for debugging this and finding the issue. I'll add a fix to the library that forces the channel to be lowercase. 

Sorry about that!

**Comment by swiftyspiffy** [comment]
I have just pushed the fix.

Cheers :)
