### ISSUE TITLE
TwitchClient.Channel

### ISSUE THREAD

**Issue by toffaste1337** [swiftyspiffy/TwitchLib#52]
This should return all of the channels the bot is connected to.

**Comment by toffaste1337** [comment]
Yeah also, I don't think the TwitchClient.JoinChannel works :-1:

**Comment by swiftyspiffy** [comment]
Looking into this now. At one point the JoinChannel was invoked to join a channel, but now this is done automatically when you initialize the TwitchClient. As such, this is sort of legacy code. Currently, I think for multi-channel bots, multiple TwitchClients are created and managed. I haven't looked too much into joining channels after having already initially joined a channel.

**Comment by swiftyspiffy** [comment]
Will do so now, though.

**Comment by swiftyspiffy** [comment]
Alright, good news and bad news. The good is that adding the ability for the client to connect to multiple channels is quite easy, though the bad news is that a good portion of the client will need to be rewritten.

**Comment by swiftyspiffy** [comment]
Mmk, after a few hours, I have added the ability for the client to join multiple channels. I am sure it is buggy, but after a very basic test, it appeared to be working. See commits:
767e425fc1c2714972141cdc0062754359fa7ec4
d5994e2ae37124eb6cd9fe21e552f95530f622fb

**Comment by toffaste1337** [comment]
Thank you :) Your TwitchLib is very good as I have not been able to keep a connection to the twitch servers using my own code.

**Comment by toffaste1337** [comment]
How do I use TwitchLib when the update is not out on NuGet Packet Manager?

**Comment by swiftyspiffy** [comment]
Ya, it's not in NuGet yet because I don't trust it to be bug free yet. If you want the bleeding edge of the library, you can either clone the repo (git clone) or just download it: 
[https://github.com/swiftyspiffy/TwitchLib/archive/master.zip](https://github.com/swiftyspiffy/TwitchLib/archive/master.zip)

Once you have it downloaded, open the TwitchLib.csproj file and have Visual Studio build it. Check the /Debug/ folder and get the .dll library. Reference that library in your project.

**Comment by swiftyspiffy** [comment]
If that doesn't sound fun, I'll try to do more bug testing on the current code and get a NuGet version out before like Friday.

**Comment by toffaste1337** [comment]
Yeah, I managed to get the DLL compiled yesterday :) Seems to work as far as my testing goes.

**Comment by swiftyspiffy** [comment]
Awesome! That's good to hear. I don't really have an application that is designed to join multiple channels, so I'm working on one so I can verify functionality across the board in multiple joined channels.

**Comment by toffaste1337** [comment]
Also, it misses a channel PART function if I'm not mistaken.

**Comment by swiftyspiffy** [comment]
Meant to add that yesterday but forgot. Will do when I get home here in a few hours.

**Comment by swiftyspiffy** [comment]
Go ahead and pull and give it a try. You should be able to leave a channel either by string (channel name) or if you want to iterate the JoinedChannels list by JoinedChannel object using either:
`LeaveChannel(string channel)`
or
`LeaveChannel(JoinedChannel channel)`

**Comment by toffaste1337** [comment]
Works great, thanks :)

**Comment by swiftyspiffy** [comment]
Cool. I will close this when the new NuGet version goes out including the fixed JoinChannel and the added LeaveChannel.

Cheers :)

**Comment by swiftyspiffy** [comment]
I just pushed the latest NuGet version out :)
