### ISSUE TITLE
TwitchLib doesn't need to depend on Fody

### ISSUE THREAD

**Issue by igor523** [swiftyspiffy/TwitchLib#53]
Hello!

TwitchLib works great without Fody and Costura packages. Try it yourself in separate project by making force uninstall these packages. So, is it really that necessary to create useless dependencies? Okay, TwitchLib builds with Costura, okay, but why do we need to install it with lib itself? Weaving is build-time process, that have been done when you compiled lib, right?

**Comment by swiftyspiffy** [comment]
You are correct, it is not needed or even used immediately. It is something that's been in the library since like day 1, and I simply haven't removed it. I'll look into doing that for the next NuGet version, along with the ability to join multiple channels.

**Comment by igor523** [comment]
Okay, thanks! One more thing about multichannel support. Please, make sure that new version of TwitchClient will perform stable on single channel, because single-channel use is really important usecase. Thank you in advance! =)

**Comment by swiftyspiffy** [comment]
Yup, and remember, if it doesn't you can always fall back to the previous verison in NuGet :)

But ya, I won't be patching until probably need weekend.

**Comment by swiftyspiffy** [comment]
It should be noted though, it's going to be a code-breaking change, in that initialization and event handling will need to be changed a bit to make way for a JoinedChannel object.

**Comment by igor523** [comment]
Well, I'm using kind of wrapper above your client to make it thread safe, so it won't be that painful to edit single class, but thank you for the warning! =)

**Comment by swiftyspiffy** [comment]
Costura/Fody removed in the NuGet version I just pushed out :)
