### ISSUE TITLE
TwitchClient.OnChatCommandReceivedArgs 

### ISSUE THREAD

**Issue by zerocarbthirty** [swiftyspiffy/TwitchLib#54]
I noticed that if no argument is passed to OnChatCommandReceived e.ArgumentsAsString is set to the command without the modifier.  

For example a command like !stuff e.ArgumentsAsString will be set to 'stuff' but for !stuff 123 e.ArgumentsAsString will be '123' shouldn't e.AgrumentsAsString just be empty or null if nothing is passed?

thanks.

**Comment by swiftyspiffy** [comment]
Yup, you're right. Will fix this when I get home.

**Comment by swiftyspiffy** [comment]
This should be fixed with 6200801e952e2b7d4ea19b5071556cd81cd305e1 . I'll push a new NuGet version later tonight unless you find issue with it. Will close this issue when new NuGet version is out.

**Comment by zerocarbthirty** [comment]
Thanks man, do you think it would be possible to add a "command separator" so that if someone does something like !stuff "hi my name is dave" that would be a single argument and !stuff hi my name is dave would be multiple arguments? right now I am just joining them on commands that only accept one argument but that has terrible limitations.

**Comment by swiftyspiffy** [comment]
Yup, I can add that.

**Comment by swiftyspiffy** [comment]
Some clarification here. If you do !stuff "hi my name is dave", would that command then ONLY accept arguments that have quotes. In other words, it would only work in the following way:
`!stuff "hi my name is dave" "and I like root beer"`
as opposed to something that has both quoted arguments and non quoted arguments as such:
`!stuff "I want how many this many root beers" 5`
Where you have a mix of both. The parsing job gets tricky when you have both quoted arguments and non-quoted arguments.

**Comment by swiftyspiffy** [comment]
Nevermind, I've got a way to recognize both :)

**Comment by zerocarbthirty** [comment]
Well its primarily only useful for things like:

!addquote "something crazy the streamer said" but it would be cool if you
could have things like

!addcom blah "blah blah blah"

if i didnt mention it im using your class for a channel moderation bot I am
making. thanks by the way for the work you have done.

**Comment by swiftyspiffy** [comment]
Are you able to pull the code in the github project and build it and test locally? I have a solution that I think should work, but not totally sure how stable it is. I tested it a bit and it seems to work.

**Comment by zerocarbthirty** [comment]
I will pull it Monday. thanks!!

**Comment by swiftyspiffy** [comment]
Sounds good! Thanks :)

**Comment by swiftyspiffy** [comment]
If you can give this a go and let me know if it works as expected, that'd be awesome :+1:

**Comment by swiftyspiffy** [comment]
I'll assume this has been implemented correctly, and close this 💃

**Comment by zerocarbthirty** [comment]
Hey Cole,

I just wanted to ask really fast but is there a method in twitchlib to
convert emotes into their URL or to grab the actual emote image? if not I
can hack this together!

thanks for all of the hard work buddy.
