### ISSUE TITLE
Getting Bot Account from received message

### ISSUE THREAD

**Issue by toffaste1337** [swiftyspiffy/TwitchLib#55]
How do I get the bot that received a message from TwitchClient.OnMessageReceivedArgs ?
Is that e.ChatMessage.DisplayName?

Edit: NVM just tested it, cant seem to find out how to get the bot receiving the message without using the raw irc message.

Edit again: realized I cant really get it from the raw irc message either.

**Comment by swiftyspiffy** [comment]
Looks like I forgot to update ChatMessage with a 'Channel' property. I will fix this when I get home.

Additionally, I will look into the issue ChatMessaage not parsing correctly.

**Comment by swiftyspiffy** [comment]
Should be noted though, I have a bot in production right now that is using the latest NuGet version fine, so perhaps try uninstalling and reinstalling the library?

**Comment by toffaste1337** [comment]
Yeah, I always had the Channel property. But I'd like to get the TwitchClient that received the message. If I have more than 1 bot connected to the same channel, doing different things, even though this doesn't seem logical, I'd like this to be an option. 
Not very much needed, but would maybe serve a better purpose later on?

**Comment by swiftyspiffy** [comment]
So perhaps a BotUsername property would be beneficial?

**Comment by toffaste1337** [comment]
That would be nice yeah. Also if it doesnt require a lot, pass the TwitchClient too?

**Comment by igor523** [comment]
Ehh... Why not to use sender parameter, that supplies with every event handler call? That's how you can get TwitchClient, that received a message

**Comment by swiftyspiffy** [comment]
True, you could get TwitchClient through `object sender`, and then access TwitchUsername, but it may be easier if each ChatMessage object had an identifier indicating which TwitchClient it originated from.

**Comment by toffaste1337** [comment]
I tried to get the TwitchClient from object sender, but couldn't find out how.
How would I do that?

**Comment by igor523** [comment]
Use this code:


TwitchClient chat = sender as TwitchClient;

If sender is really TwitchClient, then chat will be your client. chat will be an null otherwise.
But this pattern requires publisher side (e.g. Cole's code) to Invoke event properly, to make it work, and I'm not sure if Cole did this requirement, so give it a try and tell us a result =)

**Comment by swiftyspiffy** [comment]
Actually, I just realized, I've been setting the `sender` argument as null in all event invocations, I think. I will fix this when I get home as well.
I've been doing this out of habit, it is a bad habit.

**Comment by toffaste1337** [comment]
`TwitchClient client = (TwitchClient)sender;
            if(client == null)
            {
                MessageBox.Show("client == null");
            }
            else if(client != null)
            {
                MessageBox.Show(client.TwitchUsername.ToString());
            }`

this returned "client == null"

**Comment by swiftyspiffy** [comment]
For example: `OnViewerTimedout?.Invoke(null, new OnViewerTimedoutArgs`

Yes, sorry about that. What you're doing is correct, and my bad habit has made it impossible to be used. I will fix all event invocations with the proper sender, as well as add a BotUsername, and fix the ArgumentsAsString bug the other guy mentioned and send out a new NuGet version.

Sorry about that.

**Comment by toffaste1337** [comment]
No worries, you're doing a great job at this :)

**Comment by igor523** [comment]
Well, it's not that hard, actually. Just replace null with this in all event invokes =)

**Comment by swiftyspiffy** [comment]
Yup, can't do it at the moment as I'm at university, but when I get home I will :100:

**Comment by igor523** [comment]
*a little of offtop* Funny, I forgot about time zones... It's 22:25 in my city =)
Okay, as for toffaste1337's request, I think, you should think twice about architecture of your app. My own bot uses modular system with dozens of modules, each of them receiving and sends messages and all what I need in every module is a link to one TwitchClient, maintaining all of the modules. Well, of course I don't see full picture, maybe you really need that feature in your project. But maybe there is more elegant way to do the same? =)

**Comment by toffaste1337** [comment]
Well, what I have is an interface to add bot accounts manually, and also a webpage for users to get the a bot of their name or choose to use my bot name. If they want their own, it will add a new bot, and well, not likely, but possibly they could add more than 1 bot to the same channel. Or I would do it to make an AI responder with another account to respond to questions in a chat more "human". I currently did not find a way to send the message with a specific bot without getting the TwitchClient or Bot TwitchUsername from the event.

**Comment by igor523** [comment]
Okay, I've got it =)

**Comment by swiftyspiffy** [comment]
Event invocation fix should be applied with this: 013711d437119922c3437b473789f83e700a30a2
BotUsername should be applied with this: 6c66f8c7f760e52efdeff10fa06367c77bbde71f

Unless either of you find issue with either of these, I will push a new NuGet version later tonight. Will close this issue when that new version is available.

**Comment by toffaste1337** [comment]
both client.TwitchUsername and BotUsername returns an empty string.

**Comment by swiftyspiffy** [comment]
Sigh, I forgot I messed with that when I did the JoinedChannel support. Should be fixed with 7608b449488c8655663798ebd2268815fe68ab43

**Comment by toffaste1337** [comment]
`private void globalChatMessageRecieved(object sender, TwitchClient.OnMessageReceivedArgs e)
        {
            MessageBox.Show(e.ChatMessage.IsModerator.ToString() + " " + e.ChatMessage.Message + " " + e.ChatMessage.DisplayName + "\r\n" + e.ChatMessage.BotUsername);
            executeCommand(e);
        }`
Does not show the bot username

**Comment by swiftyspiffy** [comment]
Give it another try :)

**Comment by toffaste1337** [comment]
Was just about to :dancer:

**Comment by toffaste1337** [comment]
Great! Works perfectly :+1:

**Comment by swiftyspiffy** [comment]
Awesome!
