### ISSUE TITLE
Client disconnects when leaving last JoinedChannel

### ISSUE THREAD

**Issue by toffaste1337** [swiftyspiffy/TwitchLib#57]
If I leave all channels the client will get disconnected and I have to reconnect it in order to join a channel again. Is this intended? 

Also, please tell me if I'm opening too many issues :smiley_cat:

**Comment by swiftyspiffy** [comment]
You're fine :) I have not tested with leaving multiple channels, only leaving a single channel. Let me test a bit and get back to you.

**Comment by swiftyspiffy** [comment]
It looks like it's actually crashing when the last channel in the JoinedChannels list is left (PARTed).

**Comment by toffaste1337** [comment]
Yeah, as my current code goes, I have to restart if I would ever leave all channels, since I made it impossible to add the same account twice.. not doing tests to check if the client actually still is connected. But found this some hours ago and wanted to just test a bit before submitting it.

**Comment by toffaste1337** [comment]
I guess you already got this, but when leaving all channels now I get an error on line 379 in ChatParsing.cs

**Comment by swiftyspiffy** [comment]
Yup, I know what the error is, I think. Give me a second and I'll have a new commit.

**Comment by swiftyspiffy** [comment]
Sorry it's taking me a bit, ran into another potential issue with a use case.

**Comment by toffaste1337** [comment]
All ok, this wont be a problem for my usage at the moment, but I guess that crash should't be a feature :laughing:

**Comment by swiftyspiffy** [comment]
Alright, I'm a bit worried about the code I just pushed, but give it a try and let me know what you think.

**Comment by swiftyspiffy** [comment]
I think I broke other stuff with that commit. This is turning out to be more challenging than I had thought :)

**Comment by toffaste1337** [comment]
Works to leave all channels per bot now, and the connection is still active when I join a channel again.
Nothing seems to have been broken for me atleast.. will run it for a while

**Comment by swiftyspiffy** [comment]
Ya, please do. I am running mine in sort of production as well. There might be issues with chat parsing, which is what I am worried about.

**Comment by swiftyspiffy** [comment]
So far the only unaccounted for messages I have are:
`Unaccounted for: :tmi.twitch.tv PONG tmi.twitch.tv :irc.chat.twitch.tv`

**Comment by swiftyspiffy** [comment]
As a heads up, I just did a lot of commits to get Travis CI passing without errors/warnings. I'll continue running this to see if anything funky happens. It appears to be working. When my main streamer goes live tonight with a bot running the library and nothing happens, I'll probably make a NuGet package.

**Comment by toffaste1337** [comment]
Seems good! Nothing wrong here :+1:

**Comment by swiftyspiffy** [comment]
This fix seems to be functional in the latest NuGet version, so I will go ahead and close this.
