### ISSUE TITLE
ClientID no longer working for everything

### ISSUE THREAD

**Issue by D3thw0lf** [swiftyspiffy/TwitchLib#58]
They've changed some things with the ClientID
https://blog.twitch.tv/client-id-required-for-kraken-api-calls-afbb8e95f843#.n4rj5cv5b

Just to inform you :)

**Comment by Examed** [comment]
Nice you already posted it here ^^. Now everything needs a ClientID

**Comment by D3thw0lf** [comment]
Yeah sorry for that Headline.

I've just wanted to say that just TwitchApi.SetClientId("YOURID"); is no longer working the way it should or has before. :3

Btw. I guess the Servers are responding very sluggish atm. anyone else with that "Feeling"? It took me 30 or more seconds to have a Chat Connection. :/

To make it clear: I've a 100Mbit/s Connection (100 Down, 6/7 Up) ... 

I think the new ClientID stuff seems to slowing everything down. :(

**Comment by swiftyspiffy** [comment]
I just tested with the example application a couple calls and it seems to be working. Can you explain a bit more?

**Comment by D3thw0lf** [comment]
Hmn ok then I've to recheck everything. Yay! 😭

**Comment by swiftyspiffy** [comment]
Let me know if you come up with something. I set client Id using SetClientId("id") and then made the call, and they appear to be working.

**Comment by D3thw0lf** [comment]
I guess I've got it to work again. Had to add Change my restclient to this:
`var client = new RestClient("https://api.twitch.tv/kraken/channels/" + this.appSettings.LastChannelName + "?client_id=ID";`

to grab Status, Game, Logo etc.

**Comment by swiftyspiffy** [comment]
I can add that GET parameter in addition to the client id header to be absolutely certain it's being sent to Twitch.
