### ISSUE TITLE
e.ChatMessage.UserType seems to always return "Broadcaster"

### ISSUE THREAD

**Issue by zerocarbthirty** [swiftyspiffy/TwitchLib#60]
This issue refers to TwitchClient.OnMessageReceivedArgs

If I set SetLoggingStatus(true) and watch the log, when a broadcaster says something it looks like this:

"user-type= "

When a mod says something it looks like: "user-type=mod "

but it appears that e.ChatMessage.UserType always returns "Broadcaster".

Am I doing something wrong or is this just a bug?

**Comment by swiftyspiffy** [comment]
Nope, that looks like a bug. When I talk in my own channel, I get assigned the `mod` user type as seen below:
`user-type=mod :swiftyspiffy!swiftyspiffy@swiftyspiffy.tmi.twitch.tv PRIVMSG #swiftyspiffy :asd`

The easy fix for this I think is just to check if the sender name is the same as the connected twitch channel, and if yes, then set the user type to broadcaster.

Regarding the always "Broadcaster" user type, that is odd. When I first implemented it, it seemed to work. I will verify this now.

**Comment by swiftyspiffy** [comment]
Wow, found the bug. Thanks for pointing this out. Comparing Channel to Channel will always return true lol.
![Image of Bug](http://swfty.xyz/?id=979u02592)

**Comment by swiftyspiffy** [comment]
Just pushed the new NuGet version out, should fix this problem. Feel free to reopen this if you think it isn't.

**Comment by zerocarbthirty** [comment]
Yea on mine that var is always set to broadcaster but the other ones change.

**Comment by swiftyspiffy** [comment]
Can you explain a bit more? Not sure I understand.

**Comment by zerocarbthirty** [comment]
The event handler that handles messages sent to the channel has a variable
called usertype (defined in your library) for some reason that variable is
always "broadcaster"

**Comment by swiftyspiffy** [comment]
Right, is that still the case in the latest NuGet package? (v`1.2.5`)

**Comment by zerocarbthirty** [comment]
ohhh I dunno im still on an old one. let me check!

**Comment by zerocarbthirty** [comment]
Hi,

So I got around to upgrading twitchlib in my project and it seems as though
many things have changed.

It looks like SendMessage() no longer just accepts a message?

Do you have any idea what the new syntax is?

This worked before I updated =) client.SendMessage("Hello!");

**Comment by swiftyspiffy** [comment]
Right, a new parameter for a JoinedChannel object was added to support a single client joining multiple channels (via `client.JoinChannel("channel");`). If you only plan on joining a single channel, you can get away with something like:
`client.SendMessage(client.JoinedChannels[0], "Hello!");`

**Comment by zerocarbthirty** [comment]
Hurray, it now knows that not everyone is a broadcaster, thanks for adding
the additional event handlers too about the timeouts and bans, I will have
a lot of fun with that one.

Is there any way to detect when someone else hosts MY channel? I thought
that was what THIS did: TwitchClient.OnHostingStartedArgs but it seems like
it responds when my channel hosts someone else.. haha

one thing I did notice in the new version is that this:

TwitchClient.OnConnectedArgs no longer has a 'channel name' arg. I think
this is probably because of the change you made which allows multiple
channels?

**Comment by Examed** [comment]
TwitchApi.SetClientId(Properties.Settings.Default.TwitchClientId);
foreach (string host in await TwitchApi.GetChannelHosts(Channel))
{

}

**Comment by swiftyspiffy** [comment]
Correct, OnConnected is fired when the client connects to Twitch (before joining a channel). I am adding an event now that fires when a join is successful. I always get confused with the Host related events, but yes I think `OnHostingStarted` was supposed to do that,with `OnHostLeft` firing when your channel stops hosting someone (because they went offline).

Additionally, Examed is correct, for the time being you can use the API, but I understand that doesn't give you real time results.

**Comment by swiftyspiffy** [comment]
Also, `SendMessage("Hello!")` should work again with this next push, i have a few wrapper methods to improve accessibility for people less familiar with the library.
