### ISSUE TITLE
PubSub Support

### ISSUE THREAD

**Issue by swiftyspiffy** [swiftyspiffy/TwitchLib#61]
I'd like to begin implementing Twitch's new PubSub system for more in-depth event data.

**Comment by swiftyspiffy** [comment]
If anyone knows anything about Twitch's PubSub, I'm all ears. Currently trying to learn how it works. I just pushed some groundwork code that is able to send requests to PubSub successfully.

**Comment by swiftyspiffy** [comment]
BTTV's implementation of PubSub's chat_login_moderation topic for reference: https://github.com/night/BetterTTV/blob/e4b09b8246e49bfb687c5f69178a0da17b4dc24d/src/js/chat/takeover.js#L105

**Comment by swiftyspiffy** [comment]
Support for timeouts, bans, and unbans successfully added and tested 💃

**Comment by Examed** [comment]
awesome I have to look test that new feature 👍

**Comment by swiftyspiffy** [comment]
It looks like PubSub is disconnecting after around 10 minutes. I think this is due to Pings not being sent. I will work on this now.

**Comment by swiftyspiffy** [comment]
Looks like a 3 minute PING timer applied to pubsub has fixed the disconnect issue after 10 minutes. Pushing this fix now.

**Comment by swiftyspiffy** [comment]
Just added support for bitsevents as well! Won't be able to test until tonight though (when my streamer goes live).

**Comment by Examed** [comment]
awesome :) 👍

**Comment by swiftyspiffy** [comment]
I can confirm the bits event works 💃

**Comment by swiftyspiffy** [comment]
Added video-playback, although can't confirm it works.

**Comment by Examed** [comment]
video-playback ? what data provides that event ?

**Comment by swiftyspiffy** [comment]
From what i read, video-playback should give an event on stream up, stream down, and periodic updates of viewer count. Though I've seen some chatter of it not working/being sporadic.

**Comment by Examed** [comment]
ohh that sounds nice

**Comment by swiftyspiffy** [comment]
I haven't been able to get it to work though, unfortunately.

**Comment by Examed** [comment]
ohh ok :)

**Comment by swiftyspiffy** [comment]
PubSub is supported to the extent (and more so) that Twitch publicly documents. I will open this again when Twitch openly supports more topics.
