### ISSUE TITLE
Resubscription events not being detected

### ISSUE THREAD

**Issue by swiftyspiffy** [swiftyspiffy/TwitchLib#62]
Twitch modified the userstate resubscription event message which is causing the detection code to fail (though not error, so stability should be good). Testing a fix now 💯

**Comment by swiftyspiffy** [comment]
Should be fixed with 1d1f07f40b455edd41afea20f87a62a2019e549d

**Comment by rlcx** [comment]
Hey, can you explain how do you test sub/resub/bits without subbing/resubbing and sending real bits ?

**Comment by swiftyspiffy** [comment]
Sure.
So, first you need to get the raw IRC of any subscription message. You can do this by listening to any large channel chat and waiting for a sub. Once a sub happens, copy the subscription message Twitch sends and store it somewhere. Then, when you wish to test parsing at a later date, call TwitchClient's `OnReadLineTest(oldIrcString)`, and pass in the old irc string you stored. The only time this doesn't work is if Twitch modifies the subscription event message, as was the case with this bug I made here.In this case, they added a field to the message for `id`, which needed to be accounted for in the parsing. So, I gathered a fresh IRC subscription message, and passed it through `OnReadLineTest` until my parsing worked for it.

Cheers :)

**Comment by rlcx** [comment]
Thank you for your answer ! I will try this `OnReadLine` asap =)

**Comment by swiftyspiffy** [comment]
You'll want to use `OnReadLineTest` 

Cheers

**Comment by swiftyspiffy** [comment]
Also, don't forget, you can set a breakpoint on the `OnReadLineTest` and investigate line by line the parse job of the library.
