### ISSUE TITLE
Check ConnectionCredentials

### ISSUE THREAD

**Issue by rafalrozek** [swiftyspiffy/TwitchLib#63]
How to check ConnectionCredentials is correct and my Twitchclient is now connected to channel?

**Comment by swiftyspiffy** [comment]
So, there are two events you want to subscribe to for details on those two. The first is `OnIncorrectLogin`, which will fire if the credentials are incorrect. The second is `OnConnected` which will fire once connected to the Twitch chat servers. Additionally, if you are passing in a channel in the initialization of the TwitchClient, you probably want to listen to `OnJoinedChannel` as this fires when you successfully join the channel, and gives you the OK to start sending messages in chat.

**Comment by swiftyspiffy** [comment]
I'm going to close this since it seems to have gone inactive.
