### ISSUE TITLE
DisplayName parsing bug

### ISSUE THREAD

**Issue by igor523** [swiftyspiffy/TwitchLib#64]
Hello!

There is a bug with nicknames that starts with numbers. DisplayName in OnMessageRecieved becomes blank

**Comment by igor523** [comment]
Example of wrong parsed raw irc string:
`@badges=;color=#0000FF;display-name=;emotes=;id=0cc6af85-7f1d-4c9a-b1e4-ab766710417a;mod=0;room-id=60265944;sent-ts=1475437438663;subscriber=0;tmi-sent-ts=1475437465250;turbo=0;user-id=43049091;user-type= :1990newbie!1990newbie@1990newbie.tmi.twitch.tv PRIVMSG #zhem4uzhinka :Пройти обучение, чтобы разблокирвоать доступ в меню игры )`

**Comment by igor523** [comment]
Raw string, that was parsed incorrectly:
`@badges=;color=#0000FF;display-name=;emotes=;id=0cc6af85-7f1d-4c9a-b1e4-ab766710417a;mod=0;room-id=60265944;sent-ts=1475437438663;subscriber=0;tmi-sent-ts=1475437465250;turbo=0;user-id=43049091;user-type= :1990newbie!1990newbie@1990newbie.tmi.twitch.tv PRIVMSG #zhem4uzhinka :Пройти обучение, чтобы разблокирвоать доступ в меню игры )`

**Comment by swiftyspiffy** [comment]
I will look into this now.

**Comment by swiftyspiffy** [comment]
@igor523 can you confirm that the message was parsed at all? When I test, it doesn't even get detected as a message.

**Comment by igor523** [comment]
But, well, this is the only nickname, that has problems. Any other was parces correctly, including nicknames without displayname in settings.

**Comment by swiftyspiffy** [comment]
Oh, I see what you're saying. That is a good idea. To my knowledge, the only difference between a DisplayName and username is that a display name can have capital letters customized by the user. I will implement your suggestion when I get home.

**Comment by swiftyspiffy** [comment]
Done 💯

**Comment by igor523** [comment]
Thank you! =)
Another request - what about implementing something like TwitchClient.GetModsList() to get list of channel mods. There is /mods command, but response to this command is being ignored as "Unaccounted for". Could be useful =)

**Comment by swiftyspiffy** [comment]
Yes, this is a very good idea. I think the best implementation would be to have a method that sends "/mods" and then an event fires when the response is received. I think I might even have the library throw an exception if the programmer calls GetModerators() without listening to OnModeratorsReceived or something just to help the programmer out.

**Comment by swiftyspiffy** [comment]
Implemented 💯 

You MUST listen to event `OnModeratorsReceived` otherwise you'll get an exception.
Send /mods command via `GetChannelModerators`. This method is overriden allowing for JoinedChannel  object, a string for the channel, or simply no arguments (in this case, it will send to the first-joined channel).

**Comment by igor523** [comment]
Great, thanks! Waiting for NuGet! =)

**Comment by swiftyspiffy** [comment]
Will have that out in a fe hours :D

**Comment by swiftyspiffy** [comment]
Sorry about the delay on this @igor523, sending out a new version now.

**Comment by swiftyspiffy** [comment]
Submitted, should be indexed in 20-30 minutes.

**Comment by igor523** [comment]
It's okay with delay.
Thank you, I'll test it soon =)
