### ISSUE TITLE
WillReplaceEmotes replacing emotes in OnChatCommandReceivedArgs

### ISSUE THREAD

**Issue by zerocarbthirty** [swiftyspiffy/TwitchLib#65]
Is there any way to implement the replacement of emote strings with their URLs in the arguments (`Command.ArgumentsAsList`) on a chat command or should I use `Command.ChatMessage.EmoteReplacedMessage`? 

Also when handling EmoteReplacedMessage is there a way to get twitchlib to automatically finish the IMG tag? or can someone recommend a good way to for example replace:
`//static-cdn.jtvnw.net/emoticons/v1/115846/1.0`
with
`<img src="//static-cdn.jtvnw.net/emoticons/v1/115846/1.0" srcset="//static-cdn.jtvnw.net/emoticons/v1/115846/2.0 2x" alt="ScaredyCat">`

thanks guys, twitchlib is awesome.

**Comment by swiftyspiffy** [comment]
I will look into this shortly, in the meantime, I'm going to format your post so we get the full message (instead of Github butchering it).

**Comment by swiftyspiffy** [comment]
Ya, I think `Command.ChatMessage.EmoteReplacedMessage` is the most appropriate for what you're trying to do. Regarding your second question, I can add a second property, maybe `Command.ChatMessage.EmoteReplacedMessageImgTags` or something that would include the image tags that you have suggested.

Let me know what you think.

**Comment by developerlegion** [comment]
I was working with the emote stuff yesterday and what I am trying to wrap my head around is this command only takes into account 1 phrase/word and return a url. I need the ability to either search a paragraph and replace all words that are emotes and leave the remaining words alone, or a way to do this with ChatMessage. Anyone have a suggestion for this, or maybe a property that can help with this?

**Comment by swiftyspiffy** [comment]
I think I understand what you're going after, but not totally sure how to go about it. Let me think about it for a bit.

**Comment by swiftyspiffy** [comment]
Sorry about the delay on this.

So, regarding the emotes in command arguments. I think your best bet is to utilize my newly added `EmoteSet` object (accessible via `ChatMessage.cs` and `WhisperMessage.cs` `EmoteSet` property). I would first check if `ChatCommand.ChatMessage.EmoteSet.Emotes.Count() > 0`, and if it is, then compare each emote in the `EmoteSet.Emotes` list against the `Command` string property, as well as the `ArgumentsAsList` list property.

Cheers.

**Comment by swiftyspiffy** [comment]
Meant to close this with my previous comment.
