### ISSUE TITLE
UpdateStreamTitle/Game error

### ISSUE THREAD

**Issue by hikyle** [swiftyspiffy/TwitchLib#66]
i'm currently getting a 400 bad request error when i try to update a stream title/game and i'm not entirely sure what i'm doing wrong.

i've set the clientid and i've tried allowing access with just channel_editor and all possible scopes with the correct access tokens and it's still the same response

edit; forgot to mention it works as it should for me using the generic curl
`curl -H 'Accept: application/vnd.twitchtv.v3+json' -H 'Authorization: OAuth <oauth>' -H 'Client-ID: <clientid>' -d "channel[status]=asdf" -X PUT https://api.twitch.tv/kraken/channels/<channel>`

**Comment by swiftyspiffy** [comment]
I'll look into this now.

**Comment by swiftyspiffy** [comment]
So I just tested `UpdateStreamTitle`, `UpdateStreamGame`, and `UpdateStreamTitleAndGame` and they all appear to work. These calls do not require a clientid (since the oauth token can is used instead). I would make sure your OAuth key has the right scope (`channel_editor`).

**Comment by swiftyspiffy** [comment]
As a side note, I tested using the Example Application provided in this project. Perhaps give that a try and try to implement in your own project using the example application.

**Comment by hikyle** [comment]
i'm not entirely sure whats going on as i can literally copy your MakeRestRequest/UpdateStreamTitle functions line for line, plug my details in and it works but once i try from TwitchApi.UpdateStreamTitle i get the bad request error

**Comment by swiftyspiffy** [comment]
I assume you are callig the TwitchApi function in an async method and awaiting the response, similar to how the example application does it?

**Comment by hikyle** [comment]
private async void button1_Click(object sender, EventArgs e)
        {
            await TwitchApi.UpdateStreamTitle(streamTitle, channelName, accessToken);
        }
is what isn't working for me and [this pastebin link](http://pastebin.com/fJ1Za9ea) contains the code that does work for me

**Comment by hikyle** [comment]
it appears to be working now. i downloaded and built the project myself instead of installing from the nuget repository

**Comment by swiftyspiffy** [comment]
That's odd. I'll give it a go from the NuGet repo and see what the deal is.

**Comment by swiftyspiffy** [comment]
Just tested and got the same error you were getting. Will have a fixed version on NuGet shortly.

**Comment by swiftyspiffy** [comment]
Alright it's indexed, looks like NuGet package version 1.2.9 has fixed it. Thanks for bringing the issue to my attention 💯
