### ISSUE TITLE
System.Nullreference Exception

### ISSUE THREAD

**Issue by jscoys** [swiftyspiffy/TwitchLib#69]
hi,

version 1.2.9 and all dependencies to the last version... i have a System.Nullreference Exception when i send messages to the chat of channels. it could arrive at 2-3 messages or after several messages.

i use the twitchlib example project. it throws this error on form1 so I can't investigate more...

**Comment by MagiusRerecros** [comment]
I updated my own project to use TwitchLib 1.2.9 via NuGet, and my client seems to send messages just fine. Personally, I'm using the SendMessage prototype where you only pass in the message you're sending, so it gets sent to the first JoinedChannel.

**Comment by swiftyspiffy** [comment]
And you seem to randomly get a NullReference exception? It could be on the first SendMessage call, or the fifth call?

**Comment by jscoys** [comment]
Ok I'm using the send message with 3 arguments. Will use the one you indicate, just with the message as argument

**Comment by swiftyspiffy** [comment]
Oh no, I was saying you get the NullRef randomly when you call SendMessage? Sometimes you get the exception the first time you call SendMessage, sometimes you get it the fifth time you call it?

**Comment by jscoys** [comment]
yes absolutely its totally random

**Comment by swiftyspiffy** [comment]
This is really weird, the only thing I can really think of is that the client is disconnecting (or not yet connected) when you are trying to send a message. And you are unable to set a breakpoint in the twitchlib example project to investigate further? Do you know what is null when you receive the exception? Surely it's not the client, but maybe the JoinedChannel that is either passed or the attempted fetch by the library.

**Comment by jscoys** [comment]
What is the application.run(new form1)

**Comment by swiftyspiffy** [comment]
That is default code that exists in every (CSharp?) .net application. Not related to the library at all.

**Comment by MagiusRerecros** [comment]
To perhaps be a bit more accurate, it's the default code that exists in every WinForms application; it's not really used in WPF applications. But the point still stands, it has nothing to do with the library, and you should be able to use breakpoints and debug inside of the Form1.cs code.

**Comment by swiftyspiffy** [comment]
Right, sorry for not going in depth^. If you can breakpoint and dive into the library, or at least surface level, you should be able to use the debug properties window to see what exactly is Null. That will significantly help us in solving the problem

**Comment by jscoys** [comment]
ok will try and give you feedback

**Comment by jscoys** [comment]
Sorry guys but can't find the problem. As you can see on the screen, I have a problem on nullReference on the form. What is weird is that happen randomly, not only when sending messages, but when the application is open without doing anything (Precise that I have one account connected to my channel).

I try to Step into but the app just close... Any idea?
![twitchlib error](https://cloud.githubusercontent.com/assets/6160983/19522511/7defd770-95e5-11e6-8e13-f5260abef0e3.png)

**Comment by swiftyspiffy** [comment]
That is really weird. I'm tempted ot say it has to do with that error you are seeing. Have you modified the example application at all? I don't get the await warning you are getting, and it might be a race condition that deadlocks the app, perhaps?

**Comment by jscoys** [comment]
ok will try to investigate more.

**Comment by swiftyspiffy** [comment]
I don't understand why it would be random though. That is really odd to me.

**Comment by D3thw0lf** [comment]
Getting the same error and thought it could be the older version I've used (1.2.1) ... updated to 1.2.9 now and same. even if nothing is happening the client crashes for no reason.

NLog says the following:
The Remoteserver returned an error: (400) Invalid request.

Seperated all Twitchlib related console output after crash:
`TwitchLib.TwitchApi.&amp;lt;MakeGetRequest&amp;gt;d__47.MoveNext()
TwitchLib.TwitchApi.&amp;lt;GetTwitchFollowers&amp;gt;d__28.MoveNext()
TwitchLib.Services.FollowerService.&amp;lt;_followerServiceTimerElapsed&amp;gt;d__24.MoveNext()`

Full console output:
http://pastebin.com/V2zDVk7y

**Comment by swiftyspiffy** [comment]
So the follower service was causing unpredictable crashes? That's really odd. I'll look into it when I get home.

**Comment by swiftyspiffy** [comment]
Sorry about the delay. I was able to reproduce this, fixing now.

**Comment by swiftyspiffy** [comment]
The appears to be on Twitch's end. I am going to make a post about it on the dev forums, and in the mean time, I guess I'll just have GetTwtichFollowers call catch 400 web exceptions. Thanks for bringing this to my attention @D3thw0lf and @jscoys

**Comment by swiftyspiffy** [comment]
The issue appears to be resolved with the latest code I submitted. Feel free to reopen this if you see the issue again.
