### ISSUE TITLE
OAuth Token Authentication Issues

### ISSUE THREAD

**Issue by elu00** [swiftyspiffy/TwitchLib#70]
Hi,
When entering in an oauth token, should the "oauth:" portion be included or excluded in the string? I've tried both ways with the same results.
I'm having trouble authenticating and using the library currently.
Here's my test code:

```
string username = my_channel;
string oauth = "xxxxxxxxxxxxx";
string channel = my_channel;
TwitchClient client = new TwitchClient(new ConnectionCredentials(username, oauth), channel);
client.SendMessage(my_channel, "Test");
Console.WriteLine(client.TwitchUsername);
Console.WriteLine(client.IsConnected);
 Console.WriteLine(client.JoinedChannels[0].Channel);
```

Which returns the correct username, false, and an `OutOfRangeException`.
Is there something I'm missing? Do I need to manually start the connection to the IRC sever?
Thanks!

**Comment by swiftyspiffy** [comment]
Hi there, I'm going to format your post, and then respond to you shortly.

**Comment by swiftyspiffy** [comment]
Regarding your first quesiton on oauth suffix, yes you need it if you are using the NuGet package. However, if you are using the latest GitHub code, I just added a check that makes it so you don't need to have it (it's optional).

Regarding your second part, you need to call Connect() on the client after initializing it, as such:
```
TwitchClient client = new TwitchClient(new ConnectionCredentials(username, oauth), channel);
client.Connect();
```
(This was not originally part of the example implementation in the README, I have since added it)

Additionally, to detect when the client has connected and joined the channel, you want to listen to the `OnJoinedChannel`. To do this, you'll need a method that is fired when the event happens, and subscribe to the client's `OnJoinedChannel`. Example:
Method to fire on event:
```
public static void clientJoinedChannel(object sender, TwitchLib.TwitchClient.OnClientLeftChannelArgs e)
{
        client.SendMessage(my_channel, "Test");
        Console.WriteLine(client.TwitchUsername);
        Console.WriteLine(client.IsConnected);
        Console.WriteLine(client.JoinedChannels[0].Channel);            
}
```
and subscribe to event:
```
client.OnJoinedChannel += clientJoinedChannel;
```

I would highly recommend you check out the Example application provided in this project. It has examples on how to do almost everything.

**Comment by elu00** [comment]
@swiftyspiffy Alright, thanks so much for your reply!
Sorry, I'm really new to C# and the whole event/delegate model, and I didn't see the Connect command in the sample project. 
Another question that's honestly pretty stupid: how do I prevent the application from exiting before the event fires? Running into that issue with this implementation and the other project I'm working on.
Thanks again so much for your work on this project!

**Comment by swiftyspiffy** [comment]
Assuming you're referring to a ConsoleApplication, you'll want to read input. If you want to read input repeatedly, you want to do a loop for it. Something like:
```
while(true) {
        Console.ReadLine();
}
```

This will continually read input from the keyboard without exiting.

**Comment by elu00** [comment]
Alright, sorry for troubling you with that. I've now compiled the example project in this repo, and after inputting my credentials in the form, I'm unfortunately still unable to receive or send any messages at all. Is there anything I might be missing or doing wrong? I'm using the latest commit from github, if that matters, and I've also verified that the credentials work through WebIRC clients.
Thanks again for your patience and replies.

**Comment by swiftyspiffy** [comment]
Just to confirm, you are putting your username into the User textbox, and your oauth into the OAuth textbox, then in the CHannel textbox you're putting a channel, and then clicking Add, correct? And are you getting an exception I assume?

**Comment by swiftyspiffy** [comment]
And no worries, glad to help 👍

**Comment by elu00** [comment]
Yeah, I'm putting in the correct username/token, clicking add, and then attempting to send/receive messages through the appropriate tabs. Would it help at all if I PM'd you my oauth token and username? It's a throwaway account anyways that I made yesterday, so nothing important is linked to it.

**Comment by swiftyspiffy** [comment]
ya, if you want to. It would at least allow me to test it. When you click add, you should see some messages in the output box in Visual Studio indicating connection is attempting to be made to Twitch.

**Comment by elu00** [comment]
Alright, emailed you the credentials!

**Comment by swiftyspiffy** [comment]
Just responded with a video of my logging in and sending/receiving chat and whispers.

**Comment by elu00** [comment]
Alright, looks like something was just janky with the network my school. Thanks for your help!

**Comment by swiftyspiffy** [comment]
Awesome, that's what I thought it was. Glad you got it working!
