### ISSUE TITLE
Feature Request - More information in OnMessageSent

### ISSUE THREAD

**Issue by developerlegion** [swiftyspiffy/TwitchLib#72]
Basically what I would like to see is some of the same properties available to regular messages added to the method. properties like DisplayName, Badges and if possible Emotes. Currently what I see is just the name and message.. at least what I am using anyways.

**Comment by swiftyspiffy** [comment]
The only way I could see this happening is instead of firing OnMessageSent when the client sends the IRC data, it fires when the library sees a message in chat from the connected username, which i guess would work.

I will look into this.

**Comment by developerlegion** [comment]
Thanks. Before I used your library, I was coding this out myself and was just getting to this, so I understand. I know during my initial testing by hand the raw data coming back wasn't the same. I figure their has to be a way since their chat does it.

**Comment by swiftyspiffy** [comment]
So using the library, when I send a message, I am not receiving that message in the form of a received message. I am not sure if this is because the underlying IRC library (smartirc4net) is ignoring them, or if Twitch is not sending them back.

Will continue looking into it.

**Comment by swiftyspiffy** [comment]
If you want to give the latest GitHub code a try, I put all information Twitch sends me into a SentMessage object that you can use. It's not as much as the ChatMessage object, but there's a good amount there.

**Comment by developerlegion** [comment]
Thanks, I will check it out

**Comment by swiftyspiffy** [comment]
Oh no, I don't think the code is stable enough at the moment for a NuGet release. You'll need to pull a copy from this GitHub repo, and build it on your computer.

Sorry :(

**Comment by developerlegion** [comment]
Ok. I will see about doing that this weekend. I am going to move on to some other work on my bot for the time being. My goal is a fuller featured bot that can eventually replace Ankbot so I have plenty to do in the meantime.

**Comment by swiftyspiffy** [comment]
New NuGet package just uploaded with additions regarding OnSentMessage event (and many other things). Please let me know what you think.

Thanks!

**Comment by developerlegion** [comment]
Thanks, I will check it out tonight.

**Comment by developerlegion** [comment]
That seems to have done the trick... Thanks

**Comment by swiftyspiffy** [comment]
Awesome, I'd like to add more info, but unfortunately that is literally all the info I have at my disposal regarding sent messages.

I'll close this though 💯
