### ISSUE TITLE
Emotes to replace text

### ISSUE THREAD

**Issue by developerlegion** [swiftyspiffy/TwitchLib#73]
I asked about this in another issue, but thought it would be better to move it to its own issue ticket. I am currently taking the incoming messages and populating a Paragraph in a RichTextBox. In the ChatMessage  you have EmoteReplaceMessage & EmoteSet.  What I need is a Collection that has the id, and word, and possibly even the url so that I can search the paragraph that has been populated with the ChatMessage.Message and replace any word in that paragraph with the proper emote. I am not sure how other devs are doing this, if this has been done and I am just not finding it. I know twitch has a url that will bring back a collection that has the ids and keywords with them, so if your library has it and I just haven't found it yet, if you could point me in the right direction I would appreciate it.. If not, I guess its a feature request.

**Comment by swiftyspiffy** [comment]
Sorry I haven't responded to this. It's a bit more complicated as far as usecase goes than other issues. Give me a bit more time. I will leave this open.

**Comment by developerlegion** [comment]
No problem. I am moving on to other things right now anyway, so I can come back to it later.

**Comment by swiftyspiffy** [comment]
Sorry about the delay on this.

I added an EmoteSet object that is represented via the `EmoteSet` property in both WhisperMessage.cs and ChatMessage.cs . The object contained the emote name, the link to the image, the starting index, and the ending index.

Cheers :)

**Comment by swiftyspiffy** [comment]
Meant to close this with my previous message.
