### ISSUE TITLE
TwitchPubSub

### ISSUE THREAD

**Issue by NaNDiva** [swiftyspiffy/TwitchLib#74]
Hi Swifty
Nice Library

I wonder if you can give me pointers on using the TwitchPubSub?

No matter what I do I cannot seem to get authenticated. I receive an ERR_BADAUTH response from the listener. I've tried

`TwitchPubSub.ListenToChatModeratorActions(modId (from Api), StreamerId (from api), $"oauth:{OauthTokenForMod}");`

`TwitchPubSub.ListenToChatModeratorActions(modId (from Api), BroadcasterId (from api), $"{OauthTokenForMod}");`

`TwitchPubSub.ListenToChatModeratorActions(BroadcasterId(from Api), BroadcasterId (from api), $"{OauthTokenForBroadcaster}");`

and

`TwitchPubSub.ListenToChatModeratorActions(BroadcasterId(from Api), BroadcasterId (from api), $"oauth:{OauthTokenForBroadcaster}");`

Every single listen attempt gives me back a ERR_BADAUTH response from PubSub, then the connection closes after 15 seconds (which is expected because an authenticated session has not been setup)

**Comment by swiftyspiffy** [comment]
So in my bot I maintain, this is the way I do it, notice the listen command is sent in the `onConnected` event.

```
public static void onConnected(object sender, object e)
{
        Common.PubSub.ListenToChatModeratorActions(66137196, 44338537, "oauth_token");
}
```

Where `66137196` is my Twitch account (swiftyspiffy) ID, `44338537` is the account ID of my broadcaster  (burkeblack), and the oauth token does not have the "oauth:" prefix

It should go without saying your twitch ID should be a moderator on the broadcaster's stream.

**Comment by NaNDiva** [comment]
That's exactly how I'm doing it.

I've even tried using the direct example in the example project. I just can't seem to get authenticated. I've tried as me, with my oauth, as the modded bot account and the broadcaster. Do I have to acquire special scopes on the oauth generation?

**Comment by NaNDiva** [comment]
Also the user ids are just _id returned in a User Object from a request to the kraken users endpoint aren't they?

https://github.com/justintv/Twitch-API/blob/master/v3_resources/users.md#get-usersuser

**Comment by swiftyspiffy** [comment]
That is correct. Your OAuth token shouldn't be the problem either, as any scope should work. Hmmm.

**Comment by swiftyspiffy** [comment]
Just ran my bot to check, and it still seems to be working:
`[TwitchPubSub] onOpen!`
`[TwitchPubSub] {"type":"RESPONSE","error":"","nonce":"lGQNCeh7"}`

**Comment by swiftyspiffy** [comment]
There's not a whole lot of information available about this topic because it's not supported or documented by Twitch. I happened to stumble across it when I was reading up on PubSub.

**Comment by NaNDiva** [comment]
I setup a new console project, added TwitchLib, and setup twitchpubsub and everything was fine in there, so I uncommented it in my app recompiled and ran and now it's fine o.O

Perhaps it took a while for the oauth to become active?

I've no idea. Or the service was down this morning. Sorry to have wasted your time :(

**Comment by swiftyspiffy** [comment]
No worries! Hopefully twitchlib helps your project out a bit!

**Comment by NaNDiva** [comment]
Oh it already has. Thanks for your hard work on it. I've been lurking using it since the day after the first nuget upload :P

**Comment by swiftyspiffy** [comment]
Awesome, well enjoy it, and feedback is always welcome!

I'll close this now :)
