### ISSUE TITLE
Simple Question, probably a tiny fix possible as well.

### ISSUE THREAD

**Issue by mikaelssen** [swiftyspiffy/TwitchLib#76]
Why is the 
`  TwitchLib.TwitchAPIClasses.Stream stream = await TwitchApi.GetTwitchStream(command.ChatMessage.Channel);`
only able to get VideoHeight and not Width?

**Comment by XuluniX** [comment]
It seems like there is no VideoWidth returned from the API.
So the only way to to get the width would be to either calculate it from the aspect ratio (16:9) or to use a table to find the matching width for the returned height.

**Comment by mikaelssen** [comment]
That's really weird.. guess i'll just fetch the video object or something and extract it from that?.. as one can't really assume one has a 16:9 ratio on everything.

**Comment by swiftyspiffy** [comment]
@XuluniX is correct, only VideoHeight is available at the Streams endpoint. It is possible to scale that to generate a width, not sure if it's really needed though.

Endpoint: [https://api.twitch.tv/kraken/streams/{broadcaster}](https://api.twitch.tv/kraken/streams/)

**Comment by mikaelssen** [comment]
Only need if someone would like to check their settings by a twitch bot and ensure that everything is 'neat'. but scaling on a 16:9 basis would make a lot of errors, especially for people with 16:10 ratios.  but w/e put this under 'weird things twitch does' and we'll call this closed.
