### ISSUE TITLE
TwitchApi.CommercialLength typo?

### ISSUE THREAD

**Issue by frackalope** [swiftyspiffy/TwitchLib#80]
I noticed that "Second120" does not conform to the plural version of all the other types such as "Seconds150, Seconds180, etc..."  Was this intentional or just an oversight?

**Comment by swiftyspiffy** [comment]
You're right, it is a typo. I can fix it when I get home in a few hours.

**Comment by frackalope** [comment]
Groovy, Thanks!

**Comment by swiftyspiffy** [comment]
Fix pushed in commit: 667b62405c536bee8b50e8cec06df6e50d177f34

Thanks again! I'll close this now :)
