### ISSUE TITLE
Support Twitch API v5

### ISSUE THREAD

**Issue by swiftyspiffy** [swiftyspiffy/TwitchLib#83]
Twitch API v5 was just supported,. A key change will be moving from username to user ID. This impacts a good amount of TwitchApi class in TwitchLib.

**Comment by swiftyspiffy** [comment]
As a side note, documentation will arrive for v5 in mid-December, so a majority of work for this issue will need to wait a few weeks.

**Comment by D3thw0lf** [comment]
Nice! Keep up your good work. 👍

**Comment by swiftyspiffy** [comment]
Initial support: 3fce04c2e8e8777239b1920494744be07c3823c6

**Comment by swiftyspiffy** [comment]
Supported.
