### ISSUE TITLE
Some TwitchApi calls swallow exceptions

### ISSUE THREAD

**Issue by Danatobob** [swiftyspiffy/TwitchLib#84]
When long ago I've tried to use `GetTwitchStream(string channel)` I did not understand why I'm always getting null in return. I thought that maybe TwitchLib is outdated or i need to pass channel with some prefix or something. Only when I've looked up the source code I've realized that MakeGetRequest probably fires an exception because both `ClientId` and `accessToken` are null.
This came as a surprise because I've already been successfully using `UpdateStreamTitleAndGame(string status, string game, string channel, string accessToken = null)` without doing anything else. I was certain that if the method needs something, it would ask this via parameters so I had no idea SetClientId exists and must be used prior to GetTwitchStream call, so the message in (swallowed) `InvalidCredentialException` would have been useful.

I assume that swallowing exceptions were intended for random http errors and stuff like that, so I suggest that only `InvalidCredentialException` should be rethrown.
EDIT: Actually I've noticed that TwitchLib tries to explain http errors also in regards to twitch (handleWebException), so maybe swallowing all that information was not intended ?

**Comment by swiftyspiffy** [comment]
This is a good issue. A lot of earlier code was very lazy, hastily done and not a lot of thought put into it. Virtually the entire TwitchApi could use some work with exceptions and how data is returned.

If I understand you correctly, unauthenticated calls should work with either client Id, or oauth token, instead of absolutely requiring a client Id (this makes sense to me). Random http errors should be bubbled up, and specific http errors should be handled with an exception that helps the user of the library understand why the exception was thrown (BadResource, BadScope, InvalidCredentials, etc).

**Comment by Danatobob** [comment]
> If I understand you correctly, unauthenticated calls should work with either client Id, or oauth token, instead of absolutely requiring a client Id (this makes sense to me).

Since I haven't read Twitch API specs, I didn't even realize ClientId is not required if oauth token is provided. My old solution back then was to copy-paste internal code of GetTwitchStream into my project and provide both ClientId and oauth token just to be safe ;). Yeah if any of them is enough, I'd like the TwitchLib API to reflect that, so I could use both UpdateStreamTitleAndGame and GetTwitchStream the same way (via oauth token).
Regarding exceptions like `BadResource, BadScope, InvalidCredentials` - yea those would be useful to receive since they are about using TwitchApi properly. 
Http errors are also okay I guess. Though I think they might also happen in async continuation of `await new StreamReader` (I've no idea how async http works, just thinking) and would require more handling.

**Comment by swiftyspiffy** [comment]
Hi, sorry about the delay on this.

I have created a branch with some changes mentioned in this issue. The changes are listed below, and available in the branch 84.

- `MakeGetRequest` now checks if `ClientId` AND `accessToken` (passed in string) AND `AccessToken` (saved string) are all null before throwing the `InvalidCredentialException`.
- `GetTwitchStream` now throws `StreamOfflineException` if the stream is offline.
- `GetTwitchStream` now throws `BadResourceException` if the passed in channel is invalid.

**Comment by Danatobob** [comment]
Allright, I've looked through the changes. The exceptions are okay now, though I'd like the InvalidCredentialException to also mention SetAccessToken(). Something like "Set Client-Id/AccessToken by using SetClientId()/SetAccessToken()". I think you mentioned only SetClientId because accessToken sometimes is provided via parameters, but for GetTwitchStream for example that is not the case. This actually leads to a second question - do you plan on making GetTwitchStream have an accessToken parameter ? Because initially thats what confused me - GetTwitchStream doesnt ask for any credential information, yet complains that I didn't provide ClientId or AccessToken. I understand that if you add accessToken parameter, then this could lead to you making changes to every other method for consistency, so I'm not sure if you're heading in that direction.

**Comment by swiftyspiffy** [comment]
GetTwitchStream is not an authenticated call, so it does not require an access token (it can have one, not necessary though). All calls hitting the Twitch API however require a ClientId for identification.
If a ClientId is not set, but accessToken is passed or AccessToken has been set, the request should still work. Basically, Twitch needs a way to identify who is calling the api. The accessToken/AccessToken is only required when accessing private resources or when changing profile properties.

It's a bit confusing, let me know if you sort of understand.

**Comment by Danatobob** [comment]
I've read (finally) [Twitch API specs](https://github.com/justintv/Twitch-API) about this. It seems they _require_ ClientId in every request, yet as I understand it from your posts they don't really reject calls without ClientId. At least I've been successfully using UpdateStreamTitleAndGame with only accessToken. So my usage was incorrect then I guess.

Okay, with that out of the way, I still have a correction suggestion to InvalidCredentialException:
I remember when I've first read the exception message I was like "huh, how can I set clientId using a parameterless method SetClientId() ? This error is misleading." ;). Only later I've found out that this is a static method accepting a parameter. Not sure if everybody interprets that message the same way so up to you. The way I'm seeing a possible correction is smth like "SetClientId(...)" or "SetClientId(string)" or maybe even better "SetClientId method"

**Comment by swiftyspiffy** [comment]
Ya, I'm not sure if it specifically lists it, but I remember reading a response on the Twitch dev forum from a staff/engineer member that said that clientId or accessToken can be used to identify yourself, so both should (continue to) work.
As far as the SetClientId, I can get behind your suggestion. Give me a second to push that.

**Comment by Danatobob** [comment]
yes that is very clear. thank you.

**Comment by swiftyspiffy** [comment]
Cool, changes should be applied in #87 

Thanks again!
