### ISSUE TITLE
Message throttler might not help if offline for a few hours

### ISSUE THREAD

**Issue by Danatobob** [swiftyspiffy/TwitchLib#88]
When I've reconnected the failed bot after an 8 hours of broken state, the bot started spamming the channel with everything it had buffered during that time. It was a total of 60+ messages posted during a few seconds. If I wasnt the channel admin (100 messages per 30 seconds) I would have been already punished for that. Of course we are planning to fix the bot bugging like that, but I assume same thing would happen under normal circumstances when there is no internet for a few hours.
I've checked SmartIrc4net code and I think it fires OnWriteLine event when it actually writes something to the stream, so there might be a solution - delay sending new message until a write of previous message is confirmed.
EDIT: I've just realized its not supposed to delay messages, it just cancels them. Well, the idea still stands. I guess message throttler could buffer outgoing messages and cancel them only when confirmed writes reach allowed limit.

**Comment by swiftyspiffy** [comment]
Yup, I had someone else bring this up to me as well (the idea of buffering messages). I think it's a good idea.

**Comment by Danatobob** [comment]
Btw, when I first read 

> Assign this property a valid MessageThrottler to apply message throttling on chat messages.

 I thought that "valid MessageThrottler" means a "valid implementation of MessageThrottler" that I had to write myself. Later I've found out that the meaning was smth like "properly configured MessageThrottler instance" since I can't assign anything else anyway. 
Now I keep thinking that maybe it would be a good idea to actually make MessageThrottler a base class/interface (or at least make its fields/methods protected/virtual), so that user can write his own logic for how messages are discarded.
For example, I haven't tested my bot on a large amount of users so I don't know if I would need message throttling (I don't use MessageThrottler right now), but if I would, I would probably like to prioritize some messages over the others. So reply to chat command would be more important than some minor notification.
This is just a random thought. What do you think?

**Comment by swiftyspiffy** [comment]
I really like the idea of A shared interface that can involve different types of throttlers. As you stated a default and a buffer to start off. The ability to assign one of the throttlers to a client, or maybe even a JoinedChannel object so that various throttlers can be applied to a client on a per-channel basis.

**Comment by swiftyspiffy** [comment]
Sorry about the year long delay, but it looks like @prom3theu5 just added code for rate limiting and throttlers. Will close this.
