### ISSUE TITLE
Change in event naming?

### ISSUE THREAD

**Issue by zerocarbthirty** [swiftyspiffy/TwitchLib#90]
Hi, I upgraded from 1.3.0 to 1.3.3 today and I noticed now my code based off of TwitchLib will no longer compile.. It appears that some things may have been moved around.

This:

client.OnConnected += new EventHandler<TwitchClient.OnConnectedArgs>(onConnected);

needed to be re-written as:

client.OnConnected += new EventHandler<TwitchLib.Events.Client.OnConnectedArgs>(onConnected);
                
Is this intentional or am I doing something wrong?

**Comment by zerocarbthirty** [comment]
Nevemind it looks like after i included a new reference i was able to simplify the names, still was kind of a loop there for a moment.

**Comment by swiftyspiffy** [comment]
Yes, there has been some renaming in order to bring about consistency across the library. Not a lot, but some events have been.

**Comment by swiftyspiffy** [comment]
I'm going to go ahead and close this now :)
