### ISSUE TITLE
Raw server response?

### ISSUE THREAD

**Issue by SeeingBlue** [swiftyspiffy/TwitchLib#91]
Is it possible to receive raw server messages?

**Comment by swiftyspiffy** [comment]
Getting every raw message? Not a the moment. You can listen to the OnMessageReceived and then access the RawIrcMessage via something like:

```
e.ChatMessage.RawIrcMessage
```

If you really need access, I don't see why an event can't be added that fires on every message received. Not sure about the implications on resources however.

**Comment by SeeingBlue** [comment]
I guess it's not completely necessary. I just like to see it. I like to see those pings mostly just to know everything is still going smoothly.

**Comment by swiftyspiffy** [comment]
When initializing TwitchClient, you can tell the library to print out debug messages. These messages include every message received from Twitch, as well as sent messages. This assumes you only need it for debugging/assurance, and not production.

**Comment by swiftyspiffy** [comment]
If you do want it for production though, let me know and I can add it :)

**Comment by SeeingBlue** [comment]
If it won't hurt performance unless used then sure! I like to offer the raw view, especially in a dev mode/edition.

**Comment by swiftyspiffy** [comment]
I don't think it should be a problem. Will edit this comment with the commit link once pushed.
