### ISSUE TITLE
StreamOfflineException spams console

### ISSUE THREAD

**Issue by D3thw0lf** [swiftyspiffy/TwitchLib#93]
If channel is offline my console gets blown away with this new StreamOfflineException ... I know this exception is new but can you add please that it only fires once or even can get set of "false" or something? I don't rly need this exception and removing it by pulling and updating w/o NuGet can't be the solution. :/

As always: Thanks a lot for continuously updating this great libary. :) <3 
![spammyshit](https://cloud.githubusercontent.com/assets/895448/21288518/84b30fe0-c485-11e6-8a9f-10e9e98ad46b.jpg)

**Comment by swiftyspiffy** [comment]
I'll look into this now! 

Would you be willing to post the code you are using that is causing this? That'd help I think.

**Comment by D3thw0lf** [comment]
TwitchLib.Models.API.Stream stream = null;
            try
            {
                stream = await TwitchApi.GetTwitchStream(textBox25.Text);
            } catch (StreamOfflineException)
            {
                // Nothing here
            } catch (BadResourceException)
            {
                // Nothing here
            }

**Comment by swiftyspiffy** [comment]
And that results in the image above? It's not in a loop or anything?

**Comment by D3thw0lf** [comment]
// Check if Channel is Live and Changes Username Color, updates Info-Center Content
        public async void IsChannelLive(object sender, EventArgs e)
        {
            // Grabbing Server API Data from last set Channel
            if (this.appSettings.Service == "twitch")
            {
                TwitchLib.Models.API.Stream stream = null;

                try
                {
                    stream = await TwitchApi.GetTwitchStream(this.appSettings.LastChannelName);
                }
                catch (StreamOfflineException)
                {
                    //
                }
                catch (BadResourceException)
                {
                    //
                }

                // Setting Context-Menu Items for Info-Center
                MenuItem InfoHeader = new MenuItem();
                MenuItem ChannelFPS = new MenuItem();
                MenuItem ChannelUptime = new MenuItem();
                MenuItem ChannelFollowerCount = new MenuItem();
                ListBox LastFollowerList = new ListBox();
etc.

**Comment by swiftyspiffy** [comment]
So do all those lines appear as a result of calling `IsChannelLive` once, or do you call `IsChannelLive` multiple times, resulting in all of those lines?

**Comment by D3thw0lf** [comment]
It's in a thread that starts onLoad

**Comment by swiftyspiffy** [comment]
So just to be clear, `IsChannelLive` is only called once for the duration of the application?

**Comment by D3thw0lf** [comment]
It's only once called on startup. After startup it goes through the code, the else stuff etc. and if it's done with that it starts from top to check again and again etc. until it reaches the point to reset the counter to 10 seconds again. I've to do this bc I need to know if the channel is live to show informations in a dropdown and also indicate this with changing colors on nametags (my software has a login so name color get's red if live etc.) and also to auto-update the avatar if they change theirs on twitch

**Comment by swiftyspiffy** [comment]
Ok, I've written a new function to check internally (silencing the exception TwitchLib users would see). The function is called `StreamIsLive(string channel)` and returns true or false boolean. Check commit below for details. The function is pretty redundant (since this functionality already exists), so there's a chance it could be removed in the future. But, for now you can use it (I'll release a new NuGet package tonight or tomorrow probably).

Commit: 551f654ecb77f498af35715651933c1640c26982

**Comment by swiftyspiffy** [comment]
I'm going to go ahead and close this, you'll want to use the function I added above called `StreamIsLive(string channel)` to check. It will return a true or false for you to work with.
