### ISSUE TITLE
Not compatible with .netstandardx.x

### ISSUE THREAD

**Issue by CrookedBadge** [swiftyspiffy/TwitchLib#94]
Hi,
First off! Great project and I am eager to try it out.
I see that it's aimed for the .NETFramework. Before I realised that I was planning on installing it on a .NET Core project, which has .NETStandard Framework (1.6 in my case). Got an error message saying that TwitchLib along with WebSocket4Net and Newtonsoft.Json are incompatible with .netstandard and lists the compatible frameworks (.netframework v2.0-v4.5 along with a few others).

```
Package TwitchLib 1.3.5 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package TwitchLib 1.3.5 supports: net45 (.NETFramework,Version=v4.5)
Package Newtonsoft.Json 7.0.1 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package Newtonsoft.Json 7.0.1 supports:
  - net20 (.NETFramework,Version=v2.0)
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
  - portable-dnxcore50+net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=net45+wp80+win8+wpa81+dnxcore50)
  - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
Package WebSocket4Net 0.14.1 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package WebSocket4Net 0.14.1 supports:
  - monoandroid23 (MonoAndroid,Version=v2.3)
  - monotouch10 (MonoTouch,Version=v1.0)
  - net20 (.NETFramework,Version=v2.0)
  - net35 (.NETFramework,Version=v3.5)
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
  - sl4 (Silverlight,Version=v4.0)
  - sl5 (Silverlight,Version=v5.0)
  - sl5-wp (Silverlight,Version=v5.0,Profile=WindowsPhone)
  - xamarinios10 (Xamarin.iOS,Version=v1.0)
One or more packages are incompatible with .NETStandard,Version=v1.6.
Package restore failed. Rolling back package changes for 'YourProject'.
```

The issue here is mainly me asking if you have any plans on making TwitchLib Compatible with the .NET Core? (I will of course try to pitch in in making it compatible, but doubt I'd be able to do it alone).

Cheers!

**Comment by igor523** [comment]
Hello!
Even if Cole will rewrite all of his code to this standart, there is another problem. All of dependencies of TwitchLib are incompatible, and this is not Cole's code to rewrite and this is huge amount of work in general. So, I think you shouldn't wait much about netstandart version

**Comment by CrookedBadge** [comment]
Seems reasonable. Rewriting all code to fit another standars is overkill. Maybe in the future there'll be libraries that can work as a substitute for the ones used now, so that .NETStandard is supported, that way there's no need for Cole to rewrite all the code, but for now I might just as well use .NETFramework or do my own home brew :) (doubt it'll be as good though ;) )

**Comment by swiftyspiffy** [comment]
Igor is correct, but yea, if there are libraries that conform, I would definitely look at implementing them. The biggest issue, which I think you referenced above, is Newtonsoft Json not being compatible. Eventually I'd like to drop the smartirc4net dependency, but the newtonsoft json is quite a bit more difficult to remove.

**Comment by Bond-009** [comment]
Just saying that the latest version of Newtonsoft Json works with .netstandard

**Comment by swiftyspiffy** [comment]
I'll look into this a bit more in the future to see if it is feasible. For now, I'll go ahead and close this. Thanks for the suggestion though!
