### ISSUE TITLE
Logged in client is mod?

### ISSUE THREAD

**Issue by JustMeDaFaq** [swiftyspiffy/TwitchLib#95]
Hi, is there any way checking if the client(user) im using to connect to a channel, is actually moderator on the channel im connected to? Without fetching the complete chatters list?

**Comment by swiftyspiffy** [comment]
Hello! Yes it is possible, you want to list to the OnUserStateChanged. It fires right after you join a channel, and includes all kinds of information about the user, including display name, subscriber status, and moderator status.

I just added it to the example application, you can see the commit here: https://github.com/swiftyspiffy/TwitchLib/commit/f19581bee623f76412aee615d3eb793f5f13e464

**Comment by JustMeDaFaq** [comment]
Thanks! Works without any issues! :)
